const QUIZ_DATA = [
    // 1-10: Stanica i njezina građa
    { "id": 1, "pitanje": "Koji dio stanice upravlja svim životnim procesima?", "opcije": ["Mitohondrij", "Kloroplast", "Jezgra", "Vakuola"], "tocan_odgovor": 2, "obasnjenje": "Jezgra sadrži nasljedni materijal i kontrolira stanicu." },
    { "id": 2, "pitanje": "Gdje se u stanici oslobađa energija iz hrane?", "opcije": ["U citoplazmi", "U mitohondriju", "U vakuoli", "U ribosomu"], "tocan_odgovor": 1, "obasnjenje": "Mitohondriji su elektrane stanice." },
    { "id": 3, "pitanje": "Koju organelu imaju biljne, ali ne i životinjske stanice?", "opcije": ["Jezgru", "Mitohondrij", "Kloroplast", "Membranu"], "tocan_odgovor": 2, "obasnjenje": "Kloroplasti služe za fotosintezu." },
    { "id": 4, "pitanje": "Što daje čvrstoću biljnoj stanici?", "opcije": ["Membrana", "Stanična stijenka", "Citoplazma", "Jezgra"], "tocan_odgovor": 1, "obasnjenje": "Stanična stijenka je vanjski čvrsti sloj." },
    { "id": 5, "pitanje": "Kako se naziva tekućina koja ispunjava stanicu?", "opcije": ["Krv", "Voda", "Citoplazma", "Limfa"], "tocan_odgovor": 2, "obasnjenje": "Citoplazma je želatinasta tvar unutar stanice." },
    { "id": 6, "pitanje": "Koji je osnovni građevni element svih živih bića?", "opcije": ["Molekula", "Stanica", "Atom", "Tkivo"], "tocan_odgovor": 1, "obasnjenje": "Sva živa bića izgrađena su od stanica." },
    { "id": 7, "pitanje": "Koju organelu na slici prepoznaješ kao 'elektranu stanice'?", "opcije": ["Jezgra", "Mitohondrij", "Kloroplast", "Vakuola"], "tocan_odgovor": 1, "slika": "assets/img/mitohondrij.svg", "obasnjenje": "Mitohondrij ima karakterističnu naboranu unutrašnju membranu." },
    { "id": 8, "pitanje": "Koji organizmi nemaju oblikovanu jezgru?", "opcije": ["Biljke", "Bakterije", "Životinje", "Gljive"], "tocan_odgovor": 1, "obasnjenje": "Bakterije su prokarioti i nemaju jezgru." },
    { "id": 9, "pitanje": "Što regulira ulazak i izlazak tvari iz stanice?", "opcije": ["Stanična stijenka", "Stanična membrana", "Jezgra", "Vakuola"], "tocan_odgovor": 1, "obasnjenje": "Membrana je selektivno propusna barijera." },
    { "id": 10, "pitanje": "U kojem se dijelu stanice nalazi nasljedna uputa (DNA)?", "opcije": ["U vakuoli", "U jezgri", "U citoplazmi", "U membrani"], "tocan_odgovor": 1, "obasnjenje": "DNA je smještena unutar stanične jezgre." },

    // 11-20: Tkiva i organizacija tijela
    { "id": 11, "pitanje": "Kako nazivamo skupinu stanica istog oblika i funkcije?", "opcije": ["Organ", "Tkivo", "Sustav", "Organizam"], "tocan_odgovor": 1, "obasnjenje": "Tkivo je skup sličnih stanica." },
    { "id": 12, "pitanje": "Koje tkivo kod biljaka služi za prijenos vode i minerala?", "opcije": ["Pokrovno", "Provodno", "Osnovno", "Potporno"], "tocan_odgovor": 1, "obasnjenje": "Provodno tkivo prenosi tvari kroz biljku." },
    { "id": 13, "pitanje": "Više različitih tkiva koja obavljaju zajedničku zadaću čini:", "opcije": ["Organizam", "Sustav organa", "Organ", "Višestaničnost"], "tocan_odgovor": 2, "obasnjenje": "Organ (npr. srce) građen je od više tkiva." },
    { "id": 14, "pitanje": "Koje tkivo omogućuje kretanje životinja?", "opcije": ["Živčano", "Mišićno", "Pokrovno", "Vezivno"], "tocan_odgovor": 1, "obasnjenje": "Mišićno tkivo ima sposobnost stezanja." },
    { "id": 15, "pitanje": "Kako nazivamo sustav koji upravlja radom svih organa?", "opcije": ["Probavni", "Živčani", "Dišni", "Mišićni"], "tocan_odgovor": 1, "obasnjenje": "Živčani sustav koordinira tijelo." },
    { "id": 16, "pitanje": "U što se udružuju procesi fotosinteze kod biljaka?", "opcije": ["U kloroplastima", "U korijenu", "U plodovima", "U cvjetovima"], "tocan_odgovor": 0, "obasnjenje": "Fotosinteza se odvija u zelenim dijelovima (kloroplastima)." },
    { "id": 17, "pitanje": "Proces u kojem od jedne majke stanice nastaju dvije kćeri stanice naziva se:", "opcije": ["Oplodnja", "Stanična dioba", "Disanje", "Rast"], "tocan_odgovor": 1, "obasnjenje": "Stanice se umnožavaju diobom." },
    { "id": 18, "pitanje": "Koje tkivo životinjama služi kao zaštita od vanjskih utjecaja?", "opcije": ["Provodno", "Vezivno", "Pokrovno", "Živčano"], "tocan_odgovor": 2, "obasnjenje": "Pokrovno tkivo gradi kožu i obloge organa." },
    { "id": 19, "pitanje": "Što je klorofil?", "opcije": ["Organela", "Zeleni pigment", "Tekućina u stanici", "Tkivo"], "tocan_odgovor": 1, "obasnjenje": "Klorofil upija energiju Sunčeve svjetlosti." },
    { "id": 20, "pitanje": "Više organa koji zajedno obavljaju složenu funkciju čine:", "opcije": ["Tkivo", "Sustav organa", "Organizam", "Ćeliju"], "tocan_odgovor": 1, "obasnjenje": "Npr. probavni sustav čine usta, želudac, crijeva..." },

    // 21-35: Raznolikost živog svijeta (Biljke, Životinje, Gljive)
    { "id": 21, "pitanje": "Koji organizmi sami sebi proizvode hranu procesom fotosinteze?", "opcije": ["Proizvođači", "Potrošači", "Razlagači", "Paraziti"], "tocan_odgovor": 0, "obasnjenje": "Zelene biljke su proizvođači (autotrofi)." },
    { "id": 22, "pitanje": "Kako se nazivaju organizmi koji se hrane drugim živim bićima?", "opcije": ["Autotrofi", "Heterotrofi", "Simbionti", "Proizvođači"], "tocan_odgovor": 1, "obasnjenje": "Heterotrofi (životinje, gljive) uzimaju gotovu hranu." },
    { "id": 23, "pitanje": "Gljive se hrane kao:", "opcije": ["Autotrofi", "Heterotrofi", "Proizvođači", "Biljožderi"], "tocan_odgovor": 1, "obasnjenje": "Gljive nisu biljke i moraju uzimati gotovu hranu." },
    { "id": 24, "pitanje": "Što su saprofiti?", "opcije": ["Biljke", "Razlagači uginulih tvari", "Paraziti na ljudima", "Predatori"], "tocan_odgovor": 1, "obasnjenje": "Saprofiti razlažu ostatke uginulih organizama." },
    { "id": 25, "pitanje": "Kako se razmnožavaju paprati i mahovine?", "opcije": ["Sjemenom", "Spolno i nespolno (sporama)", "Samo reznicama", "Plodovima"], "tocan_odgovor": 1, "obasnjenje": "Vaskularne bescvjetnjače koriste spore." },
    { "id": 26, "pitanje": "Koja je glavna funkcija korijena?", "opcije": ["Fotosinteza", "Učvršćivanje i upijanje vode", "Razmnožavanje", "Disanje"], "tocan_odgovor": 1, "obasnjenje": "Korijen crpi vodu i minerale iz tla." },
    { "id": 27, "pitanje": "Što nastaje u cvijetu nakon oplodnje?", "opcije": ["List", "Korijen", "Sjemenka i plod", "Stabljika"], "tocan_odgovor": 2, "obasnjenje": "Cvijet služi za razmnožavanje sjemenkama." },
    { "id": 28, "pitanje": "Koji plin biljke oslobađaju tijekom fotosinteze?", "opcije": ["Dušik", "Ugljikov dioksid", "Kisik", "Vodik"], "tocan_odgovor": 2, "obasnjenje": "Biljke nam daju kisik neophodan za disanje." },
    { "id": 29, "pitanje": "Simbioza gljiva i algi naziva se:", "opcije": ["Mikoriza", "Lišaj", "Plijesan", "Mahovina"], "tocan_odgovor": 1, "obasnjenje": "Lišajevi su zajednica dva organizma." },
    { "id": 30, "pitanje": "Koji je najjednostavniji višestanični životinjski organizam?", "opcije": ["Spužva", "Meduza", "Glista", "Puž"], "tocan_odgovor": 0, "obasnjenje": "Spužve nemaju prava tkiva ni organe." },
    { "id": 31, "pitanje": "Kojoj skupini pripadaju životinje s člankovitim nogama i vanjskim skeletom?", "opcije": ["Mekušci", "Člankonošci", "Bodljikaši", "Kralježnjaci"], "tocan_odgovor": 1, "obasnjenje": "Kukci i pauci su člankonošci." },
    { "id": 32, "pitanje": "Što karakterizira sve kralježnjake?", "opcije": ["Ljuske", "Kralježnica", "Pluća", "Krila"], "tocan_odgovor": 1, "obasnjenje": "Kralježnjaci imaju unutrašnji koštani kostur." },
    { "id": 33, "pitanje": "Koji kralježnjaci imaju stalnu temperaturu tijela?", "opcije": ["Ribe", "Gmazovi", "Ptice i sisavci", "Vodozemci"], "tocan_odgovor": 2, "obasnjenje": "Ptice i sisavci su toplokrvni." },
    { "id": 34, "pitanje": "Prijenos peludnih zrnaca na njušku tučka naziva se:", "opcije": ["Oplodnja", "Oprašivanje", "Klijanje", "Fotosinteza"], "tocan_odgovor": 1, "obasnjenje": "Oprašivanje prethodi oplodnji." },
    { "id": 35, "pitanje": "Kako žabe dišu kao odrasle jedinke?", "opcije": ["Samo škrgama", "Plućima i kožom", "Cjevčicama", "Samo kožom"], "tocan_odgovor": 1, "obasnjenje": "Vodozemci koriste i pluća i vlažnu kožu." },

    // 36-50: Ekologija i zdravlje
    { "id": 36, "pitanje": "Zajednica svih živih bića na nekom staništu naziva se:", "opcije": ["Biocenoza", "Biotop", "Ekosustav", "Populacija"], "tocan_odgovor": 0, "obasnjenje": "Biocenoza je životna zajednica." },
    { "id": 37, "pitanje": "Što čini ekosustav?", "opcije": ["Samo biljke", "Samo životinje", "Živa zajednica + stanište", "Samo tlo"], "tocan_odgovor": 2, "obasnjenje": "Ekosustav je Biotop + Biocenoza." },
    { "id": 38, "pitanje": "Koji je glavni izvor energije za život na Zemlji?", "opcije": ["Mjesec", "Voda", "Sunce", "Nafta"], "tocan_odgovor": 2, "obasnjenje": "Sunce pokreće fotosintezu i život." },
    { "id": 39, "pitanje": "Što su razlagači?", "opcije": ["Lavovi", "Bakterije i gljive", "Biljke", "Ljudi"], "tocan_odgovor": 1, "obasnjenje": "Razlagači vraćaju tvari iz uginulih bića u prirodu." },
    { "id": 40, "pitanje": "Kako nazivamo odnos u kojem jedan organizam živi na račun drugoga?", "opcije": ["Simbioza", "Parazitizam", "Natjecanje", "Mutualizam"], "tocan_odgovor": 1, "obasnjenje": "Parazit nanosi štetu domaćinu." },
    { "id": 41, "pitanje": "Više jedinki iste vrste na istom prostoru čini:", "opcije": ["Zajednicu", "Populaciju", "Ekosustav", "Vrstu"], "tocan_odgovor": 1, "obasnjenje": "Populacija su npr. svi zečevi u jednoj šumi." },
    { "id": 42, "pitanje": "Što je bioraznolikost?", "opcije": ["Broj ljudi", "Raznolikost živih bića", "Broj planina", "Zagađenje"], "tocan_odgovor": 1, "obasnjenje": "Bioraznolikost je bogatstvo vrsta na Zemlji." },
    { "id": 43, "pitanje": "Koji plin izaziva efekt staklenika i globalno zatopljenje?", "opcije": ["Kisik", "Ugljikov dioksid", "Helij", "Argon"], "tocan_odgovor": 1, "obasnjenje": "CO2 zadržava toplinu u atmosferi." },
    { "id": 44, "pitanje": "Što su endemi?", "opcije": ["Izumrle vrste", "Vrste koje žive samo na jednom području", "Sveprisutne vrste", "Opasne vrste"], "tocan_odgovor": 1, "obasnjenje": "Endemi imaju ograničeno stanište (npr. Velebitska degenija)." },
    { "id": 45, "pitanje": "Organizmi koji indikatorima čistoće zraka nazivaju se:", "opcije": ["Lišajevi", "Bakterije", "Štakori", "Gljive"], "tocan_odgovor": 0, "obasnjenje": "Lišajevi ne rastu tamo gdje je zrak zagađen." },
    { "id": 46, "pitanje": "Što je higijena?", "opcije": ["Samo pranje ruku", "Znanost o očuvanju zdravlja", "Odlazak liječniku", "Sport"], "tocan_odgovor": 1, "obasnjenje": "Higijena obuhvaća mjere za sprječavanje bolesti." },
    { "id": 47, "pitanje": "Koji su najčešći uzročnici zaraznih bolesti?", "opcije": ["Vitamini", "Bakterije i virusi", "Zdrava hrana", "Zrak"], "tocan_odgovor": 1, "obasnjenje": "Mikroorganizmi izazivaju infekcije." },
    { "id": 48, "pitanje": "Kako tijelo stvara otpornost na određene bolesti?", "opcije": ["Spavanjem", "Cijepljenjem i prebolijevanjem", "Trčanjem", "Gledanjem TV-a"], "tocan_odgovor": 1, "obasnjenje": "Imunitet nas štiti od ponovne zaraze." },
    { "id": 49, "pitanje": "Što je ovisnost?", "opcije": ["Hobi", "Teška bolest vezanosti uz supstanciju", "Zabava", "Navika"], "tocan_odgovor": 1, "obasnjenje": "Ovisnost o alkoholu, drogi ili internetu je ozbiljno stanje." },
    { "id": 50, "pitanje": "Koji organ kod ljudi služi za filtraciju krvi i izbacivanje štetnih tvari?", "opcije": ["Srce", "Pluća", "Bubrezi", "Želudac"], "tocan_odgovor": 2, "obasnjenje": "Bubrezi čiste našu krv." }
];
