const ENG_DATA = [
    { "id": 1, "semester": 1, "pitanje": "I _______ from Croatia.", "opcije": ["is", "be", "are", "am"], "tocan_odgovor": 3, "obasnjenje": "Uz zamjenicu 'I' uvijek koristimo 'am'." },
    { "id": 2, "semester": 1, "pitanje": "She _______ got a green bike.", "opcije": ["have", "has", "are", "is"], "tocan_odgovor": 1, "obasnjenje": "Za treće lice jednine (He/She/It) koristimo 'has got'." },
    { "id": 3, "semester": 1, "pitanje": "This is _______ apple.", "opcije": ["an", "the", "/", "a"], "tocan_odgovor": 0, "obasnjenje": "Koristimo 'an' ispred riječi koje počinju samoglasnikom." },
    { "id": 4, "semester": 1, "pitanje": "Look at _______! They are happy.", "opcije": ["theirs", "their", "they", "them"], "tocan_odgovor": 3, "obasnjenje": "'Them' je objektna zamjenica (pogledaj NJIH)." },
    { "id": 5, "semester": 1, "pitanje": "_______ you like pizza?", "opcije": ["Is", "Does", "Do", "Are"], "tocan_odgovor": 2, "obasnjenje": "Pitanja u Present Simple s 'You' počinju s 'Do'." },
    { "id": 6, "semester": 1, "pitanje": "My father _______ in a bank.", "opcije": ["works", "is work", "working", "work"], "tocan_odgovor": 0, "obasnjenje": "U Present Simple dodajemo -s za He/She/It." },
    { "id": 7, "semester": 1, "pitanje": "What is the plural of 'Child'?", "opcije": ["Childes", "Childs", "Childrens", "Children"], "tocan_odgovor": 3, "obasnjenje": "'Children' je nepravilna množina riječi child." },
    { "id": 8, "semester": 1, "pitanje": "_______ is your name?", "opcije": ["Who", "What", "Why", "Where"], "tocan_odgovor": 1, "obasnjenje": "'What' koristimo za pitanja o imenima i stvarima." },
    { "id": 9, "semester": 1, "pitanje": "These _______ my books.", "opcije": ["is", "be", "am", "are"], "tocan_odgovor": 3, "obasnjenje": "'These' je množina od 'this', pa koristimo 'are'." },
    { "id": 10, "semester": 1, "pitanje": "We _______ have English on Mondays.", "opcije": ["isn't", "don't", "doesn't", "aren't"], "tocan_odgovor": 1, "obasnjenje": "Negacija za 'We' u Present Simple je 'don't'." },
    { "id": 11, "semester": 1, "pitanje": "Her cats _______ very cute.", "opcije": ["are", "have", "am", "is"], "tocan_odgovor": 0, "obasnjenje": "'Cats' je množina, zato koristimo glagol 'are'." },
    { "id": 12, "semester": 1, "pitanje": "Can you help _______?", "opcije": ["me", "I", "mine", "my"], "tocan_odgovor": 0, "obasnjenje": "'Me' je objektna zamjenica (POMOZI MENI)." },
    { "id": 13, "semester": 1, "pitanje": "There _______ a pen on the desk.", "opcije": ["is", "are", "be", "am"], "tocan_odgovor": 0, "obasnjenje": "Za jedninu koristimo 'There is'." },
    { "id": 14, "semester": 1, "pitanje": "_______ your sister have a cat?", "opcije": ["Are", "Do", "Is", "Does"], "tocan_odgovor": 3, "obasnjenje": "'Your sister' je She, pa pitanje počinje s 'Does'." },
    { "id": 15, "semester": 1, "pitanje": "That is _______ car.", "opcije": ["mine", "me", "I", "my"], "tocan_odgovor": 3, "obasnjenje": "'My' je posvojna zamjenica koja stoji uz imenicu." },
    { "id": 16, "semester": 1, "pitanje": "The children _______ playing in the garden.", "opcije": ["be", "is", "are", "am"], "tocan_odgovor": 2, "obasnjenje": "'Children' je množina, pa koristimo 'are'." },
    { "id": 17, "semester": 1, "pitanje": "My friend _______ Croatian and English.", "opcije": ["speaking", "speaks", "speak", "is speak"], "tocan_odgovor": 1, "obasnjenje": "Dodajemo -s jer je friend (prijatelj) He ili She." },
    { "id": 18, "semester": 1, "pitanje": "Whose bag is this? It's _______.", "opcije": ["her", "she", "she's", "hers"], "tocan_odgovor": 3, "obasnjenje": "'Hers' koristimo samostalno na kraju rečenice." },
    { "id": 19, "semester": 1, "pitanje": "He _______ go to school on Saturdays.", "opcije": ["doesn't", "aren't", "don't", "isn't"], "tocan_odgovor": 0, "obasnjenje": "Negacija za He je 'doesn't'." },
    { "id": 20, "semester": 1, "pitanje": "Where _______ you from?", "opcije": ["is", "am", "are", "be"], "tocan_odgovor": 2, "obasnjenje": "Pitanje za porijeklo ide s 'are' uz 'you'." },
    { "id": 21, "semester": 1, "pitanje": "_______ is that girl? She is my sister.", "opcije": ["Where", "Who", "What", "Why"], "tocan_odgovor": 1, "obasnjenje": "'Who' koristimo kad pitamo za osobe." },
    { "id": 22, "semester": 1, "pitanje": "We _______ got any milk.", "opcije": ["doesn't", "haven't", "don't", "hasn't"], "tocan_odgovor": 1, "obasnjenje": "Za 'We' negacija je 'haven't got'." },
    { "id": 23, "semester": 1, "pitanje": "Put your books _______ the bag.", "opcije": ["in", "on", "at", "under"], "tocan_odgovor": 0, "obasnjenje": "'In' znači unutra (u torbu)." },
    { "id": 24, "semester": 1, "pitanje": "Is this your pen? Yes, it _______.", "opcije": ["am", "be", "is", "are"], "tocan_odgovor": 2, "obasnjenje": "Kratki potvrdi odgovor prati glagol 'is'." },
    { "id": 25, "semester": 1, "pitanje": "How _______ are you? I'm 11.", "opcije": ["much", "many", "old", "long"], "tocan_odgovor": 2, "obasnjenje": "'How old' je pitanje za godine." },
    { "id": 26, "semester": 2, "pitanje": "Look! It _______ right now.", "opcije": ["raining", "rain", "is raining", "rains"], "tocan_odgovor": 2, "obasnjenje": "Za radnju koja se događa SAD koristimo Present Continuous." },
    { "id": 27, "semester": 2, "pitanje": "I _______ a movie at the moment.", "opcije": ["watch", "watching", "is watching", "am watching"], "tocan_odgovor": 3, "obasnjenje": "Uz 'I' ide 'am' + glagol s nastavkom -ing." },
    { "id": 28, "semester": 2, "pitanje": "They _______ football in the park today.", "opcije": ["is playing", "are playing", "am playing", "play"], "tocan_odgovor": 1, "obasnjenje": "Present Continuous za množinu 'They are'." },
    { "id": 29, "semester": 2, "pitanje": "_______ she listening to music?", "opcije": ["Am", "Are", "Does", "Is"], "tocan_odgovor": 3, "obasnjenje": "Pitanje u Present Continuous za She počinje s 'Is'." },
    { "id": 30, "semester": 2, "pitanje": "We _______ not doing our homework.", "opcije": ["are", "is", "am", "be"], "tocan_odgovor": 0, "obasnjenje": "Negacija u Present Continuous za 'We' je 'are not'." },
    { "id": 31, "semester": 2, "pitanje": "Listen! My sister _______ a song.", "opcije": ["is singing", "are singing", "sings", "sing"], "tocan_odgovor": 0, "obasnjenje": "Glagol 'Listen!' signalizira Present Continuous." },
    { "id": 32, "semester": 2, "pitanje": "I am sitting _______ the chair.", "opcije": ["on", "under", "in", "behind"], "tocan_odgovor": 0, "obasnjenje": "Sjedimo NA stolici." },
    { "id": 33, "semester": 2, "pitanje": "There _______ five apples in the basket.", "opcije": ["am", "is", "be", "are"], "tocan_odgovor": 3, "obasnjenje": "'There are' koristimo za množinu." },
    { "id": 34, "semester": 2, "pitanje": "What _______ you doing?", "opcije": ["are", "am", "is", "do"], "tocan_odgovor": 0, "obasnjenje": "Pitanje u Present Continuous: Wh- + are + you + -ing?" },
    { "id": 35, "semester": 2, "pitanje": "He is _______ a book.", "opcije": ["reading", "reads", "read", "is read"], "tocan_odgovor": 0, "obasnjenje": "Nakon 'is' u Continuousu ide nastavak -ing." },
    { "id": 36, "semester": 2, "pitanje": "The cat is _______ the table.", "opcije": ["next to", "under", "behind", "on"], "tocan_odgovor": 1, "obasnjenje": "'Under' znači ispod." },
    { "id": 37, "semester": 2, "pitanje": "We are _______ lunch now.", "opcije": ["eat", "is eating", "eating", "eats"], "tocan_odgovor": 2, "obasnjenje": "Radnja koja traje sada (eating)." },
    { "id": 38, "semester": 2, "pitanje": "Are you _______? No, I'm not.", "opcije": ["cry", "cries", "cried", "crying"], "tocan_odgovor": 3, "obasnjenje": "Pitanje o trenutačnoj radnji (-ing)." },
    { "id": 39, "semester": 2, "pitanje": "There isn't _______ orange in my bag.", "opcije": ["an", "a", "any", "some"], "tocan_odgovor": 0, "obasnjenje": "'An' ispred samoglasnika u jednini." },
    { "id": 40, "semester": 2, "pitanje": "Please stand _______ your friend.", "opcije": ["behind", "under", "on", "next to"], "tocan_odgovor": 3, "obasnjenje": "'Next to' znači pokraj ili pored." },
    { "id": 41, "semester": 2, "pitanje": "Where _______ the keys? They are on the desk.", "opcije": ["is", "be", "am", "are"], "tocan_odgovor": 3, "obasnjenje": "'Keys' su množina, pa koristimo 'are'." },
    { "id": 42, "semester": 2, "pitanje": "She _______ tennis every Friday.", "opcije": ["play", "is playing", "playing", "plays"], "tocan_odgovor": 3, "obasnjenje": "'Every Friday' sugerira naviku (Present Simple - s)." },
    { "id": 43, "semester": 2, "pitanje": "I usually _______ breakfast at 7 o'clock.", "opcije": ["having", "am have", "have", "has"], "tocan_odgovor": 2, "obasnjenje": "'Usually' signalizira Present Simple." },
    { "id": 44, "semester": 2, "pitanje": "My brother _______ like vegetables.", "opcije": ["isn't", "aren't", "doesn't", "don't"], "tocan_odgovor": 2, "obasnjenje": "Negacija za He (brother) je 'doesn't'." },
    { "id": 45, "semester": 2, "pitanje": "Look at that bird! It _______ red and blue.", "opcije": ["have", "are", "is", "am"], "tocan_odgovor": 2, "obasnjenje": "Opisujemo pticu (it is)." },
    { "id": 46, "semester": 2, "pitanje": "Are _______ your pencils? Yes, they are.", "opcije": ["these", "this", "that", "it"], "tocan_odgovor": 0, "obasnjenje": "'Pencils' je množina, blizu nas (these)." },
    { "id": 47, "semester": 2, "pitanje": "I can't find _______ phone.", "opcije": ["mine", "I", "me", "my"], "tocan_odgovor": 3, "obasnjenje": "'My' stoji ispred imenice." },
    { "id": 48, "semester": 2, "pitanje": "Can you swim? Yes, I _______.", "opcije": ["do", "am", "is", "can"], "tocan_odgovor": 3, "obasnjenje": "Odgovor na pitanje s 'Can' ide s 'can'." },
    { "id": 49, "semester": 2, "pitanje": "He is _______ a shower at the moment.", "opcije": ["takes", "is taking", "taking", "take"], "tocan_odgovor": 2, "obasnjenje": "'At the moment' traži nastavak -ing." },
    { "id": 50, "semester": 2, "pitanje": "Dogs _______ run very fast.", "opcije": ["is", "can", "am", "has"], "tocan_odgovor": 1, "obasnjenje": "'Can' izražava sposobnost." },
    { "id": 51, "semester": 1, "pitanje": "What is 'Konj' in English?", "opcije": ["Horse", "Sheep", "Pig", "Cow"], "tocan_odgovor": 0, "obasnjenje": "Horse je konj." },
    { "id": 52, "semester": 1, "pitanje": "Which one is furniture?", "opcije": ["Sun", "Cat", "Apple", "Table"], "tocan_odgovor": 3, "obasnjenje": "Table (stol) je komad namještaja." },
    { "id": 53, "semester": 1, "pitanje": "What is 'Mrkva'?", "opcije": ["Potato", "Tomato", "Carrot", "Onion"], "tocan_odgovor": 2, "obasnjenje": "Carrot je mrkva." },
    { "id": 54, "semester": 1, "pitanje": "Bananas are _______.", "opcije": ["Yellow", "Blue", "Red", "Green"], "tocan_odgovor": 0, "obasnjenje": "Banane su žute (yellow)." },
    { "id": 55, "semester": 1, "pitanje": "Who works in a school?", "opcije": ["Doctor", "Teacher", "Pilot", "Baker"], "tocan_odgovor": 1, "obasnjenje": "Teacher (učitelj) radi u školi." },
    { "id": 56, "semester": 1, "pitanje": "You carry books in a _______.", "opcije": ["Kitchen", "Schoolbag", "Bed", "Fridge"], "tocan_odgovor": 1, "obasnjenje": "Knjige nosimo u školskoj torbi (schoolbag)." },
    { "id": 57, "semester": 1, "pitanje": "Where do you watch TV?", "opcije": ["Garden", "Living room", "Bathroom", "Garage"], "tocan_odgovor": 1, "obasnjenje": "TV obično gledamo u dnevnom boravku (living room)." },
    { "id": 58, "semester": 1, "pitanje": "A red fruit is an _______.", "opcije": ["Banana", "Pear", "Apple", "Orange"], "tocan_odgovor": 2, "obasnjenje": "Apple (jabuka) je često crvena." },
    { "id": 59, "semester": 1, "pitanje": "The king of the jungle is the _______.", "opcije": ["Giraffe", "Monkey", "Lion", "Elephant"], "tocan_odgovor": 2, "obasnjenje": "Lion (lav) je kralj džungle." },
    { "id": 60, "semester": 1, "pitanje": "You type on a _______.", "opcije": ["Chair", "Door", "Computer", "Window"], "tocan_odgovor": 2, "obasnjenje": "Tipkamo na računalu (computer)." },
    { "id": 61, "semester": 1, "pitanje": "Mummy is my _______.", "opcije": ["Mother", "Father", "Sister", "Brother"], "tocan_odgovor": 0, "obasnjenje": "Mother je majka." },
    { "id": 62, "semester": 1, "pitanje": "Water is for _______.", "opcije": ["Reading", "Running", "Sleeping", "Swimming"], "tocan_odgovor": 3, "obasnjenje": "U vodi plivamo (swimming)." },
    { "id": 63, "semester": 1, "pitanje": "Where are many books?", "opcije": ["Library", "Hospital", "Supermarket", "Cinema"], "tocan_odgovor": 0, "obasnjenje": "U knjižnici (library) ima puno knjiga." },
    { "id": 64, "semester": 1, "pitanje": "If you smile, you are _______.", "opcije": ["Tired", "Sad", "Angry", "Happy"], "tocan_odgovor": 3, "obasnjenje": "Kad se smijemo, sretni smo (happy)." },
    { "id": 65, "semester": 1, "pitanje": "You wear _______ on your feet.", "opcije": ["Gloves", "Hats", "Shirts", "Shoes"], "tocan_odgovor": 3, "obasnjenje": "Na nogama nosimo cipele (shoes)." },
    { "id": 66, "semester": 1, "pitanje": "White drink from a cow:", "opcije": ["Milk", "Tea", "Juice", "Water"], "tocan_odgovor": 0, "obasnjenje": "Krava daje mlijeko (milk)." },
    { "id": 67, "semester": 1, "pitanje": "A dangerous green animal:", "opcije": ["Parrot", "Rabbit", "Crocodile", "Frog"], "tocan_odgovor": 2, "obasnjenje": "Krokodil je opasan i zelen." },
    { "id": 68, "semester": 1, "pitanje": "You look out of the _______.", "opcije": ["Wall", "Ceiling", "Floor", "Window"], "tocan_odgovor": 3, "obasnjenje": "Gledamo kroz prozor (window)." },
    { "id": 69, "semester": 1, "pitanje": "You write with a _______.", "opcije": ["Pencil", "Ruler", "Glue", "Eraser"], "tocan_odgovor": 0, "obasnjenje": "Pišemo olovkom (pencil)." },
    { "id": 70, "semester": 1, "pitanje": "My aunt's son is my _______.", "opcije": ["Father", "Cousin", "Brother", "Uncle"], "tocan_odgovor": 1, "obasnjenje": "Cousin je bratić ili sestrična." },
    { "id": 71, "semester": 1, "pitanje": "White grains you eat:", "opcije": ["Meat", "Pasta", "Bread", "Rice"], "tocan_odgovor": 3, "obasnjenje": "Rice je riža." },
    { "id": 72, "semester": 1, "pitanje": "The sky is _______.", "opcije": ["Orange", "Black", "Pink", "Blue"], "tocan_odgovor": 3, "obasnjenje": "Nebo je plavo (blue)." },
    { "id": 73, "semester": 1, "pitanje": "Where does mum cook?", "opcije": ["Kitchen", "Attic", "Bathroom", "Bedroom"], "tocan_odgovor": 0, "obasnjenje": "Kuha se u kuhinji (kitchen)." },
    { "id": 74, "semester": 1, "pitanje": "Where do you watch movies?", "opcije": ["School", "Bank", "Park", "Cinema"], "tocan_odgovor": 3, "obasnjenje": "Filmove gledamo u kinu (cinema)." },
    { "id": 75, "semester": 1, "pitanje": "Music instrument with strings:", "opcije": ["Drum", "Guitar", "Trumpet", "Piano"], "tocan_odgovor": 1, "obasnjenje": "Gitara ima žice." },
    { "id": 76, "semester": 2, "pitanje": "Big grey animal with a trunk:", "opcije": ["Tiger", "Elephant", "Hippo", "Bear"], "tocan_odgovor": 1, "obasnjenje": "Elephant (slon) ima surlu." },
    { "id": 77, "semester": 2, "pitanje": "You make sandwiches with _______.", "opcije": ["Milk", "Bread", "Water", "Sugar"], "tocan_odgovor": 1, "obasnjenje": "Sendviče radimo s kruhom (bread)." },
    { "id": 78, "semester": 2, "pitanje": "Grass is _______.", "opcije": ["Green", "Purple", "Brown", "White"], "tocan_odgovor": 0, "obasnjenje": "Trava je zelena (green)." },
    { "id": 79, "semester": 2, "pitanje": "Where is the shower?", "opcije": ["Garage", "Kitchen", "Bathroom", "Garden"], "tocan_odgovor": 2, "obasnjenje": "Tuš je u kupaonici (bathroom)." },
    { "id": 80, "semester": 2, "pitanje": "Who helps sick people?", "opcije": ["Artist", "Chef", "Doctor", "Waiter"], "tocan_odgovor": 2, "obasnjenje": "Liječnik (doctor) pomaže bolesnima." },
    { "id": 81, "semester": 2, "pitanje": "Transport with two wheels:", "opcije": ["Bus", "Car", "Train", "Bicycle"], "tocan_odgovor": 3, "obasnjenje": "Bicikl ima dva kotača." },
    { "id": 82, "semester": 2, "pitanje": "A fruit and a color:", "opcije": ["Apple", "Cherry", "Lemon", "Orange"], "tocan_odgovor": 3, "obasnjenje": "Orange je i naranča i narančasta boja." },
    { "id": 83, "semester": 2, "pitanje": "You sleep in a _______.", "opcije": ["Table", "Desk", "Sofa", "Bed"], "tocan_odgovor": 3, "obasnjenje": "Spavamo u krevetu (bed)." },
    { "id": 84, "semester": 2, "pitanje": "Where do children play outside?", "opcije": ["Park", "Library", "Cinema", "Museum"], "tocan_odgovor": 0, "obasnjenje": "Djeca se igraju u parku." },
    { "id": 85, "semester": 2, "pitanje": "It says 'Meow':", "opcije": ["Hamster", "Cat", "Dog", "Fish"], "tocan_odgovor": 1, "obasnjenje": "Mačka (cat) kaže 'meow'." },
    { "id": 86, "semester": 2, "pitanje": "Transparent liquid to drink:", "opcije": ["Coffee", "Cola", "Juice", "Water"], "tocan_odgovor": 3, "obasnjenje": "Water je voda." },
    { "id": 87, "semester": 2, "pitanje": "Hot thing in the sky:", "opcije": ["Moon", "Cloud", "Star", "Sun"], "tocan_odgovor": 3, "obasnjenje": "Sunce (sun) grije." },
    { "id": 88, "semester": 2, "pitanje": "You wear it on your head:", "opcije": ["Sock", "Jean", "Coat", "Hat"], "tocan_odgovor": 3, "obasnjenje": "Na glavi nosimo šešir ili kapu (hat)." },
    { "id": 89, "semester": 2, "pitanje": "You read a _______.", "opcije": ["Book", "Key", "Phone", "Pen"], "tocan_odgovor": 0, "obasnjenje": "Čitamo knjigu (book)." },
    { "id": 90, "semester": 2, "pitanje": "My mother's daughter is my _______.", "opcije": ["Brother", "Cousin", "Sister", "Aunt"], "tocan_odgovor": 2, "obasnjenje": "Sister je sestra." },
    { "id": 91, "semester": 2, "pitanje": "Long yellow fruit:", "opcije": ["Melon", "Apple", "Banana", "Grape"], "tocan_odgovor": 2, "obasnjenje": "Banana je duga i žuta." },
    { "id": 92, "semester": 2, "pitanje": "You sit on a _______.", "opcije": ["Plate", "Floor", "Book", "Chair"], "tocan_odgovor": 3, "obasnjenje": "Sjedimo na stolici (chair)." },
    { "id": 93, "semester": 2, "pitanje": "Animal that can fly:", "opcije": ["Dog", "Fish", "Bird", "Snake"], "tocan_odgovor": 2, "obasnjenje": "Bird (ptica) leti." },
    { "id": 94, "semester": 2, "pitanje": "Cars drive on the _______.", "opcije": ["Sea", "Street", "Sky", "House"], "tocan_odgovor": 1, "obasnjenje": "Auti voze ulicom (street)." },
    { "id": 95, "semester": 2, "pitanje": "Sport with a black and white ball:", "opcije": ["Soccer", "Basketball", "Tennis", "Golf"], "tocan_odgovor": 0, "obasnjenje": "Soccer (nogomet) je nogomet." },
    { "id": 96, "semester": 2, "pitanje": "Water falling from the sky:", "opcije": ["Sun", "Rain", "Snow", "Wind"], "tocan_odgovor": 1, "obasnjenje": "Rain je kiša." },
    { "id": 97, "semester": 2, "pitanje": "Sweet food for birthdays:", "opcije": ["Salad", "Soup", "Pizza", "Cake"], "tocan_odgovor": 3, "obasnjenje": "Cake je torta." },
    { "id": 98, "semester": 2, "pitanje": "It says 'Woof':", "opcije": ["Mouse", "Bird", "Cat", "Dog"], "tocan_odgovor": 3, "obasnjenje": "Pas (dog) kaže 'vau'." },
    { "id": 99, "semester": 2, "pitanje": "You wear it on your body:", "opcije": ["Shoe", "Hat", "Sock", "Shirt"], "tocan_odgovor": 3, "obasnjenje": "Shirt je košulja ili majica." },
    { "id": 100, "semester": 2, "pitanje": "Where you sit in class:", "opcije": ["Kitchen", "Desk", "Sofa", "Bed"], "tocan_odgovor": 1, "obasnjenje": "U razredu sjedimo za radnim stolom (desk)." }
];
