const ENG_DATA = [
    { "id": 1, "semester": 1, "pitanje": "I _______ from Croatia.", "opcije": ["is", "am", "are", "be"], "tocan_odgovor": 1, "obasnjenje": "Uz zamjenicu 'I' uvijek koristimo 'am'." },
    { "id": 2, "semester": 1, "pitanje": "She _______ got a green bike.", "opcije": ["have", "has", "is", "are"], "tocan_odgovor": 1, "obasnjenje": "Za treće lice jednine (He/She/It) koristimo 'has got'." },
    { "id": 3, "semester": 1, "pitanje": "This is _______ apple.", "opcije": ["a", "an", "the", "/"], "tocan_odgovor": 1, "obasnjenje": "Koristimo 'an' ispred riječi koje počinju samoglasnikom." },
    { "id": 4, "semester": 1, "pitanje": "Look at _______! They are happy.", "opcije": ["they", "them", "their", "theirs"], "tocan_odgovor": 1, "obasnjenje": "'Them' je objektna zamjenica (pogledaj NJIH)." },
    { "id": 5, "semester": 1, "pitanje": "_______ you like pizza?", "opcije": ["Do", "Does", "Are", "Is"], "tocan_odgovor": 0, "obasnjenje": "Pitanja u Present Simple s 'You' počinju s 'Do'." },
    { "id": 6, "semester": 1, "pitanje": "My father _______ in a bank.", "opcije": ["work", "works", "working", "is work"], "tocan_odgovor": 1, "obasnjenje": "U Present Simple dodajemo -s za He/She/It." },
    { "id": 7, "semester": 1, "pitanje": "What is the plural of 'Child'?", "opcije": ["Childs", "Children", "Childrens", "Childes"], "tocan_odgovor": 1, "obasnjenje": "'Children' je nepravilna množina riječi child." },
    { "id": 8, "semester": 1, "pitanje": "_______ is your name?", "opcije": ["Who", "Where", "What", "Why"], "tocan_odgovor": 2, "obasnjenje": "'What' koristimo za pitanja o imenima i stvarima." },
    { "id": 9, "semester": 1, "pitanje": "These _______ my books.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 1, "obasnjenje": "'These' je množina od 'this', pa koristimo 'are'." },
    { "id": 10, "semester": 1, "pitanje": "We _______ have English on Mondays.", "opcije": ["doesn't", "don't", "aren't", "isn't"], "tocan_odgovor": 1, "obasnjenje": "Negacija za 'We' u Present Simple je 'don't'." },
    { "id": 11, "semester": 1, "pitanje": "Her cats _______ very cute.", "opcije": ["is", "are", "am", "have"], "tocan_odgovor": 1, "obasnjenje": " 'Cats' je množina, zato koristimo glagol 'are'." },
    { "id": 12, "semester": 1, "pitanje": "Can you help _______?", "opcije": ["I", "me", "my", "mine"], "tocan_odgovor": 1, "obasnjenje": "'Me' je objektna zamjenica (POMOZI MENI)." },
    { "id": 13, "semester": 1, "pitanje": "There _______ a pen on the desk.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 0, "obasnjenje": "Za jedninu koristimo 'There is'." },
    { "id": 14, "semester": 1, "pitanje": "_______ your sister have a cat?", "opcije": ["Do", "Does", "Is", "Are"], "tocan_odgovor": 1, "obasnjenje": "'Your sister' je She, pa pitanje počinje s 'Does'." },
    { "id": 15, "semester": 1, "pitanje": "That is _______ car.", "opcije": ["me", "my", "mine", "I"], "tocan_odgovor": 1, "obasnjenje": "'My' je posvojna zamjenica koja stoji uz imenicu." },
    { "id": 16, "semester": 1, "pitanje": "The children _______ playing in the garden.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 1, "obasnjenje": "'Children' je množina, pa koristimo 'are'." },
    { "id": 17, "semester": 1, "pitanje": "My friend _______ Croatian and English.", "opcije": ["speak", "speaks", "is speak", "speaking"], "tocan_odgovor": 1, "obasnjenje": "Dodajemo -s jer je friend (prijatelj) He ili She." },
    { "id": 18, "semester": 1, "pitanje": "Whose bag is this? It's _______.", "opcije": ["her", "hers", "she", "she's"], "tocan_odgovor": 1, "obasnjenje": "'Hers' koristimo samostalno na kraju rečenice." },
    { "id": 19, "semester": 1, "pitanje": "He _______ go to school on Saturdays.", "opcije": ["don't", "doesn't", "isn't", "aren't"], "tocan_odgovor": 1, "obasnjenje": "Negacija za He je 'doesn't'." },
    { "id": 20, "semester": 1, "pitanje": "Where _______ you from?", "opcije": ["am", "is", "are", "be"], "tocan_odgovor": 2, "obasnjenje": "Pitanje za porijeklo ide s 'are' uz 'you'." },
    { "id": 21, "semester": 1, "pitanje": "_______ is that girl? She is my sister.", "opcije": ["What", "Who", "Where", "Why"], "tocan_odgovor": 1, "obasnjenje": "'Who' koristimo kad pitamo za osobe." },
    { "id": 22, "semester": 1, "pitanje": "We _______ got any milk.", "opcije": ["haven't", "hasn't", "don't", "doesn't"], "tocan_odgovor": 0, "obasnjenje": "Za 'We' negacija je 'haven't got'." },
    { "id": 23, "semester": 1, "pitanje": "Put your books _______ the bag.", "opcije": ["on", "under", "in", "at"], "tocan_odgovor": 2, "obasnjenje": "'In' znači unutra (u torbu)." },
    { "id": 24, "semester": 1, "pitanje": "Is this your pen? Yes, it _______.", "opcije": ["am", "is", "are", "be"], "tocan_odgovor": 1, "obasnjenje": "Kratki potvrdi odgovor prati glagol 'is'." },
    { "id": 25, "semester": 1, "pitanje": "How _______ are you? I'm 11.", "opcije": ["old", "many", "much", "long"], "tocan_odgovor": 0, "obasnjenje": "'How old' je pitanje za godine." },
    { "id": 26, "semester": 2, "pitanje": "Look! It _______ right now.", "opcije": ["rains", "is raining", "rain", "raining"], "tocan_odgovor": 1, "obasnjenje": "Za radnju koja se događa SAD koristimo Present Continuous." },
    { "id": 27, "semester": 2, "pitanje": "I _______ a movie at the moment.", "opcije": ["watch", "watching", "am watching", "is watching"], "tocan_odgovor": 2, "obasnjenje": "Uz 'I' ide 'am' + glagol s nastavkom -ing." },
    { "id": 28, "semester": 2, "pitanje": "They _______ football in the park today.", "opcije": ["am playing", "is playing", "are playing", "play"], "tocan_odgovor": 2, "obasnjenje": "Present Continuous za množinu 'They are'." },
    { "id": 29, "semester": 2, "pitanje": "_______ she listening to music?", "opcije": ["Is", "Are", "Am", "Does"], "tocan_odgovor": 0, "obasnjenje": "Pitanje u Present Continuous za She počinje s 'Is'." },
    { "id": 30, "semester": 2, "pitanje": "We _______ not doing our homework.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 1, "obasnjenje": "Negacija u Present Continuous za 'We' je 'are not'." },
    { "id": 31, "semester": 2, "pitanje": "Listen! My sister _______ a song.", "opcije": ["sing", "sings", "is singing", "are singing"], "tocan_odgovor": 2, "obasnjenje": "Glagol 'Listen!' signalizira Present Continuous." },
    { "id": 32, "semester": 2, "pitanje": "I am sitting _______ the chair.", "opcije": ["on", "under", "in", "behind"], "tocan_odgovor": 0, "obasnjenje": "Sjedimo NA stolici." },
    { "id": 33, "semester": 2, "pitanje": "There _______ five apples in the basket.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 1, "obasnjenje": "'There are' koristimo za množinu." },
    { "id": 34, "semester": 2, "pitanje": "What _______ you doing?", "opcije": ["is", "are", "am", "do"], "tocan_odgovor": 1, "obasnjenje": "Pitanje u Present Continuous: Wh- + are + you + -ing?" },
    { "id": 35, "semester": 2, "pitanje": "He is _______ a book.", "opcije": ["read", "reads", "reading", "is read"], "tocan_odgovor": 2, "obasnjenje": "Nakon 'is' u Continuousu ide nastavak -ing." },
    { "id": 36, "semester": 2, "pitanje": "The cat is _______ the table.", "opcije": ["on", "under", "behind", "next to"], "tocan_odgovor": 1, "obasnjenje": "'Under' znači ispod." },
    { "id": 37, "semester": 2, "pitanje": "We are _______ lunch now.", "opcije": ["eat", "eats", "eating", "is eating"], "tocan_odgovor": 2, "obasnjenje": "Radnja koja traje sada (eating)." },
    { "id": 38, "semester": 2, "pitanje": "Are you _______? No, I'm not.", "opcije": ["cry", "crying", "cries", "cried"], "tocan_odgovor": 1, "obasnjenje": "Pitanje o trenutačnoj radnji (-ing)." },
    { "id": 39, "semester": 2, "pitanje": "There isn't _______ orange in my bag.", "opcije": ["a", "an", "some", "any"], "tocan_odgovor": 1, "obasnjenje": "'An' ispred samoglasnika u jednini." },
    { "id": 40, "semester": 2, "pitanje": "Please stand _______ your friend.", "opcije": ["on", "under", "next to", "behind"], "tocan_odgovor": 2, "obasnjenje": "'Next to' znači pokraj ili pored." },
    { "id": 41, "semester": 2, "pitanje": "Where _______ the keys? They are on the desk.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 1, "obasnjenje": "'Keys' su množina, pa koristimo 'are'." },
    { "id": 42, "semester": 2, "pitanje": "She _______ tennis every Friday.", "opcije": ["play", "plays", "is playing", "playing"], "tocan_odgovor": 1, "obasnjenje": "'Every Friday' sugerira naviku (Present Simple - s)." },
    { "id": 43, "semester": 2, "pitanje": "I usually _______ breakfast at 7 o'clock.", "opcije": ["have", "has", "having", "am have"], "tocan_odgovor": 0, "obasnjenje": "'Usually' signalizira Present Simple." },
    { "id": 44, "semester": 2, "pitanje": "My brother _______ like vegetables.", "opcije": ["don't", "doesn't", "isn't", "aren't"], "tocan_odgovor": 1, "obasnjenje": "Negacija za He (brother) je 'doesn't'." },
    { "id": 45, "semester": 2, "pitanje": "Look at that bird! It _______ red and blue.", "opcije": ["is", "am", "are", "have"], "tocan_odgovor": 0, "obasnjenje": "Opisujemo pticu (it is)." },
    { "id": 46, "semester": 2, "pitanje": "Are _______ your pencils? Yes, they are.", "opcije": ["this", "that", "these", "it"], "tocan_odgovor": 2, "obasnjenje": "'Pencils' je množina, blizu nas (these)." },
    { "id": 47, "semester": 2, "pitanje": "I can't find _______ phone.", "opcije": ["I", "me", "my", "mine"], "tocan_odgovor": 2, "obasnjenje": "'My' stoji ispred imenice." },
    { "id": 48, "semester": 2, "pitanje": "Can you swim? Yes, I _______.", "opcije": ["am", "can", "do", "is"], "tocan_odgovor": 1, "obasnjenje": "Odgovor na pitanje s 'Can' ide s 'can'." },
    { "id": 49, "semester": 2, "pitanje": "He is _______ a shower at the moment.", "opcije": ["take", "takes", "taking", "is taking"], "tocan_odgovor": 2, "obasnjenje": "'At the moment' traži nastavak -ing." },
    { "id": 50, "semester": 2, "pitanje": "Dogs _______ run very fast.", "opcije": ["can", "am", "is", "has"], "tocan_odgovor": 0, "obasnjenje": "'Can' izražava sposobnost." }
];
