const ENG_DATA = [
    { "id": 1, "semester": 1, "pitanje": "How do you say 'Jabuka' in English?", "opcije": ["Banana", "Apple", "Orange", "Grape"], "tocan_odgovor": 1, "obasnjenje": "Apple je jabuka." },
    { "id": 2, "semester": 1, "pitanje": "Which word is a color?", "opcije": ["Run", "Blue", "Happy", "Chair"], "tocan_odgovor": 1, "obasnjenje": "Blue je plava boja." },
    { "id": 3, "semester": 1, "pitanje": "How do you introduce yourself?", "opcije": ["Good night!", "My name is...", "Thank you.", "Go away!"], "tocan_odgovor": 1, "obasnjenje": "My name is... koristimo za predstavljanje." },
    { "id": 4, "semester": 1, "pitanje": "Who is your mother's sister?", "opcije": ["Uncle", "Aunt", "Cousin", "Brother"], "tocan_odgovor": 1, "obasnjenje": "Aunt je teta." },
    { "id": 5, "semester": 1, "pitanje": "What do you use to write in your notebook?", "opcije": ["Eraser", "Pen", "Ruler", "Bag"], "tocan_odgovor": 1, "obasnjenje": "Pen je kemijska olovka." },
    { "id": 6, "semester": 1, "pitanje": "I ___ a student.", "opcije": ["is", "are", "am", "be"], "tocan_odgovor": 2, "obasnjenje": "Uz 'I' ide 'am'." },
    { "id": 7, "semester": 1, "pitanje": "How many fingers do you have on one hand?", "opcije": ["Three", "Four", "Five", "Ten"], "tocan_odgovor": 2, "obasnjenje": "Imamo pet prstiju na jednoj ruci." },
    { "id": 8, "semester": 1, "pitanje": "What is the plural of 'Book'?", "opcije": ["Bookes", "Books", "Bookies", "Book"], "tocan_odgovor": 1, "obasnjenje": "Množina od book je books." },
    { "id": 9, "semester": 1, "pitanje": "Which animal can fly?", "opcije": ["Dog", "Cat", "Bird", "Fish"], "tocan_odgovor": 2, "obasnjenje": "Bird je ptica." },
    { "id": 10, "semester": 1, "pitanje": "What day comes after Monday?", "opcije": ["Sunday", "Wednesday", "Tuesday", "Friday"], "tocan_odgovor": 2, "obasnjenje": "Tuesday je utorak." },
    { "id": 11, "semester": 1, "pitanje": "He ___ a big dog.", "opcije": ["have", "has", "am", "are"], "tocan_odgovor": 1, "obasnjenje": "Uz 'He/She/It' ide 'has'." },
    { "id": 12, "semester": 1, "pitanje": "How do you say 'Olovka' in English?", "opcije": ["Ruler", "Pencil", "Eraser", "Sharpener"], "tocan_odgovor": 1, "obasnjenje": "Pencil je olovka." },
    { "id": 13, "semester": 1, "pitanje": "What color is a banana?", "opcije": ["Red", "Blue", "Yellow", "Green"], "tocan_odgovor": 2, "obasnjenje": "Yellow je žuta." },
    { "id": 14, "semester": 1, "pitanje": "'Father' is another word for...", "opcije": ["Brother", "Uncle", "Dad", "Cousin"], "tocan_odgovor": 2, "obasnjenje": "Dad je tata." },
    { "id": 15, "semester": 1, "pitanje": "Good ___! (Morning greeting)", "opcije": ["Night", "Evening", "Morning", "Afternoon"], "tocan_odgovor": 2, "obasnjenje": "Good morning je Dobro jutro." },
    { "id": 16, "semester": 1, "pitanje": "Where is London?", "opcije": ["In Croatia", "In the UK", "In Italy", "In France"], "tocan_odgovor": 1, "obasnjenje": "London je u Ujedinjenom Kraljevstvu." },
    { "id": 17, "semester": 1, "pitanje": "10 + 5 = ?", "opcije": ["Ten", "Twelve", "Fifteen", "Twenty"], "tocan_odgovor": 2, "obasnjenje": "Fifteen je petnaest." },
    { "id": 18, "semester": 1, "pitanje": "Is she a teacher? Yes, she ___.", "opcije": ["is", "am", "are", "be"], "tocan_odgovor": 0, "obasnjenje": "Odgovor prati glagol u pitanju." },
    { "id": 19, "semester": 1, "pitanje": "My ___ is red. (Small carry bag)", "opcije": ["Desk", "Chair", "Pencil case", "Backpack"], "tocan_odgovor": 3, "obasnjenje": "Backpack je ruksak." },
    { "id": 20, "semester": 1, "pitanje": "You use your ___ to listen.", "opcije": ["Eyes", "Nose", "Mouth", "Ears"], "tocan_odgovor": 3, "obasnjenje": "Ears su uši." },
    { "id": 21, "semester": 1, "pitanje": "Which of these is a school subject?", "opcije": ["Pizza", "Maths", "Football", "Summer"], "tocan_odgovor": 1, "obasnjenje": "Maths je matematika." },
    { "id": 22, "semester": 1, "pitanje": "How do you say 'Sestra'?", "opcije": ["Mother", "Sister", "Brother", "Grandma"], "tocan_odgovor": 1, "obasnjenje": "Sister je sestra." },
    { "id": 23, "semester": 1, "pitanje": "It is ___ (12:00).", "opcije": ["Midday", "Midnight", "Morning", "Evening"], "tocan_odgovor": 0, "obasnjenje": "Midday je podne." },
    { "id": 24, "semester": 1, "pitanje": "Choose the correct: She ___ 10 years old.", "opcije": ["am", "is", "are", "has"], "tocan_odgovor": 1, "obasnjenje": "Godine izražavamo s 'to be'." },
    { "id": 25, "semester": 1, "pitanje": "Opposite of 'Happy' is...", "opcije": ["New", "Small", "Sad", "Fast"], "tocan_odgovor": 2, "obasnjenje": "Sad je tužan." },
    { "id": 26, "semester": 2, "pitanje": "What do you eat for breakfast?", "opcije": ["Dinner", "Cereal", "Pizza", "Soup"], "tocan_odgovor": 1, "obasnjenje": "Cereal su žitarice." },
    { "id": 27, "semester": 2, "pitanje": "She ___ her homework every day.", "opcije": ["do", "does", "doing", "did"], "tocan_odgovor": 1, "obasnjenje": "She/He/It dobiva nastavak -s/-es." },
    { "id": 28, "semester": 2, "pitanje": "Where do you play football?", "opcije": ["Kitchen", "Field", "Bed", "Fridge"], "tocan_odgovor": 1, "obasnjenje": "Football se igra na igralištu (field)." },
    { "id": 29, "semester": 2, "pitanje": "Which month is in summer?", "opcije": ["January", "July", "October", "December"], "tocan_odgovor": 1, "obasnjenje": "July je srpanj." },
    { "id": 30, "semester": 2, "pitanje": "What is the opposite of 'Big'?", "opcije": ["Small", "Long", "Tall", "Short"], "tocan_odgovor": 0, "obasnjenje": "Small je mali." },
    { "id": 31, "semester": 2, "pitanje": "Can you ___ a bicycle?", "opcije": ["drive", "ride", "fly", "swim"], "tocan_odgovor": 1, "obasnjenje": "Ride a bike je voziti bicikl." },
    { "id": 32, "semester": 2, "pitanje": "I ___ watching TV now.", "opcije": ["is", "am", "are", "be"], "tocan_odgovor": 1, "obasnjenje": "Present Continuous: am + -ing." },
    { "id": 33, "semester": 2, "pitanje": "An elephant is ___.", "opcije": ["small", "tiny", "huge", "thin"], "tocan_odgovor": 2, "obasnjenje": "Huge znači ogroman." },
    { "id": 34, "semester": 2, "pitanje": "Translate: 'Jabuka je na stolu.'", "opcije": ["under", "in", "on", "at"], "tocan_odgovor": 2, "obasnjenje": "On je na." },
    { "id": 35, "semester": 2, "pitanje": "What do you call a baby cat?", "opcije": ["Puppy", "Chick", "Kitten", "Calf"], "tocan_odgovor": 2, "obasnjenje": "Kitten je mačić." },
    { "id": 36, "semester": 2, "pitanje": "Do you like apples? No, I ___.", "opcije": ["doesn't", "don't", "am not", "not"], "tocan_odgovor": 1, "obasnjenje": "Negacija u Present Simple je don't." },
    { "id": 37, "semester": 2, "pitanje": "Where does a doctor work?", "opcije": ["School", "Hospital", "Farm", "Park"], "tocan_odgovor": 1, "obasnjenje": "Hospital je bolnica." },
    { "id": 38, "semester": 2, "pitanje": "We ___ to school by bus.", "opcije": ["goes", "go", "going", "gone"], "tocan_odgovor": 1, "obasnjenje": "Uz 'We' ide osnovni oblik glagola." },
    { "id": 39, "semester": 2, "pitanje": "Which fruit is orange?", "opcije": ["Apple", "Orange", "Pear", "Plum"], "tocan_odgovor": 1, "obasnjenje": "Orange je i boja i voće (naranča)." },
    { "id": 40, "semester": 2, "pitanje": "It's ___ (padne kiša).", "opcije": ["snowing", "raining", "sunny", "windy"], "tocan_odgovor": 1, "obasnjenje": "Raining je padanje kiše." },
    { "id": 41, "semester": 2, "pitanje": "I have ___ in my soup.", "opcije": ["sugar", "salt", "chocolate", "ice"], "tocan_odgovor": 1, "obasnjenje": "Salt je sol." },
    { "id": 42, "semester": 2, "pitanje": "What is the capital of Croatia?", "opcije": ["Split", "Rijeka", "Osijek", "Zagreb"], "tocan_odgovor": 3, "obasnjenje": "Zagreb je glavni grad." },
    { "id": 43, "semester": 2, "pitanje": "Can I ___ your pen?", "opcije": ["borrow", "fly", "eat", "sleep"], "tocan_odgovor": 0, "obasnjenje": "Borrow znači posuditi." },
    { "id": 44, "semester": 2, "pitanje": "Where do sharks live?", "opcije": ["Forest", "Desert", "Ocean", "Sky"], "tocan_odgovor": 2, "obasnjenje": "Ocean je dom morskim psima." },
    { "id": 45, "semester": 2, "pitanje": "Who flies an airplane?", "opcije": ["Driver", "Pilot", "Captain", "Teacher"], "tocan_odgovor": 1, "obasnjenje": "Pilot upravlja avionom." },
    { "id": 46, "semester": 2, "pitanje": "How do you say 'Sladoled'?", "opcije": ["Ice cream", "Hot dog", "Hamburger", "Cake"], "tocan_odgovor": 0, "obasnjenje": "Ice cream je sladoled." },
    { "id": 47, "semester": 2, "pitanje": "Which one is a vegetable?", "opcije": ["Apple", "Carrot", "Banana", "Cherry"], "tocan_odgovor": 1, "obasnjenje": "Carrot je mrkva." },
    { "id": 48, "semester": 2, "pitanje": "Are they playing? Yes, they ___.", "opcije": ["is", "am", "are", "do"], "tocan_odgovor": 2, "obasnjenje": "Odgovor prati oblik glagola iz pitanja." },
    { "id": 49, "semester": 2, "pitanje": "What do you wear when it's cold?", "opcije": ["T-shirt", "Shorts", "Jacket", "Sunglasses"], "tocan_odgovor": 2, "obasnjenje": "Jacket je jakna." },
    { "id": 50, "semester": 2, "pitanje": "How do you say 'Doviđenja'?", "opcije": ["Hello", "Welcome", "Goodbye", "Please"], "tocan_odgovor": 2, "obasnjenje": "Goodbye je doviđenja." }
];
