const GER_7_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Ich _______ nach Berlin. (putujem)", "opcije": ["schlafe", "trinke", "esse", "reise"], "tocan_odgovor": 3, "obasnjenje": "Reisen - putovati." },
    { "id": 2, "semester": 1, "pitanje": "Ich bin nach Berlin _______. (putovao)", "opcije": ["gereis", "reisen", "gereisen", "gereist"], "tocan_odgovor": 3, "obasnjenje": "Perfekt glagola reisen." },
    { "id": 3, "semester": 1, "pitanje": "Gestern _______ ich im Kino.", "opcije": ["habe", "bin", "war", "hatte"], "tocan_odgovor": 2, "obasnjenje": "Präteritum glagola 'sein'." },
    { "id": 4, "semester": 1, "pitanje": "Die _______ su ljeti. (praznici)", "opcije": ["Schule", "Ferien", "Übung", "Arbeit"], "tocan_odgovor": 1, "obasnjenje": "Ferien - ljetni praznici." },
    { "id": 5, "semester": 1, "pitanje": "Er hat _______. (zadaću / m.r.)", "opcije": ["einen Job", "eine Übung", "ein Buch", "seine Hausaufgabe"], "tocan_odgovor": 3, "obasnjenje": "Hausaufgabe (ž.r.)." },
    { "id": 6, "semester": 1, "pitanje": "Wir _______ ein neues Haus. (imamo)", "opcije": ["ist", "sind", "bist", "haben"], "tocan_odgovor": 3, "obasnjenje": "Glagol haben (1. lice množine)." },
    { "id": 7, "semester": 1, "pitanje": "Ich _______ heute lernen. (moram)", "opcije": ["kann", "muss", "will", "darf"], "tocan_odgovor": 1, "obasnjenje": "Müssen - morati." },
    { "id": 8, "semester": 1, "pitanje": "Mathe je moj _______ . (predmet)", "opcije": ["Schulfach", "Lehrer", "Pause", "Schulbuch"], "tocan_odgovor": 0, "obasnjenje": "Schulfach - školski predmet." },
    { "id": 9, "semester": 1, "pitanje": "Er _______ heute nicht kommen. (može)", "opcije": ["kannst", "könnt", "können", "kann"], "tocan_odgovor": 3, "obasnjenje": "Können (moći) - 3. lice jednine." },
    { "id": 10, "semester": 1, "pitanje": "Ich _______ schlafen. (želim)", "opcije": ["kann", "muss", "will", "darf"], "tocan_odgovor": 2, "obasnjenje": "Wollen - htjeti/željeti." },
    { "id": 11, "semester": 1, "pitanje": "Prošlo vrijeme: Präteritum ili _______ ?", "opcije": ["Perfekt", "Futur", "Präsens", "Genitiv"], "tocan_odgovor": 0, "obasnjenje": "Ključna prošla vremena." },
    { "id": 12, "semester": 1, "pitanje": "Ich habe das Buch _______. (pročitao)", "opcije": ["gelest", "gelesen", "las", "lesen"], "tocan_odgovor": 1, "obasnjenje": "Particip II glagola lesen." },
    { "id": 13, "semester": 1, "pitanje": "Der _______ je u prtljažniku. (kofer)", "opcije": ["Zug", "Koffer", "Tasche", "Flugzeug"], "tocan_odgovor": 1, "obasnjenje": "Der Koffer - kofer." },
    { "id": 14, "semester": 1, "pitanje": "Das _______ fliegt schnell. (avion)", "opcije": ["Auto", "Zug", "Flugzeug", "Schiff"], "tocan_odgovor": 2, "obasnjenje": "Das Flugzeug - avion." },
    { "id": 15, "semester": 1, "pitanje": "Du _______ fleißig lernen. (moraš)", "opcije": ["müsst", "müssen", "musst", "muss"], "tocan_odgovor": 2, "obasnjenje": "Müssen - 2. lice jednine." },
    { "id": 16, "semester": 1, "pitanje": "Ich _______ in Deutschland. (bio sam)", "opcije": ["hatte", "ist", "hat", "war"], "tocan_odgovor": 3, "obasnjenje": "War - bio sam." },
    { "id": 17, "semester": 1, "pitanje": "Ich _______ keine Zeit. (imao sam)", "opcije": ["hatte", "bin", "war", "habe"], "tocan_odgovor": 0, "obasnjenje": "Hatte - präteritum od haben." },
    { "id": 18, "semester": 1, "pitanje": "Der Film war _______ . (zabavan)", "opcije": ["lustig", "langweilig", "schwer", "traurig"], "tocan_odgovor": 0, "obasnjenje": "Lustig - zabavan." },
    { "id": 19, "semester": 1, "pitanje": "Deutsch je _______ . (zanimljiv)", "opcije": ["langweilig", "dumm", "interessant", "schwer"], "tocan_odgovor": 2, "obasnjenje": "Interessant - zanimljivo." },
    { "id": 20, "semester": 1, "pitanje": "Hier _______ man nie parken.", "opcije": ["darfst", "dürfen", "dürft", "darf"], "tocan_odgovor": 3, "obasnjenje": "Dürfen (smjeti) 3. lice jednine." },
    { "id": 21, "semester": 1, "pitanje": "Ich _______ meine Oma. (posjećujem)", "opcije": ["esse", "suche", "finde", "besuche"], "tocan_odgovor": 3, "obasnjenje": "Besuchen - posjetiti." },
    { "id": 22, "semester": 1, "pitanje": "Der _______ fährt nach München. (vlak)", "opcije": ["Rad", "Schiff", "Zug", "Bus"], "tocan_odgovor": 2, "obasnjenje": "Der Zug - vlak." },
    { "id": 23, "semester": 1, "pitanje": "Sie _______ Schokolade essen. (bi željela)", "opcije": ["möchte", "möchten", "möchtest", "möchtet"], "tocan_odgovor": 0, "obasnjenje": "Möchte - željeti (konjunktiv)." },
    { "id": 24, "semester": 1, "pitanje": "Die _______ kostet 10 Euro. (ulaznica)", "opcije": ["Eintrittskarte", "Karte", "Brief", "Post"], "tocan_odgovor": 0, "obasnjenje": "Eintrittskarte - ulaznica." },
    { "id": 25, "semester": 1, "pitanje": "Das _______ ist blau. (more)", "opcije": ["Fluss", "See", "Berg", "Meer"], "tocan_odgovor": 3, "obasnjenje": "Das Meer - more." },
    { "id": 26, "semester": 1, "pitanje": "Wir _______ in den Alpen. (pješačimo)", "opcije": ["laufen", "essen", "schwimmen", "wandern"], "tocan_odgovor": 3, "obasnjenje": "Wandern - planinariti." },
    { "id": 27, "semester": 1, "pitanje": "Wir _______ nach Berlin geflogen.", "opcije": ["war", "haben", "hatte", "sind"], "tocan_odgovor": 3, "obasnjenje": "Fliegen koristi 'sein'." },
    { "id": 28, "semester": 1, "pitanje": "_______ kommst du? (Kada)", "opcije": ["Wann", "Wer", "Was", "Wo"], "tocan_odgovor": 0, "obasnjenje": "Wann - kada?" },
    { "id": 29, "semester": 1, "pitanje": "Mein _______ ist cool. (prijatelj)", "opcije": ["Vater", "Freund", "Lehrer", "Feind"], "tocan_odgovor": 1, "obasnjenje": "Der Freund - prijatelj." },
    { "id": 30, "semester": 1, "pitanje": "Ich bin _______ Hause. (kod kuće)", "opcije": ["an", "in", "zu", "nach"], "tocan_odgovor": 2, "obasnjenje": "Zu Hause - stanje (kod kuće)." },
    { "id": 31, "semester": 1, "pitanje": "Ich gehe _______ Hause. (kući)", "opcije": ["zu", "in", "nach", "an"], "tocan_odgovor": 2, "obasnjenje": "Nach Hause - smjer (kući)." },
    { "id": 32, "semester": 1, "pitanje": "Viele _______ (pozdravi) iz Njemačke!", "opcije": ["Brille", "Grüße", "Küsse", "Träume"], "tocan_odgovor": 1, "obasnjenje": "Grüße - pozdravi." },
    { "id": 33, "semester": 1, "pitanje": "Das ist eine _______ ! (iznenađenje)", "opcije": ["Frühstück", "Abendessen", "Überraschung", "Geschenk"], "tocan_odgovor": 2, "obasnjenje": "Überraschung - iznenađenje." },
    { "id": 34, "semester": 1, "pitanje": "Er _______ yesterday krank. (bio je)", "opcije": ["ist", "hat", "hatte", "war"], "tocan_odgovor": 3, "obasnjenje": "War - präteritum od ist." },
    { "id": 35, "semester": 1, "pitanje": "Er ist _______ . (bolestan)", "opcije": ["krank", "froh", "müde", "gesund"], "tocan_odgovor": 0, "obasnjenje": "Krank - bolestan." },
    { "id": 36, "semester": 1, "pitanje": "Er wird _______ . (ozdraviti)", "opcije": ["rot", "krank", "schwach", "gesund"], "tocan_odgovor": 3, "obasnjenje": "Gesund - zdrav." },
    { "id": 37, "semester": 1, "pitanje": "Der _______ hilft mir. (liječnik)", "opcije": ["Fahrer", "Koch", "Lehrer", "Arzt"], "tocan_odgovor": 3, "obasnjenje": "Der Arzt - liječnik." },
    { "id": 38, "semester": 1, "pitanje": "Mein Kopf _______ weh. (boli)", "opcije": ["macht", "ist", "hat", "tut"], "tocan_odgovor": 3, "obasnjenje": "Tut weh - boli." },
    { "id": 39, "semester": 1, "pitanje": "Ich habe _______ . (glavobolju)", "opcije": ["Zahnschmerzen", "Kopfschmerzen", "Beinschmerzen", "Bauchschmerzen"], "tocan_odgovor": 1, "obasnjenje": "Kopfschmerzen - bol u glavi." },
    { "id": 40, "semester": 1, "pitanje": "Mein _______ tut weh. (trbuh)", "opcije": ["Bauch", "Bein", "Kopf", "Arm"], "tocan_odgovor": 0, "obasnjenje": "Der Bauch - trbuh." },
    { "id": 41, "semester": 1, "pitanje": "Ich _______ die Tabletten. (uzimam)", "opcije": ["sehe", "nehme", "höre", "gebe"], "tocan_odgovor": 1, "obasnjenje": "Nehmen - uzeti." },
    { "id": 42, "semester": 1, "pitanje": "Er _______ Medikamente nehmen.", "opcije": ["darf", "will", "muss", "kann"], "tocan_odgovor": 2, "obasnjenje": "Muss - obveza." },
    { "id": 43, "semester": 1, "pitanje": "In der _______ kaufe ich Aspirin.", "opcije": ["Laden", "Bibliothek", "Schule", "Apotheke"], "tocan_odgovor": 3, "obasnjenje": "Die Apotheke - ljekarna." },
    { "id": 44, "semester": 1, "pitanje": "Ich trinke _______ . (čaj)", "opcije": ["Wasser", "Kaffee", "Milch", "Tee"], "tocan_odgovor": 3, "obasnjenje": "Der Tee - čaj." },
    { "id": 45, "semester": 1, "pitanje": "Du _______ im Bett blijven. (trebaš)", "opcije": ["sollt", "sollst", "sollen", "soll"], "tocan_odgovor": 1, "obasnjenje": "Sollen - savjet." },
    { "id": 46, "semester": 1, "pitanje": "Ich _______ im Bett. (ostajem)", "opcije": ["laufe", "gehe", "bleibe", "komme"], "tocan_odgovor": 2, "obasnjenje": "Bleiben - ostati." },
    { "id": 47, "semester": 1, "pitanje": "Wie ist das _______ ? (vrijeme)", "opcije": ["Tag", "Zeit", "Uhr", "Wetter"], "tocan_odgovor": 3, "obasnjenje": "Das Wetter - vrijeme." },
    { "id": 48, "semester": 1, "pitanje": "Es _______ oggi. (pada kiša)", "opcije": ["regnet", "scheint", "weht", "schneit"], "tocan_odgovor": 0, "obasnjenje": "Regnen - padati (kiša)." },
    { "id": 49, "semester": 1, "pitanje": "Es ist _______ . (vruće)", "opcije": ["bewölkt", "windig", "heiß", "kalt"], "tocan_odgovor": 2, "obasnjenje": "Heiß - vruće." },
    { "id": 50, "semester": 1, "pitanje": "Die Sonne _______ . (sija)", "opcije": ["scheint", "weht", "schneit", "regnet"], "tocan_odgovor": 0, "obasnjenje": "Scheinen - sijati." },
    { "id": 51, "semester": 2, "pitanje": "Ich _______ gerne fern. (gledam TV)", "opcije": ["höre", "sehe", "gehe", "mache"], "tocan_odgovor": 1, "obasnjenje": "Fernsehen - gledati TV." },
    { "id": 52, "semester": 2, "pitanje": "Am Abend sehe ich _______.", "opcije": ["zu", "fern", "mit", "an"], "tocan_odgovor": 1, "obasnjenje": "Djeljivi glagol (Ich sehe fern)." },
    { "id": 53, "semester": 2, "pitanje": "Mein _______ ist neu. (handy)", "opcije": ["Computer", "Handy", "Radio", "Tablet"], "tocan_odgovor": 1, "obasnjenje": "Das Handy - mobitel." },
    { "id": 54, "semester": 2, "pitanje": "Ich _______ eine SMS. (šaljem)", "opcije": ["schicke", "lese", "höre", "schlafe"], "tocan_odgovor": 0, "obasnjenje": "Schicken - poslati." },
    { "id": 55, "semester": 2, "pitanje": "Er _______ das Internet. (koristi)", "opcije": ["trinkt", "isst", "liest", "benutzt"], "tocan_odgovor": 3, "obasnjenje": "Benutzen - koristiti." },
    { "id": 56, "semester": 2, "pitanje": "Das _______ ist global. (internet)", "opcije": ["Fernsehen", "Zeitung", "Magazin", "Internet"], "tocan_odgovor": 3, "obasnjenje": "Das Internet - internet." },
    { "id": 57, "semester": 2, "pitanje": "Der _______ ist gruselig. (horor film)", "opcije": ["Krimi", "Cartoon", "Komödie", "Horrorfilm"], "tocan_odgovor": 3, "obasnjenje": "Horrorfilm - film strave." },
    { "id": 58, "semester": 2, "pitanje": "Die _______ ist lustig. (komedija)", "opcije": ["Tragödie", "Dokumentation", "Komödie", "Drama"], "tocan_odgovor": 2, "obasnjenje": "Komödie - komedija." },
    { "id": 59, "semester": 2, "pitanje": "Wir haben den film _______ .", "opcije": ["sah", "gesehen", "sieht", "sehen"], "tocan_odgovor": 1, "obasnjenje": "Particip II od sehen je gesehen." },
    { "id": 60, "semester": 2, "pitanje": "Der Film war _______ . (dosadan)", "opcije": ["lustig", "langweilig", "prima", "neu"], "tocan_odgovor": 1, "obasnjenje": "Langweilig - dosadno." },
    { "id": 61, "semester": 2, "pitanje": "Ich gehe _______ . (kupovati)", "opcije": ["tražiti", "prodati", "naći", "einkaufen"], "tocan_odgovor": 3, "obasnjenje": "Einkaufen - kupovati." },
    { "id": 62, "semester": 2, "pitanje": "Ich gehe in _______ Supermarkt.", "opcije": ["den", "das", "dem", "die"], "tocan_odgovor": 0, "obasnjenje": "Akkusativ muškog roda." },
    { "id": 63, "semester": 2, "pitanje": "Das _______ ist groß. (robna kuća)", "opcije": ["Park", "Kaufhaus", "Schule", "Krankenhaus"], "tocan_odgovor": 1, "obasnjenje": "Das Kaufhaus - robna kuća." },
    { "id": 64, "semester": 2, "pitanje": "Das T-Shirt ist _______ . (jeftino)", "opcije": ["schön", "teuer", "neu", "billig"], "tocan_odgovor": 3, "obasnjenje": "Billig - jeftino." },
    { "id": 65, "semester": 2, "pitanje": "Die Brille ist _______ . (skupa)", "opcije": ["teuer", "groß", "klein", "billig"], "tocan_odgovor": 0, "obasnjenje": "Teuer - skupo." },
    { "id": 66, "semester": 2, "pitanje": "Das ist _______ schön. (jako)", "opcije": ["nikad", "sehr", "ne", "možda"], "tocan_odgovor": 1, "obasnjenje": "Sehr - jako." },
    { "id": 67, "semester": 2, "pitanje": "_______ du dich s prijateljima?", "opcije": ["Triffst", "Isst", "Machst", "Siehst"], "tocan_odgovor": 0, "obasnjenje": "Sich treffen (du triffst)." },
    { "id": 68, "semester": 2, "pitanje": "Wir lernen _______ . (zajedno)", "opcije": ["rijetko", "često", "zusammen", "sam"], "tocan_odgovor": 2, "obasnjenje": "Zusammen - zajedno." },
    { "id": 69, "semester": 2, "pitanje": "Ich habe die Hausaufgabe _______ .", "opcije": ["gemacht", "macht", "machen", "gemachen"], "tocan_odgovor": 0, "obasnjenje": "Particip II od machen." },
    { "id": 70, "semester": 2, "pitanje": "Berlin ist eine _______ . (grad)", "opcije": ["Küste", "Stadt", "Berg", "Dorf"], "tocan_odgovor": 1, "obasnjenje": "Die Stadt - grad." },
    { "id": 71, "semester": 2, "pitanje": "_______ ist die Hauptstadt. (Berlin)", "opcije": ["München", "Berlin", "Wien", "Hamburg"], "tocan_odgovor": 1, "obasnjenje": "Berlin je glavni grad." },
    { "id": 72, "semester": 2, "pitanje": "In Österreich spricht man _______ .", "opcije": ["Deutsch", "Englisch", "Französisch", "Spanisch"], "tocan_odgovor": 0, "obasnjenje": "Glavni jezik u Austriji." },
    { "id": 73, "semester": 2, "pitanje": "Das _______ je u centru. (vijećnica)", "opcije": ["Schule", "Rathaus", "Kirche", "Museum"], "tocan_odgovor": 1, "obasnjenje": "Rathaus - gradska vijećnica." },
    { "id": 74, "semester": 2, "pitanje": "Der _______ ist groß. (trg)", "opcije": ["Straße", "Park", "Fluss", "Platz"], "tocan_odgovor": 3, "obasnjenje": "Der Platz - trg." },
    { "id": 75, "semester": 2, "pitanje": "Wo _______ die Post? (je)", "opcije": ["haben", "hat", "ist", "bin"], "tocan_odgovor": 2, "obasnjenje": "Pitanje (gdje se nalazi)." },
    { "id": 76, "semester": 2, "pitanje": "Gehen Sie _______ . (lijevo)", "opcije": ["links", "oben", "rechts", "geradeaus"], "tocan_odgovor": 0, "obasnjenje": "Links - lijevo." },
    { "id": 77, "semester": 2, "pitanje": "Gehen Sie _______ . (desno)", "opcije": ["unten", "rechts", "zurück", "links"], "tocan_odgovor": 1, "obasnjenje": "Rechts - desno." },
    { "id": 78, "semester": 2, "pitanje": "Gehen Sie _______ . (ravno)", "opcije": ["visoko", "duboko", "geradeaus", "daleko"], "tocan_odgovor": 2, "obasnjenje": "Geradeaus - ravno." },
    { "id": 79, "semester": 2, "pitanje": "Nehmen Sie _______ Bus.", "opcije": ["das", "die", "den", "dem"], "tocan_odgovor": 2, "obasnjenje": "Akkusativ muškog roda." },
    { "id": 80, "semester": 2, "pitanje": "Die _______ ist tamo. (stajalište)", "opcije": ["Haltestelle", "Haus", "Brücke", "Schule"], "tocan_odgovor": 0, "obasnjenje": "Haltestelle - stajalište busa." },
    { "id": 81, "semester": 2, "pitanje": "Ich gehe _______ . (pješke)", "opcije": ["vlakom", "autom", "busom", "zu Fuß"], "tocan_odgovor": 3, "obasnjenje": "Zu Fuß - pješke." },
    { "id": 82, "semester": 2, "pitanje": "Das _______ ist gesund.", "opcije": ["Schiff", "Auto", "Fahrrad", "Motorrad"], "tocan_odgovor": 2, "obasnjenje": "Bicikliranje (gradske teme)." },
    { "id": 83, "semester": 2, "pitanje": "Der Vater _______ Auto. (vozi)", "opcije": ["ide", "fährt", "trči", "vidi"], "tocan_odgovor": 1, "obasnjenje": "Fahren - ići vozilom." },
    { "id": 84, "semester": 2, "pitanje": "Kannst du mir _______ ? (pomoći)", "opcije": ["geben", "machen", "helfen", "hören"], "tocan_odgovor": 2, "obasnjenje": "Helfen - pomoći." },
    { "id": 85, "semester": 2, "pitanje": "Ich habe eine _______ . (pitanje)", "opcije": ["Frage", "Antwort", "Wort", "Satz"], "tocan_odgovor": 0, "obasnjenje": "Die Frage - pitanje." },
    { "id": 86, "semester": 2, "pitanje": "Das ist die _______ . (odgovor)", "opcije": ["Nummer", "Antwort", "Frage", "Buchstab"], "tocan_odgovor": 1, "obasnjenje": "Die Antwort - odgovor." },
    { "id": 87, "semester": 2, "pitanje": "Er _______ gut Deutsch. (priča)", "opcije": ["spreche", "spricht", "sprecht", "sprechen"], "tocan_odgovor": 1, "obasnjenje": "Sprechen (pričati) - 3. lice jednine." },
    { "id": 88, "semester": 2, "pitanje": "Ich _______ dich. (razumijem)", "opcije": ["sehe", "vergesse", "verstehe", "höre"], "tocan_odgovor": 2, "obasnjenje": "Verstehen - razumjeti." },
    { "id": 89, "semester": 2, "pitanje": "Das je jedna _______ . (vježba)", "opcije": ["Buch", "Übung", "Papier", "Stift"], "tocan_odgovor": 1, "obasnjenje": "Die Übung - vježba." },
    { "id": 90, "semester": 2, "pitanje": "Ich _______ ein Eis. (želio bih)", "opcije": ["imam", "sam", "möchte", "bio"], "tocan_odgovor": 2, "obasnjenje": "Möchte - željeti." },
    { "id": 91, "semester": 2, "pitanje": "Das _______ schmeckt gut.", "opcije": ["Schnee", "Regen", "Wasser", "Eis"], "tocan_odgovor": 3, "obasnjenje": "Das Eis - sladoled." },
    { "id": 92, "semester": 2, "pitanje": "Was je tvoj _______ ? (omiljeni predmet)", "opcije": ["Lieblingsfach", "Freund", "Essen", "Farbe"], "tocan_odgovor": 0, "obasnjenje": "Lieblingsfach - omiljeni predmet." },
    { "id": 93, "semester": 2, "pitanje": "Ich habe jedna Eins (1). (ocjena)", "opcije": ["Buch", "Note", "Klasse", "Schüler"], "tocan_odgovor": 1, "obasnjenje": "Die Note - ocjena." },
    { "id": 94, "semester": 2, "pitanje": "Ich _______ 13 Jahre alt.", "opcije": ["imam", "bin", "imamo", "je"], "tocan_odgovor": 1, "obasnjenje": "Za godine koristimo bin (sein)." },
    { "id": 95, "semester": 2, "pitanje": "Hast du _______ ? (braću i sestre)", "opcije": ["Eltern", "Großeltern", "Geschwister", "Freunde"], "tocan_odgovor": 2, "obasnjenje": "Geschwister - braća i sestre." },
    { "id": 96, "semester": 2, "pitanje": "Mein _______ je mlađi. (brat)", "opcije": ["Onkel", "Bruder", "Tante", "Schwester"], "tocan_odgovor": 1, "obasnjenje": "Der Bruder - brat." },
    { "id": 97, "semester": 2, "pitanje": "Meine _______ je starija. (sestra)", "opcije": ["Bruder", "Tata", "Schwester", "Mama"], "tocan_odgovor": 2, "obasnjenje": "Die Schwester - sestra." },
    { "id": 98, "semester": 2, "pitanje": "Meine Mutter _______ Ärztin. (je)", "opcije": ["ist", "ima", "sam", "postat će"], "tocan_odgovor": 0, "obasnjenje": "Ist - je." },
    { "id": 99, "semester": 2, "pitanje": "Ich _______ mich! (radujem se)", "opcije": ["habe", "freue", "bin", "sehe"], "tocan_odgovor": 1, "obasnjenje": "Sich freuen - radovati se." },
    { "id": 100, "semester": 2, "pitanje": "SharkLearn macht _______ !", "opcije": ["Pause", "Spaß", "Angst", "Hausaufgabe"], "tocan_odgovor": 1, "obasnjenje": "Spaß machen - biti zabavno." }
];
