const GER_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Ich _______ Marko.", "opcije": ["bist", "ist", "bin", "sind"], "tocan_odgovor": 2, "obasnjenje": "Za prvo lice jednine glagol 'sein' glasi 'bin'." },
    { "id": 2, "semester": 1, "pitanje": "Du _______ lerne Deutsch.", "opcije": ["bin", "bist", "ist", "sind"], "tocan_odgovor": 1, "obasnjenje": "Za drugo lice jednine glagol 'sein' glasi 'bist'." },
    { "id": 3, "semester": 1, "pitanje": "Wir _______ ein Haus.", "opcije": ["haben", "hast", "hat", "habt"], "tocan_odgovor": 0, "obasnjenje": "'Wir' (mi) koristi osnovni oblik glagola 'haben'." },
    { "id": 4, "semester": 1, "pitanje": "Das ist _______ Tisch.", "opcije": ["der", "die", "das", "den"], "tocan_odgovor": 0, "obasnjenje": "Stol je muškog roda u nominativu (Der Tisch)." },
    { "id": 5, "semester": 1, "pitanje": "Ich habe _______ Bruder.", "opcije": ["ein", "eine", "einen", "eines"], "tocan_odgovor": 2, "obasnjenje": "'Bruder' je muškog roda, a glagol 'haben' traži Akkusativ (Einen)." },
    { "id": 6, "semester": 1, "pitanje": "Er _______ Fußball.", "opcije": ["spiele", "spielst", "spielt", "spielen"], "tocan_odgovor": 2, "obasnjenje": "Za Er/Sie/It dodajemo nastavak -t na korijen glagola." },
    { "id": 7, "semester": 1, "pitanje": "Wir _______ nach Hause.", "opcije": ["gehe", "gehst", "geht", "gehen"], "tocan_odgovor": 3, "obasnjenje": "Za 'Wir' i 'sie/Sie' koristimo infinitivni oblik (-en)." },
    { "id": 8, "semester": 1, "pitanje": "Wie _______ du?", "opcije": ["heiße", "heißt", "heißen", "heißt"], "tocan_odgovor": 1, "obasnjenje": "Za 'du' dodajemo nastavak -st (ovdje samo -t zbog korijena na -ß)." },
    { "id": 9, "semester": 1, "pitanje": "Das ist _______ Tasche.", "opcije": ["der", "die", "das", "den"], "tocan_odgovor": 1, "obasnjenje": "Torba je ženskog roda (Die Tasche)." },
    { "id": 10, "semester": 1, "pitanje": "Sie _______ (ona) ist 10 Jahre alt.", "opcije": ["bin", "bist", "ist", "sind"], "tocan_odgovor": 2, "obasnjenje": "Za treće lice jednine glasi 'ist'." },
    { "id": 11, "semester": 1, "pitanje": "Ihr _______ fleißig.", "opcije": ["bin", "bist", "ist", "seid"], "tocan_odgovor": 3, "obasnjenje": "Za 'Ihr' (vi) glagol 'sein' glasi 'seid'." },
    { "id": 12, "semester": 1, "pitanje": "Das ist _______ Buch.", "opcije": ["der", "die", "das", "den"], "tocan_odgovor": 2, "obasnjenje": "Knjiga je srednjeg roda (Das Buch)." },
    { "id": 13, "semester": 1, "pitanje": "Habt _______ ein Hobby?", "opcije": ["du", "ihr", "wir", "sie"], "tocan_odgovor": 1, "obasnjenje": "Nastavak -t na glagolu 'habt' sugerira zamjenicu 'ihr'." },
    { "id": 14, "semester": 1, "pitanje": "Ich ________ (pijem) Cola.", "opcije": ["trinkst", "trinkt", "trinke", "trinken"], "tocan_odgovor": 2, "obasnjenje": "Za 'Ich' dodajemo nastavak -e na korijen." },
    { "id": 15, "semester": 1, "pitanje": "Koja je zamjenica za 'Moj otac'?", "opcije": ["Ich", "Du", "Er", "Sie"], "tocan_odgovor": 2, "obasnjenje": "Moj otac je muškog roda, dakle Er (On)." },
    { "id": 16, "semester": 1, "pitanje": "Das ist _______ Apfel.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 0, "obasnjenje": "U nominativu za muški rod neodređeni član je 'ein'." },
    { "id": 17, "semester": 1, "pitanje": "Wo _______ du?", "opcije": ["wohne", "wohnst", "wohnt", "wohnen"], "tocan_odgovor": 1, "obasnjenje": "Za 'du' je nastavak -st." },
    { "id": 18, "semester": 1, "pitanje": "Wir _______ (učimo) Deutsch.", "opcije": ["lerne", "lernst", "lernt", "lernen"], "tocan_odgovor": 3, "obasnjenje": "Nastavak -en za zamjenicu 'Wir'." },
    { "id": 19, "semester": 1, "pitanje": "Koja je zamjenica za 'Moja majka'?", "opcije": ["Er", "Sie", "Es", "Wir"], "tocan_odgovor": 1, "obasnjenje": "Moja majka je ženskog roda, dakle Sie (Ona)." },
    { "id": 20, "semester": 1, "pitanje": "Sie _______ kommen aus Split. (oni)", "opcije": ["kommst", "kommt", "komme", "kommen"], "tocan_odgovor": 3, "obasnjenje": "Za 'sie' (oni) glagol ima uobičajeni -en kraj." },
    { "id": 21, "semester": 1, "pitanje": "_______ ist das? Das ist Petra.", "opcije": ["Wer", "Was", "Wo", "Wie"], "tocan_odgovor": 0, "obasnjenje": "'Wer' koristimo kad pitamo za osobe." },
    { "id": 22, "semester": 1, "pitanje": "Neodređeni član za 'die Schule' je...", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 1, "obasnjenje": "Za ženski rod neodređeni član je 'eine'." },
    { "id": 23, "semester": 1, "pitanje": "Das Kind _______ (spava).", "opcije": ["schlafe", "schläfst", "schläft", "schlafen"], "tocan_odgovor": 2, "obasnjenje": "Treće lice jednine (Kind = Es) često ima prijeglas na 'a'." },
    { "id": 24, "semester": 1, "pitanje": "Was _______ du gerne?", "opcije": ["isst", "esse", "essen", "esst"], "tocan_odgovor": 0, "obasnjenje": "Glagol 'essen' je nepravilan (du isst)." },
    { "id": 25, "semester": 1, "pitanje": "Ich _______ (imam) keine Zeit.", "opcije": ["habe", "hast", "hat", "haben"], "tocan_odgovor": 0, "obasnjenje": "Za 'Ich' je oblik 'habe'." },
    { "id": 26, "semester": 2, "pitanje": "Ich suche _______ Ball.", "opcije": ["der", "die", "das", "den"], "tocan_odgovor": 3, "obasnjenje": "U Akkusativu muški rod 'der' prelazi u 'den'." },
    { "id": 27, "semester": 2, "pitanje": "Du siehst _______ Film.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 2, "obasnjenje": "U Akkusativu muški rod 'ein' postaje 'einen'." },
    { "id": 28, "semester": 2, "pitanje": "Er kauft _______ Buch.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 0, "obasnjenje": "Srednji rod u Akkusativu ostaje isti (ein)." },
    { "id": 29, "semester": 2, "pitanje": "Wir besuchen _______ Oma.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 1, "obasnjenje": "Ženski rod u Akkusativu ostaje isti (eine)." },
    { "id": 30, "semester": 2, "pitanje": "_______ du Pizza?", "opcije": ["Isst", "Esst", "Esse", "Essen"], "tocan_odgovor": 0, "obasnjenje": "Pitanje u 2. licu jednine (du isst)." },
    { "id": 31, "semester": 2, "pitanje": "Meine Schwester _______ schön. (pjeva)", "opcije": ["singe", "singst", "singt", "singen"], "tocan_odgovor": 2, "obasnjenje": "Treće lice jednine (She) -nastavak -t." },
    { "id": 32, "semester": 2, "pitanje": "Ich brauche _______ Heft.", "opcije": ["der", "die", "das", "den"], "tocan_odgovor": 2, "obasnjenje": "Akkusativ za srednji rod je nepromijenjen (das)." },
    { "id": 33, "semester": 2, "pitanje": "Wir _________ einen Test. (pišemo)", "opcije": ["schreibe", "schreibst", "schreibt", "schreiben"], "tocan_odgovor": 3, "obasnjenje": "Nastavak -en za prvo lice množine (Wir)." },
    { "id": 34, "semester": 2, "pitanje": "Koja je zamjenica za 'Das Mädchen'?", "opcije": ["Er", "Sie", "Es", "Wir"], "tocan_odgovor": 2, "obasnjenje": "Iako je djevojčica, riječ Mädchen je srednjeg roda (Es)." },
    { "id": 35, "semester": 2, "pitanje": "_______ ihr nach Zagreb?", "opcije": ["fahre", "fährst", "fahrt", "fahrt"], "tocan_odgovor": 3, "obasnjenje": "Drugo lice množine (Ihr) ima nastavak -t (bez prijeglasa)." },
    { "id": 36, "semester": 2, "pitanje": "Das ist _______ Banane.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 1, "obasnjenje": "Neodređeni član za ženski rod (eine)." },
    { "id": 37, "semester": 2, "pitanje": "Ich _______ Deutsch sprehen. (mogu)", "opcije": ["kann", "kannst", "könnt", "können"], "tocan_odgovor": 0, "obasnjenje": "Glagol 'können' za 'Ich' je 'kann'." },
    { "id": 38, "semester": 2, "pitanje": "_______ du das? Ja, ja.", "opcije": ["Verstehe", "Verstehst", "Versteht", "Verstehen"], "tocan_odgovor": 1, "obasnjenje": "Nastavak -st uz zamjenicu 'du'." },
    { "id": 39, "semester": 2, "pitanje": "Er _______ mir. (pomaže)", "opcije": ["hilfe", "hilfst", "hilft", "helfen"], "tocan_odgovor": 2, "obasnjenje": "Glagol 'helfen' je nepravilan (er hilft)." },
    { "id": 40, "semester": 2, "pitanje": "Das sind _______ Kinder.", "opcije": ["ein", "eine", "/", "einen"], "tocan_odgovor": 2, "obasnjenje": "Neodređeni član nema množinu." },
    { "id": 41, "semester": 2, "pitanje": "Ich habe _______ Katze.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 1, "obasnjenje": "Akkusativ ženskog roda (eine)." },
    { "id": 42, "semester": 2, "pitanje": "Er _______ heute. (radi)", "opcije": ["arbeite", "arbeitest", "arbeitet", "arbeiten"], "tocan_odgovor": 2, "obasnjenje": "Kako korijen završava na -t, dodajemo -et (arbeitet)." },
    { "id": 43, "semester": 2, "pitanje": "Kako se kaže 'Moram' na njemačkom?", "opcije": ["Ich kann", "Ich muss", "Ich soll", "Ich darf"], "tocan_odgovor": 1, "obasnjenje": "Ich muss znači 'Moram'." },
    { "id": 44, "semester": 2, "pitanje": "Ich sehe _______ Vogel.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 2, "obasnjenje": "Akkusativ muškog roda (Einen Vogel)." },
    { "id": 45, "semester": 2, "pitanje": "Wir _________ ins Kino. (idemo)", "opcije": ["gehe", "gehst", "geht", "gehen"], "tocan_odgovor": 3, "obasnjenje": "Nastavak -en." },
    { "id": 46, "semester": 2, "pitanje": "Bist _______ fertig?", "opcije": ["ich", "du", "er", "sie"], "tocan_odgovor": 1, "obasnjenje": "Glagol 'bist' ide isključivo uz 'du'." },
    { "id": 47, "semester": 2, "pitanje": "Das ist _______ Haus.", "opcije": ["ein", "eine", "einen", "/"], "tocan_odgovor": 0, "obasnjenje": "Srednji rod (ein)." },
    { "id": 48, "semester": 2, "pitanje": "Ich _______ Pizza. (volim)", "opcije": ["mag", "magst", "mögen", "mögt"], "tocan_odgovor": 0, "obasnjenje": "Za 'Ich' glagol 'mögen' glasi 'mag'." },
    { "id": 49, "semester": 2, "pitanje": "Sie _________ Englisch. (uči)", "opcije": ["lerne", "lernst", "lernt", "lernen"], "tocan_odgovor": 2, "obasnjenje": "Treće lice jednine (She) -nastavak -t." },
    { "id": 50, "semester": 2, "pitanje": "Guten Appetit! - _______!", "opcije": ["Hallo", "Danke", "Ja", "Nein"], "tocan_odgovor": 1, "obasnjenje": "Pristojan odgovor na dobar tek je 'hvala'." },
    // 51-100: Vokabular (Riječi)
    { "id": 51, "semester": 1, "pitanje": "Kako kažemo 'Konj' na njemačkom?", "opcije": ["Kuh", "Pferd", "Schwein", "Hund"], "tocan_odgovor": 1, "obasnjenje": "Das Pferd je konj." },
    { "id": 52, "semester": 1, "pitanje": "Što od ovoga je namještaj za jelo?", "opcije": ["Schrank", "Tisch", "Bett", "Sessel"], "tocan_odgovor": 1, "obasnjenje": "Der Tisch je stol." },
    { "id": 53, "semester": 1, "pitanje": "Kako se kaže 'Mrkva' na njemačkom?", "opcije": ["Kartoffel", "Karotte", "Gurke", "Tomate"], "tocan_odgovor": 1, "obasnjenje": "Die Karotte je mrkva." },
    { "id": 54, "semester": 1, "pitanje": "Die Sonne ist _______ (žuta).", "opcije": ["Rot", "Blau", "Gelb", "Grün"], "tocan_odgovor": 2, "obasnjenje": "Gelb znači žuto." },
    { "id": 55, "semester": 1, "pitanje": "Tko radi u školi?", "opcije": ["Arzt", "Lehrer", "Pilot", "Koch"], "tocan_odgovor": 1, "obasnjenje": "Der Lehrer je učitelj." },
    { "id": 56, "semester": 1, "pitanje": "Knjige nosim u _______ (školskoj torbi).", "opcije": ["Bett", "Schultasche", "Küche", "Auto"], "tocan_odgovor": 1, "obasnjenje": "Schultasche je školska torba." },
    { "id": 57, "semester": 1, "pitanje": "U kojoj sobi stoji kauč (Sofa)?", "opcije": ["Bad", "Wohnzimmer", "Garten", "Keller"], "tocan_odgovor": 1, "obasnjenje": "Wohnzimmer je dnevni boravak." },
    { "id": 58, "semester": 1, "pitanje": "Crveno voće je _______ (jabuka).", "opcije": ["Banane", "Apfel", "Birne", "Zitrone"], "tocan_odgovor": 1, "obasnjenje": "Der Apfel (jabuka) je često crven." },
    { "id": 59, "semester": 1, "pitanje": "Kralj životinja je _______ (lav).", "opcije": ["Affe", "Löwe", "Tiger", "Wolf"], "tocan_odgovor": 1, "obasnjenje": "Der Löwe je lav." },
    { "id": 60, "semester": 1, "pitanje": "Igram se na _______ (računalu).", "opcije": ["Stuhl", "Computer", "Fenster", "Tisch"], "tocan_odgovor": 1, "obasnjenje": "Der Computer je računalo." },
    { "id": 61, "semester": 1, "pitanje": "Mama je moja _______ (Mutter).", "opcije": ["Vater", "Mutter", "Opa", "Onkel"], "tocan_odgovor": 1, "obasnjenje": "Die Mutter je majka." },
    { "id": 62, "semester": 1, "pitanje": "U moru se može _______ (plivati).", "opcije": ["Laufen", "Schwimmen", "Lesen", "Kochen"], "tocan_odgovor": 1, "obasnjenje": "Schwimmen znači plivati." },
    { "id": 63, "semester": 1, "pitanje": "Gdje ima puno knjiga?", "opcije": ["Park", "Bibliothek", "Kino", "Zoo"], "tocan_odgovor": 1, "obasnjenje": "Bibliothek je knjižnica." },
    { "id": 64, "semester": 1, "pitanje": "Smijem se, znači da sam _______ (sretan).", "opcije": ["Traurig", "Glücklich", "Müde", "Böse"], "tocan_odgovor": 1, "obasnjenje": "Glücklich znači sretan." },
    { "id": 65, "semester": 1, "pitanje": "Što nosimo na nogama?", "opcije": ["Hüte", "Schuhe", "Handschuhe", "Hemden"], "tocan_odgovor": 1, "obasnjenje": "Die Schuhe su cipele." },
    { "id": 66, "semester": 1, "pitanje": "Bijelo piće od krave:", "opcije": ["Saft", "Wasser", "Milch", "Tee"], "tocan_odgovor": 2, "obasnjenje": "Die Milch je mlijeko." },
    { "id": 67, "semester": 1, "pitanje": "Opasna zelena životinja:", "opcije": ["Frosch", "Krokodil", "Papagei", "Hase"], "tocan_odgovor": 1, "obasnjenje": "Das Krokodil je opasan i zeleno." },
    { "id": 68, "semester": 1, "pitanje": "Gledam kroz _______ (prozor).", "opcije": ["Boden", "Wand", "Fenster", "Dach"], "tocan_odgovor": 2, "obasnjenje": "Das Fenster je prozor." },
    { "id": 69, "semester": 1, "pitanje": "Pišem _______ (olovkom).", "opcije": ["Bleistift", "Radiergummi", "Lineal", "Buch"], "tocan_odgovor": 0, "obasnjenje": "Der Bleistift je olovka." },
    { "id": 70, "semester": 1, "pitanje": "Sin od moje tete je moj _______ (bratić).", "opcije": ["Bruder", "Cousin", "Vater", "Onkel"], "tocan_odgovor": 1, "obasnjenje": "Cousin je bratić." },
    { "id": 71, "semester": 1, "pitanje": "Što je bijelo i jede se?", "opcije": ["Brot", "Reis", "Fleisch", "Salat"], "tocan_odgovor": 1, "obasnjenje": "Der Reis je riža." },
    { "id": 72, "semester": 1, "pitanje": "Nebo je _______ (plavo).", "opcije": ["Rosa", "Blau", "Schwarz", "Gelb"], "tocan_odgovor": 1, "obasnjenje": "Blau znači plavo." },
    { "id": 73, "semester": 1, "pitanje": "Gdje mama kuha?", "opcije": ["Schlafzimmer", "Küche", "Bad", "Garage"], "tocan_odgovor": 1, "obasnjenje": "Die Kitchen je kuhinja." },
    { "id": 74, "semester": 1, "pitanje": "Gdje se gledaju filmovi?", "opcije": ["Bank", "Kino", "Park", "Supermarkt"], "tocan_odgovor": 1, "obasnjenje": "Das Kino je kino." },
    { "id": 75, "semester": 1, "pitanje": "Instrument sa žicama:", "opcije": ["Trommel", "Gitarre", "Klavier", "Flöte"], "tocan_odgovor": 1, "obasnjenje": "Die Gitarre je gitara." },
    { "id": 76, "semester": 1, "pitanje": "Velika siva životinja sa surlom:", "opcije": ["Nashorn", "Elefant", "Tiger", "Bär"], "tocan_odgovor": 1, "obasnjenje": "Der Elefant je slon." },
    { "id": 77, "semester": 2, "pitanje": "Trebam _______ za sendvič (kruh).", "opcije": ["Milch", "Brot", "Wasser", "Zucker"], "tocan_odgovor": 1, "obasnjenje": "Das Brot je kruh." },
    { "id": 78, "semester": 2, "pitanje": "Trava je _______ (zelena).", "opcije": ["Braun", "Grün", "Violett", "Grau"], "tocan_odgovor": 1, "obasnjenje": "Grün znači zeleno." },
    { "id": 79, "semester": 2, "pitanje": "Gdje se ljudi tuširaju?", "opcije": ["Küche", "Badezimmer", "Garten", "Garage"], "tocan_odgovor": 1, "obasnjenje": "Badezimmer je kupaonica." },
    { "id": 80, "semester": 2, "pitanje": "Tko pomaže bolesnim ljudima?", "opcije": ["Koch", "Arzt", "Kellner", "Maler"], "tocan_odgovor": 1, "obasnjenje": "Der Arzt je liječnik." },
    { "id": 81, "semester": 2, "pitanje": "Vozilo na dva kotača:", "opcije": ["Auto", "Fahrrad", "Bus", "Zug"], "tocan_odgovor": 1, "obasnjenje": "Das Fahrrad je bicikl." },
    { "id": 82, "semester": 2, "pitanje": "I voće i boja (narančasta):", "opcije": ["Zitrone", "Apfel", "Orange", "Kirsche"], "tocan_odgovor": 2, "obasnjenje": "Die Orange (naranča) je narančaste boje." },
    { "id": 83, "semester": 2, "pitanje": "Spavam u _______ (krevetu).", "opcije": ["Stuhl", "Tisch", "Bett", "Sofa"], "tocan_odgovor": 2, "obasnjenje": "Das Bett je krevet." },
    { "id": 84, "semester": 2, "pitanje": "Gdje se djeca igraju vani?", "opcije": ["Museum", "Kino", "Park", "Schule"], "tocan_odgovor": 2, "obasnjenje": "Park je park." },
    { "id": 85, "semester": 2, "pitanje": "Životinja koja kaže 'Miau':", "opcije": ["Hund", "Hamster", "Katze", "Fisch"], "tocan_odgovor": 2, "obasnjenje": "Die Katze je mačka." },
    { "id": 86, "semester": 2, "pitanje": "Hladna prozirna tekućina:", "opcije": ["Saft", "Kaffee", "Wasser", "Milch"], "tocan_odgovor": 2, "obasnjenje": "Das Wasser je voda." },
    { "id": 87, "semester": 2, "pitanje": "Vruće na nebu:", "opcije": ["Mond", "Sterne", "Sonne", "Wolken"], "tocan_odgovor": 2, "obasnjenje": "Die Sonne je sunce." },
    { "id": 88, "semester": 2, "pitanje": "Nosim _______ na glavi (šešir).", "opcije": ["Mantel", "Hut", "Socken", "Schal"], "tocan_odgovor": 1, "obasnjenje": "Der Hut je šešir/kapa." },
    { "id": 90, "semester": 2, "pitanje": "Čitam _______ (knjigu).", "opcije": ["Stift", "Buch", "Handy", "Schlüssel"], "tocan_odgovor": 1, "obasnjenje": "Das Buch je knjiga." },
    { "id": 91, "semester": 2, "pitanje": "Kćer moje majke je moja _______ (sestra).", "opcije": ["Bruder", "Schwester", "Tante", "Oma"], "tocan_odgovor": 1, "obasnjenje": "Die Schwester je sestra." },
    { "id": 92, "semester": 2, "pitanje": "Žuta duga voćka:", "opcije": ["Apfel", "Banane", "Traube", "Melone"], "tocan_odgovor": 1, "obasnjenje": "Die Banane je banana." },
    { "id": 93, "semester": 2, "pitanje": "Sjedim na _______ (stolici).", "opcije": ["Boden", "Stuhl", "Teller", "Tisch"], "tocan_odgovor": 1, "obasnjenje": "Der Stuhl je stolica." },
    { "id": 94, "semester": 2, "pitanje": "Životinja koja leti:", "opcije": ["Hund", "Fisch", "Vogel", "Schlange"], "tocan_odgovor": 2, "obasnjenje": "Der Vogel je ptica." },
    { "id": 95, "semester": 2, "pitanje": "Autos fahren po _______ (ulici).", "opcije": ["See", "Himmel", "Straße", "Haus"], "tocan_odgovor": 2, "obasnjenje": "Die Straße je ulica." },
    { "id": 96, "semester": 2, "pitanje": "Sport s loptom (nogomet):", "opcije": ["Tennis", "Surfen", "Fußball", "Skifahren"], "tocan_odgovor": 2, "obasnjenje": "Fußball je nogomet." },
    { "id": 97, "semester": 2, "pitanje": "Voda koja pada s neba:", "opcije": ["Schnee", "Regen", "Sonne", "Wind"], "tocan_odgovor": 1, "obasnjenje": "Regen znači kiša." },
    { "id": 98, "semester": 2, "pitanje": "Slatko za rođendan (kolač):", "opcije": ["Pizza", "Salad", "Kuchen", "Suppe"], "tocan_odgovor": 2, "obasnjenje": "Der Kuchen je kolač/torta." },
    { "id": 99, "semester": 2, "pitanje": "Životinja koja kaže 'Wuff':", "opcije": ["Katze", "Hund", "Vogel", "Maus"], "tocan_odgovor": 1, "obasnjenje": "Der Hund je pas." },
    { "id": 100, "semester": 2, "pitanje": "Što nosimo na tijelu?", "opcije": ["Schuh", "Hemd", "Hut", "Radio"], "tocan_odgovor": 1, "obasnjenje": "Das Hemd je košulja." },
    { "id": 101, "semester": 2, "pitanje": "Gdje sjediš u razredu? (radni stol)", "opcije": ["Bed", "Schreibtisch", "Sofa", "Kitchen"], "tocan_odgovor": 1, "obasnjenje": "Der Schreibtisch je radni stol." }
];
