const GER_5_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Ich _______ Marko.", "opcije": ["bist", "sind", "ist", "bin"], "tocan_odgovor": 3, "obasnjenje": "Uz zamjenicu 'Ich' uvijek koristimo 'bin' (ja sam)." },
    { "id": 2, "semester": 1, "pitanje": "Du _______ fleiÃŸig.", "opcije": ["bin", "ist", "sind", "bist"], "tocan_odgovor": 3, "obasnjenje": "Uz 'Du' (ti) koristimo 'bist' (ti si)." },
    { "id": 3, "semester": 1, "pitanje": "Wir _______ ein Haus.", "opcije": ["haben", "habt", "hast", "hat"], "tocan_odgovor": 0, "obasnjenje": "Za mnoÅ¾inu (Wir/Sie/svi) koristimo 'haben' (imamo/imaju)." },
    { "id": 4, "semester": 1, "pitanje": "Das ist _______ Tisch.", "opcije": ["den", "der", "das", "die"], "tocan_odgovor": 1, "obasnjenje": "OdreÄ‘eni Älan 'der' koristimo za muÅ¡ki rod (npr. Tisch)." },
    { "id": 5, "semester": 1, "pitanje": "Ich habe _______ Bruder.", "opcije": ["eine", "eines", "einen", "ein"], "tocan_odgovor": 2, "obasnjenje": "U akuzativu (objekt) muÅ¡ki Älan 'ein' postaje 'einen'." },
    { "id": 6, "semester": 1, "pitanje": "Er _______ Fußball.", "opcije": ["spielen", "spielst", "spiele", "spielt"], "tocan_odgovor": 3, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 7, "semester": 1, "pitanje": "Wir _______ nach Hause.", "opcije": ["gehe", "gehen", "gehst", "geht"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 8, "semester": 1, "pitanje": "Wie _______ du?", "opcije": ["heiße", "heißen", "heißt", "heißt"], "tocan_odgovor": 2, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 9, "semester": 1, "pitanje": "Das ist _______ Tasche.", "opcije": ["das", "den", "der", "die"], "tocan_odgovor": 3, "obasnjenje": "OdreÄ‘eni Älan 'die' koristimo za Å¾enski rod ili mnoÅ¾inu." },
    { "id": 10, "semester": 1, "pitanje": "Sie _______ 10 Jahre alt.", "opcije": ["bin", "bist", "sind", "ist"], "tocan_odgovor": 3, "obasnjenje": "Za on/ona/ono (Er/Sie/Es) koristimo 'ist' (je)." },
    { "id": 11, "semester": 1, "pitanje": "Ihr _______ fleißig.", "opcije": ["bin", "ist", "seid", "bist"], "tocan_odgovor": 2, "obasnjenje": "Glagol 'seid' koristimo za vi (Ihr)." },
    { "id": 12, "semester": 1, "pitanje": "Das ist _______ Buch.", "opcije": ["der", "das", "den", "die"], "tocan_odgovor": 1, "obasnjenje": "OdreÄ‘eni Älan 'das' koristimo za srednji rod (npr. Buch)." },
    { "id": 13, "semester": 1, "pitanje": "Habt _______ ein Hobby?", "opcije": ["ihr", "wir", "sie", "du"], "tocan_odgovor": 0, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 14, "semester": 1, "pitanje": "Ich ________ Cola.", "opcije": ["trinken", "trinke", "trinkt", "trinkst"], "tocan_odgovor": 1, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 15, "semester": 1, "pitanje": "Mein Vater ... Koja je zamjenica?", "opcije": ["Er", "Du", "Sie", "Ich"], "tocan_odgovor": 0, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 16, "semester": 1, "pitanje": "Das ist _______ Apfel.", "opcije": ["/", "ein", "eine", "einen"], "tocan_odgovor": 1, "obasnjenje": "NeodreÄ‘eni Älan 'ein' koristimo za muÅ¡ki ili srednji rod." },
    { "id": 17, "semester": 1, "pitanje": "Wo _______ du?", "opcije": ["wohnst", "wohnen", "wohnt", "wohne"], "tocan_odgovor": 0, "obasnjenje": "Upitna zamjenica 'Wo' znaÄi 'Gdje'." },
    { "id": 18, "semester": 1, "pitanje": "Wir _______ Deutsch.", "opcije": ["lernt", "lernen", "lerne", "lernst"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 19, "semester": 1, "pitanje": "Meine Mutter ... Koja je zamjenica?", "opcije": ["Wir", "Sie", "Es", "Er"], "tocan_odgovor": 1, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 20, "semester": 1, "pitanje": "Sie _______ aus Split.", "opcije": ["kommst", "kommen", "komme", "kommt"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 21, "semester": 1, "pitanje": "_______ ist das? Das ist Petra.", "opcije": ["Was", "Wo", "Wer", "Wie"], "tocan_odgovor": 2, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 22, "semester": 1, "pitanje": "Die Schule", "opcije": ["ein", "/", "einen", "eine"], "tocan_odgovor": 3, "obasnjenje": "NeodreÄ‘eni Älan 'eine' koristimo za Å¾enski rod." },
    { "id": 23, "semester": 1, "pitanje": "Das Kind _______ .", "opcije": ["schläfst", "schläft", "schlafen", "schlafe"], "tocan_odgovor": 1, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 24, "semester": 1, "pitanje": "Was _______ du gerne?", "opcije": ["esst", "isst", "esse", "essen"], "tocan_odgovor": 1, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 25, "semester": 1, "pitanje": "Ich _______ keine Zeit.", "opcije": ["hat", "habe", "haben", "hast"], "tocan_odgovor": 1, "obasnjenje": "Uz 'Ich' (ja) koristimo 'habe' (imam)." },
    { "id": 26, "semester": 2, "pitanje": "Ich suche _______ Ball.", "opcije": ["der", "das", "den", "die"], "tocan_odgovor": 2, "obasnjenje": "U akuzativu 'der' postaje 'den' (objekt radnje)." },
    { "id": 27, "semester": 2, "pitanje": "Du siehst _______ Film.", "opcije": ["eine", "einen", "/", "ein"], "tocan_odgovor": 1, "obasnjenje": "U akuzativu (objekt) muÅ¡ki Älan 'ein' postaje 'einen'." },
    { "id": 28, "semester": 2, "pitanje": "Er kauft _______ Buch.", "opcije": ["eine", "/", "einen", "ein"], "tocan_odgovor": 3, "obasnjenje": "NeodreÄ‘eni Älan 'ein' koristimo za muÅ¡ki ili srednji rod." },
    { "id": 29, "semester": 2, "pitanje": "Wir besuchen _______ Oma.", "opcije": ["/", "ein", "eine", "einen"], "tocan_odgovor": 2, "obasnjenje": "NeodreÄ‘eni Älan 'eine' koristimo za Å¾enski rod." },
    { "id": 30, "semester": 2, "pitanje": "_______ du Pizza?", "opcije": ["Isst", "Esse", "Essen", "Esst"], "tocan_odgovor": 0, "obasnjenje": "U prezentu uz 'du' glagoli dobivaju nastavak -st." },
    { "id": 31, "semester": 2, "pitanje": "Meine Schwester _______ schön.", "opcije": ["singst", "singen", "singe", "singt"], "tocan_odgovor": 3, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 32, "semester": 2, "pitanje": "Ich brauche _______ Heft.", "opcije": ["den", "die", "der", "das"], "tocan_odgovor": 3, "obasnjenje": "OdreÄ‘eni Älan 'das' koristimo za srednji rod (npr. Buch)." },
    { "id": 33, "semester": 2, "pitanje": "Wir _________ einen Test.", "opcije": ["schreibe", "schreibst", "schreibt", "schreiben"], "tocan_odgovor": 3, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 34, "semester": 2, "pitanje": "Das Mädchen ... Koja je zamjenica?", "opcije": ["Sie", "Wir", "Er", "Es"], "tocan_odgovor": 3, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 35, "semester": 2, "pitanje": "_______ ihr nach Zagreb?", "opcije": ["fahrt", "fährst", "fahrt", "fahre"], "tocan_odgovor": 0, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 36, "semester": 2, "pitanje": "Das ist _______ Banane.", "opcije": ["einen", "/", "eine", "ein"], "tocan_odgovor": 2, "obasnjenje": "NeodreÄ‘eni Älan 'eine' koristimo za Å¾enski rod." },
    { "id": 37, "semester": 2, "pitanje": "Ich _______ Deutsch sprechen.", "opcije": ["könnt", "kann", "können", "kannst"], "tocan_odgovor": 1, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 38, "semester": 2, "pitanje": "_______ du das? Ja, ja.", "opcije": ["Verstehen", "Verstehst", "Verstehe", "Versteht"], "tocan_odgovor": 1, "obasnjenje": "U prezentu uz 'du' glagoli dobivaju nastavak -st." },
    { "id": 39, "semester": 2, "pitanje": "Er _______ mir.", "opcije": ["hilfe", "hilft", "helfen", "hilfst"], "tocan_odgovor": 1, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 40, "semester": 2, "pitanje": "Das sind _______ Kinder.", "opcije": ["eine", "/", "ein", "einen"], "tocan_odgovor": 1, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 41, "semester": 2, "pitanje": "Ich habe _______ Katze.", "opcije": ["ein", "einen", "/", "eine"], "tocan_odgovor": 3, "obasnjenje": "NeodreÄ‘eni Älan 'eine' koristimo za Å¾enski rod." },
    { "id": 42, "semester": 2, "pitanje": "Er _______ heute.", "opcije": ["arbeite", "arbeiten", "arbeitest", "arbeitet"], "tocan_odgovor": 3, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 43, "semester": 2, "pitanje": "Was ist 'moram' auf Deutsch?", "opcije": ["Ich darf", "Ich soll", "Ich muss", "Ich kann"], "tocan_odgovor": 2, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 44, "semester": 2, "pitanje": "Ich sehe _______ Vogel.", "opcije": ["eine", "einen", "ein", "/"], "tocan_odgovor": 1, "obasnjenje": "U akuzativu (objekt) muÅ¡ki Älan 'ein' postaje 'einen'." },
    { "id": 45, "semester": 2, "pitanje": "Wir _________ ins Kino.", "opcije": ["geht", "gehen", "gehe", "gehst"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 46, "semester": 2, "pitanje": "Bist _______ fertig?", "opcije": ["er", "sie", "du", "ich"], "tocan_odgovor": 2, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 47, "semester": 2, "pitanje": "Das ist _______ Haus.", "opcije": ["einen", "/", "ein", "eine"], "tocan_odgovor": 2, "obasnjenje": "NeodreÄ‘eni Älan 'ein' koristimo za muÅ¡ki ili srednji rod." },
    { "id": 48, "semester": 2, "pitanje": "Ich _______ Pizza.", "opcije": ["magst", "mögen", "mögt", "mag"], "tocan_odgovor": 3, "obasnjenje": "Pravilna gramatika i vokabular za 5. razred." },
    { "id": 49, "semester": 2, "pitanje": "Sie _________ Englisch.", "opcije": ["lernst", "lernen", "lernt", "lerne"], "tocan_odgovor": 2, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 50, "semester": 2, "pitanje": "Guten Appetit! - _______!", "opcije": ["Hallo", "Nein", "Ja", "Danke"], "tocan_odgovor": 3, "obasnjenje": "NjemaÄki vokabular: Danke je toÄan odgovor." },
    { "id": 51, "semester": 1, "pitanje": "Was ist 'konj' auf Deutsch?", "opcije": ["Pferd", "Hund", "Kuh", "Schwein"], "tocan_odgovor": 0, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 52, "semester": 1, "pitanje": "Was ist ein Möbelstück?", "opcije": ["Tisch", "Sonne", "Hund", "Apfel"], "tocan_odgovor": 0, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 53, "semester": 1, "pitanje": "Was ist 'mrkva' auf Deutsch?", "opcije": ["Kartoffel", "Tomate", "Karotte", "Gurke"], "tocan_odgovor": 2, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 54, "semester": 1, "pitanje": "Die Sonne ist _______ .", "opcije": ["Grün", "Rot", "Gelb", "Blau"], "tocan_odgovor": 2, "obasnjenje": "Gelb je Å¾uta boja." },
    { "id": 55, "semester": 1, "pitanje": "Wer arbeitet in der Schule?", "opcije": ["Koch", "Pilot", "Lehrer", "Arzt"], "tocan_odgovor": 2, "obasnjenje": "Upitna zamjenica 'Wer' znaÄi 'Tko'." },
    { "id": 56, "semester": 1, "pitanje": "Die Bücher sind in der _______ .", "opcije": ["Küche", "Auto", "Bett", "Schultasche"], "tocan_odgovor": 3, "obasnjenje": "Schultasche je Å¡kolska torba." },
    { "id": 57, "semester": 1, "pitanje": "Das Sofa steht im _______ .", "opcije": ["Wohnzimmer", "Bad", "Keller", "Garten"], "tocan_odgovor": 0, "obasnjenje": "Wohnzimmer je dnevni boravak." },
    { "id": 58, "semester": 1, "pitanje": "Ein Apfel ist _______ .", "opcije": ["Blau", "Lila", "Gelb", "Rot"], "tocan_odgovor": 3, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 59, "semester": 1, "pitanje": "Der König der Tiere ist der _______ .", "opcije": ["Affe", "Wolf", "Tiger", "Löwe"], "tocan_odgovor": 3, "obasnjenje": "NjemaÄki vokabular: Löwe je toÄan odgovor." },
    { "id": 60, "semester": 1, "pitanje": "Ich spiele am _______ .", "opcije": ["Computer", "Fenster", "Tisch", "Stuhl"], "tocan_odgovor": 0, "obasnjenje": "Computer je raÄunalo." },
    { "id": 61, "semester": 1, "pitanje": "Die Mutter ist _______ .", "opcije": ["Vater", "Onkel", "Opa", "Mama"], "tocan_odgovor": 3, "obasnjenje": "NjemaÄki vokabular: Mama je toÄan odgovor." },
    { "id": 62, "semester": 1, "pitanje": "Im Meer kann man _______ .", "opcije": ["Schwimmen", "Laufen", "Lesen", "Kochen"], "tocan_odgovor": 0, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 63, "semester": 1, "pitanje": "Viele Bücher sind in der _______ .", "opcije": ["Park", "Bibliothek", "Zoo", "Kino"], "tocan_odgovor": 1, "obasnjenje": "Bibliothek je knjiÅ¾nica." },
    { "id": 64, "semester": 1, "pitanje": "Ich bin _______ .", "opcije": ["müde", "glücklich", "traurig", "böse"], "tocan_odgovor": 1, "obasnjenje": "NjemaÄki vokabular: glücklich je toÄan odgovor." },
    { "id": 65, "semester": 1, "pitanje": "Ich trage _______ an den Füßen.", "opcije": ["Schuhe", "Hüte", "Handschuhe", "Hemden"], "tocan_odgovor": 0, "obasnjenje": "Schuhe su cipele." },
    { "id": 66, "semester": 1, "pitanje": "Die Kuh daje _______ .", "opcije": ["Wasser", "Tee", "Milch", "Saft"], "tocan_odgovor": 2, "obasnjenje": "Milch znaÄi mlijeko." },
    { "id": 67, "semester": 1, "pitanje": "Das Krokodil ist _______ .", "opcije": ["gefährlich", "gelb", "klein", "süß"], "tocan_odgovor": 0, "obasnjenje": "NjemaÄki vokabular: gefährlich je toÄan odgovor." },
    { "id": 68, "semester": 1, "pitanje": "Ich schaue aus dem _______ .", "opcije": ["Dach", "Boden", "Fenster", "Wand"], "tocan_odgovor": 2, "obasnjenje": "Fenster znaÄi prozor." },
    { "id": 69, "semester": 1, "pitanje": "Ich schreibe mit dem _______ .", "opcije": ["Lineal", "Radiergummi", "Bleistift", "Buch"], "tocan_odgovor": 2, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 70, "semester": 1, "pitanje": "Der Sohn von meiner Tante je moj _______ .", "opcije": ["Vater", "Cousin", "Onkel", "Bruder"], "tocan_odgovor": 1, "obasnjenje": "Cousin je bratiÄ‡." },
    { "id": 71, "semester": 1, "pitanje": "Reis ist _______ .", "opcije": ["Salat", "weiß", "Brot", "Fleisch"], "tocan_odgovor": 1, "obasnjenje": "NjemaÄki vokabular: weiß je toÄan odgovor." },
    { "id": 72, "semester": 1, "pitanje": "Der Himmel ist _______ .", "opcije": ["Schwarz", "Blau", "Gelb", "Rosa"], "tocan_odgovor": 1, "obasnjenje": "NjemaÄki vokabular: Blau je toÄan odgovor." },
    { "id": 73, "semester": 1, "pitanje": "Wo kocht die Mutter?", "opcije": ["Schlafzimmer", "Bad", "Küche", "Garage"], "tocan_odgovor": 2, "obasnjenje": "Upitna zamjenica 'Wo' znaÄi 'Gdje'." },
    { "id": 74, "semester": 1, "pitanje": "Wo sieht man Filme?", "opcije": ["Supermarkt", "Kino", "Park", "Bank"], "tocan_odgovor": 1, "obasnjenje": "Upitna zamjenica 'Wo' znaÄi 'Gdje'." },
    { "id": 75, "semester": 1, "pitanje": "Die Gitarre ist ein _______ .", "opcije": ["Trommel", "Instrument", "Klavier", "Flöte"], "tocan_odgovor": 1, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 76, "semester": 1, "pitanje": "Der Elefant ist _______ .", "opcije": ["grün", "groß", "gelb", "klein"], "tocan_odgovor": 1, "obasnjenje": "NjemaÄki vokabular: groß je toÄan odgovor." },
    { "id": 77, "semester": 2, "pitanje": "Ich brauche _______ für das Sandwich.", "opcije": ["Zucker", "Milch", "Wasser", "Brot"], "tocan_odgovor": 3, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 78, "semester": 2, "pitanje": "Das Gras ist _______ .", "opcije": ["Grün", "Grau", "Violett", "Braun"], "tocan_odgovor": 0, "obasnjenje": "NjemaÄki vokabular: Grün je toÄan odgovor." },
    { "id": 79, "semester": 2, "pitanje": "Ich dusche im _______ .", "opcije": ["Garage", "Küche", "Badezimmer", "Garten"], "tocan_odgovor": 2, "obasnjenje": "Badezimmer je kupaonica." },
    { "id": 80, "semester": 2, "pitanje": "Der Arzt hilft _______ Menschen.", "opcije": ["lustigen", "kranken", "großen", "starken"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 81, "semester": 2, "pitanje": "Das Fahrrad hat zwei _______ .", "opcije": ["Autos", "Räder", "Züge", "Busse"], "tocan_odgovor": 1, "obasnjenje": "NjemaÄki vokabular: Räder je toÄan odgovor." },
    { "id": 82, "semester": 2, "pitanje": "Die Orange ist _______ .", "opcije": ["Orange", "Blau", "Gelb", "Rot"], "tocan_odgovor": 0, "obasnjenje": "Orange je naranÄasta boja." },
    { "id": 83, "semester": 2, "pitanje": "Ich schlafe im _______ .", "opcije": ["Bett", "Sofa", "Tisch", "Stuhl"], "tocan_odgovor": 0, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 84, "semester": 2, "pitanje": "Kinder spielen im _______ .", "opcije": ["Park", "Schule", "Museum", "Kino"], "tocan_odgovor": 0, "obasnjenje": "U parku se djeca igraju." },
    { "id": 85, "semester": 2, "pitanje": "Die Katze macht _______ .", "opcije": ["Piep", "Miau", "Wuff", "Muh"], "tocan_odgovor": 1, "obasnjenje": "MaÄke mijauÄu (miau)." },
    { "id": 86, "semester": 2, "pitanje": "Wasser je _______ .", "opcije": ["heiß", "kalt", "süž", "rot"], "tocan_odgovor": 1, "obasnjenje": "Upitna zamjenica 'Was' znaÄi 'Å to'." },
    { "id": 87, "semester": 2, "pitanje": "Die Sonne ist _______ .", "opcije": ["nass", "dunkel", "kalt", "heiß"], "tocan_odgovor": 3, "obasnjenje": "NjemaÄki vokabular: heiß je toÄan odgovor." },
    { "id": 88, "semester": 2, "pitanje": "Ich trage den _______ auf dem Kopf.", "opcije": ["Mantel", "Schal", "Hut", "Socken"], "tocan_odgovor": 2, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 89, "semester": 2, "pitanje": "Ich lese ein _______ .", "opcije": ["Handy", "Buch", "Stift", "Schlüssel"], "tocan_odgovor": 1, "obasnjenje": "Buch znaÄi knjiga." },
    { "id": 90, "semester": 2, "pitanje": "Die Schwester ist ein _______ .", "opcije": ["Hund", "Junge", "Mädchen", "Baum"], "tocan_odgovor": 2, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 91, "semester": 2, "pitanje": "Die Banane ist _______ .", "opcije": ["Gelb", "Grün", "Rot", "Schwarz"], "tocan_odgovor": 0, "obasnjenje": "Gelb je Å¾uta boja." },
    { "id": 92, "semester": 2, "pitanje": "Ich sitze auf dem _______ .", "opcije": ["Tisch", "Boden", "Stuhl", "Teller"], "tocan_odgovor": 2, "obasnjenje": "Stuhl je stolica." },
    { "id": 93, "semester": 2, "pitanje": "Der Vogel kann _______ .", "opcije": ["lesen", "fliegen", "kochen", "schwimmen"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 94, "semester": 2, "pitanje": "Autos fahren auf der _______ .", "opcije": ["Straße", "Himmel", "Haus", "See"], "tocan_odgovor": 0, "obasnjenje": "NjemaÄki vokabular: Straße je toÄan odgovor." },
    { "id": 95, "semester": 2, "pitanje": "Fußball ist ein _______ .", "opcije": ["Essen", "Sport", "House", "Trinken"], "tocan_odgovor": 1, "obasnjenje": "U prezentu uz 'er/sie/es' glagoli dobivaju nastavak -t." },
    { "id": 96, "semester": 2, "pitanje": "Es regnet. Das ist _______ .", "opcije": ["Sonne", "Regen", "Schnee", "Wind"], "tocan_odgovor": 1, "obasnjenje": "Za 'wir' ili 'sie' (oni) glagoli ostaju u infinitivu (-en)." },
    { "id": 97, "semester": 2, "pitanje": "Der Kuchen ist _______ .", "opcije": ["salzig", "bitter", "süß", "sauer"], "tocan_odgovor": 2, "obasnjenje": "NjemaÄki vokabular: süß je toÄan odgovor." },
    { "id": 98, "semester": 2, "pitanje": "Der Hund macht _______ .", "opcije": ["Miau", "Wuff", "Muh", "Piep"], "tocan_odgovor": 1, "obasnjenje": "Psi kaÅ¾u 'Wuff' (vau-vau)." },
    { "id": 99, "semester": 2, "pitanje": "Das Hemd ist _______ .", "opcije": ["Möbel", "Tier", "Kleidung", "Essen"], "tocan_odgovor": 2, "obasnjenje": "Kleidung je odjeÄ‡a." },
    { "id": 100, "semester": 2, "pitanje": "Ich lerne am _______ .", "opcije": ["Bett", "Sofa", "Herd", "Schreibtisch"], "tocan_odgovor": 3, "obasnjenje": "Schreibtisch je radni stol." }
];
