const MAT_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Kako se zove rezultat zbrajanja?", "opcije": ["Umnožak", "Suma", "Količnik", "Razlika"], "tocan_odgovor": 1, "obasnjenje": "Rezultat zbroja zove se suma." },
    { "id": 2, "semester": 1, "pitanje": "Kako se zove rezultat oduzimanja?", "opcije": ["Razlika", "Količnik", "Suma", "Umnožak"], "tocan_odgovor": 0, "obasnjenje": "Rezultat oduzimanja zove se razlika." },
    { "id": 3, "semester": 1, "pitanje": "Kako se zove rezultat množenja?", "opcije": ["Razlika", "Umnožak", "Suma", "Količnik"], "tocan_odgovor": 1, "obasnjenje": "Rezultat množenja zove se umnožak." },
    { "id": 4, "semester": 1, "pitanje": "Kako se zove rezultat dijeljenja?", "opcije": ["Razlika", "Umnožak", "Količnik", "Suma"], "tocan_odgovor": 2, "obasnjenje": "Rezultat dijeljenja zove se količnik." },
    { "id": 5, "semester": 1, "pitanje": "Koji je najmanji prirodni broj?", "opcije": ["Ne postoji", "1", "0", "10"], "tocan_odgovor": 1, "obasnjenje": "Najmanji prirodni broj je 1." },
    { "id": 6, "semester": 1, "pitanje": "Je li broj 0 prirodni broj?", "opcije": ["Samo ponekad", "Ovisi o državi", "Da", "Ne"], "tocan_odgovor": 3, "obasnjenje": "Prirodni brojevi počinju od 1." },
    { "id": 7, "semester": 1, "pitanje": "Koji je broj neposredni sljedbenik broja 999?", "opcije": ["990", "1000", "998", "1001"], "tocan_odgovor": 1, "obasnjenje": "999 + 1 = 1000." },
    { "id": 8, "semester": 1, "pitanje": "Koji je broj neposredni prethodnik broja 100?", "opcije": ["0", "90", "101", "99"], "tocan_odgovor": 3, "obasnjenje": "100 - 1 = 99." },
    { "id": 9, "semester": 1, "pitanje": "Izračunaj: 125 + 75", "opcije": ["190", "210", "225", "200"], "tocan_odgovor": 3, "obasnjenje": "125 + 75 = 200." },
    { "id": 10, "semester": 1, "pitanje": "Izračunaj: 300 - 125", "opcije": ["175", "275", "185", "150"], "tocan_odgovor": 0, "obasnjenje": "300 - 125 = 175." },
    { "id": 11, "semester": 1, "pitanje": "Koliko je 15 ⋅ 4?", "opcije": ["45", "60", "50", "70"], "tocan_odgovor": 1, "obasnjenje": "15 puta 4 je 60." },
    { "id": 12, "semester": 1, "pitanje": "Koliko je 100 : 4?", "opcije": ["50", "10", "20", "25"], "tocan_odgovor": 3, "obasnjenje": "100 podijeljeno s 4 je 25." },
    { "id": 13, "semester": 1, "pitanje": "Koji je rezultat operacije 0 ⋅ 55?", "opcije": ["1", "0", "Beskonačno", "55"], "tocan_odgovor": 1, "obasnjenje": "Sve pomnoženo s nulom je nula." },
    { "id": 14, "semester": 1, "pitanje": "Je li dijeljenje s nulom moguće?", "opcije": ["Ne", "Samo u geometriji", "Ponekad", "Da"], "tocan_odgovor": 0, "obasnjenje": "Dijeljenje s nulom nije definirano u matematici." },
    { "id": 15, "semester": 1, "pitanje": "Koji broj dobijemo ako 45 zbrojimo s 0?", "opcije": ["45", "0", "90", "450"], "tocan_odgovor": 0, "obasnjenje": "Nula je neutralni element za zbrajanje." },
    { "id": 16, "semester": 1, "pitanje": "Koliko je 72 : 8?", "opcije": ["10", "8", "7", "9"], "tocan_odgovor": 3, "obasnjenje": "9 puta 8 je 72." },
    { "id": 17, "semester": 1, "pitanje": "Broj je djeljiv s 2 ako mu je zadnja znamenka:", "opcije": ["Neparna", "Parna", "Uvijek 0", "Bilo koja"], "tocan_odgovor": 1, "obasnjenje": "Parna znamenka (0,2,4,6,8) znači djeljivost s 2." },
    { "id": 18, "semester": 1, "pitanje": "Koji je od ovih brojeva djeljiv s 5?", "opcije": ["26", "34", "101", "45"], "tocan_odgovor": 3, "obasnjenje": "Brojevi djeljivi s 5 završavaju na 0 ili 5." },
    { "id": 19, "semester": 1, "pitanje": "Broj je djeljiv s 10 ako mu je zadnja znamenka:", "opcije": ["0", "5", "Parna", "1"], "tocan_odgovor": 0, "obasnjenje": "Broj je djeljiv s 10 ako završava s 0." },
    { "id": 20, "semester": 1, "pitanje": "Broj je djeljiv s 5 ako mu je zadnja znamenka:", "opcije": ["0 ili 5", "Parna", "Samo 5", "Samo 0"], "tocan_odgovor": 0, "obasnjenje": "Pravilo djeljivosti s 5." },
    { "id": 21, "semester": 1, "pitanje": "Koji je od ovih brojeva prost broj?", "opcije": ["9", "6", "4", "7"], "tocan_odgovor": 3, "obasnjenje": "7 je djeljiv samo s 1 i sa samim sobom." },
    { "id": 22, "semester": 1, "pitanje": "Što su prosti brojevi?", "opcije": ["Brojevi djeljivi s 2", "Neparni brojevi", "Brojevi koji imaju samo 2 djelitelja (1 i samog sebe)", "Brojevi veći od 100"], "tocan_odgovor": 2, "obasnjenje": "Definicija prostih brojeva." },
    { "id": 23, "semester": 1, "pitanje": "Je li broj 1 prost broj?", "opcije": ["Ne", "Da", "Ponekad", "Samo u matematici"], "tocan_odgovor": 0, "obasnjenje": "1 nije ni prost ni složen broj." },
    { "id": 24, "semester": 1, "pitanje": "Koji je jedini parni prost broj?", "opcije": ["4", "1", "2", "10"], "tocan_odgovor": 2, "obasnjenje": "2 je jedinstven po tome što je paran i prost." },
    { "id": 25, "semester": 1, "pitanje": "Zbroj znamenaka broja 123 je:", "opcije": ["7", "5", "3", "6"], "tocan_odgovor": 3, "obasnjenje": "1+2+3=6." },
    { "id": 26, "semester": 1, "pitanje": "Broj je djeljiv s 3 ako mu je zbroj znamenaka djeljiv s:", "opcije": ["2", "3", "5", "9"], "tocan_odgovor": 1, "obasnjenje": "Pravilo djeljivosti s 3." },
    { "id": 27, "semester": 1, "pitanje": "Je li broj 123 djeljiv s 3?", "opcije": ["Ne", "Možda", "Samo petkom", "Da"], "tocan_odgovor": 3, "obasnjenje": "Jer mu je zbroj znamenaka 6, a 6 je djeljivo s 3." },
    { "id": 28, "semester": 1, "pitanje": "Je li broj 450 djeljiv s 9?", "opcije": ["Samo ako je paran", "Ovisi o kutu", "Da", "Ne"], "tocan_odgovor": 2, "obasnjenje": "Zbroj znamenaka je 9, što je djeljivo s 9." },
    { "id": 29, "semester": 1, "pitanje": "Koji je najmanji zajednički višekratnik brojeva 4 i 6?", "opcije": ["12", "6", "24", "10"], "tocan_odgovor": 0, "obasnjenje": "Najmanji broj djeljiv s oba je 12." },
    { "id": 30, "semester": 1, "pitanje": "Koji je najveći zajednički djelitelj brojeva 12 i 18?", "opcije": ["3", "6", "12", "2"], "tocan_odgovor": 1, "obasnjenje": "6 je najveći broj koji dijeli oba." },
    { "id": 31, "semester": 1, "pitanje": "Dvije točke određuju točno jedan:", "opcije": ["Kut", "Pravac", "Kvadrat", "Trokut"], "tocan_odgovor": 1, "obasnjenje": "Kroz bilo koje dvije točke prolazi točno jedan pravac." },
    { "id": 32, "semester": 1, "pitanje": "Dio pravca omeđen dvjema točkama zove se:", "opcije": ["Dužina", "Točka", "Kružnica", "Zraka"], "tocan_odgovor": 0, "obasnjenje": "Dužina ima početnu i završnu točku." },
    { "id": 33, "semester": 1, "pitanje": "Koliko točaka ima pravac?", "opcije": ["Beskonačno", "Dvije", "Nijednu", "Jednu"], "tocan_odgovor": 0, "obasnjenje": "Pravac je skup beskonačno mnogo točaka." },
    { "id": 34, "semester": 1, "pitanje": "Pravci koji se nikada ne sijeku zovu se:", "opcije": ["Usporedni (paralelni)", "Sječice", "Okomiti", "Kosi"], "tocan_odgovor": 0, "obasnjenje": "Usporedni pravci leže u istoj ravnini i nemaju zajedničkih točaka." },
    { "id": 35, "semester": 1, "pitanje": "Pravci koji se sijeku pod pravim kutom zovu se:", "opcije": ["Okomiti", "Tangente", "Usporedni", "Kosi"], "tocan_odgovor": 0, "obasnjenje": "Okomiti pravci sijeku se pod 90 stupnjeva." },
    { "id": 36, "semester": 1, "pitanje": "Koji je simbol za okomitost?", "opcije": ["Angle", "=", "⊥", "∥"], "tocan_odgovor": 2, "obasnjenje": "⊥ je simbol za okomitost." },
    { "id": 37, "semester": 1, "pitanje": "Koji je simbol za usporednost?", "opcije": ["≈", "⊥", "∥", "<"], "tocan_odgovor": 2, "obasnjenje": "∥ je simbol za usporednost." },
    { "id": 38, "semester": 1, "pitanje": "Kako se zove kut od 90 stupnjeva?", "opcije": ["Ispruženi", "Tupi", "Pravi", "Oštri"], "tocan_odgovor": 2, "obasnjenje": "Pravi kut iznosi točno 90 stupnjeva." },
    { "id": 39, "semester": 1, "pitanje": "Kut manji od 90 stupnjeva je:", "opcije": ["Ispruženi", "Pravi", "Tupi", "Oštri"], "tocan_odgovor": 3, "obasnjenje": "Takav kut zovemo oštrim kutom." },
    { "id": 40, "semester": 1, "pitanje": "Kut veći od 90 stupnjeva, a manji od 180 stupnjeva je:", "opcije": ["Tupi", "Oštri", "Puni", "Pravi"], "tocan_odgovor": 0, "obasnjenje": "Takav kut zovemo tupim kutom." },
    { "id": 41, "semester": 1, "pitanje": "Kako se zove kut od 180 stupnjeva?", "opcije": ["Tupi", "Pravi", "Puni", "Ispruženi"], "tocan_odgovor": 3, "obasnjenje": "Ispruženi kut iznosi 180 stupnjeva." },
    { "id": 42, "semester": 1, "pitanje": "Koliko stupnjeva ima puni kut?", "opcije": ["0", "360", "90", "180"], "tocan_odgovor": 1, "obasnjenje": "Puni krug ima 360 stupnjeva." },
    { "id": 43, "semester": 1, "pitanje": "Opseg pravokutnika s stranicama a i b računa se:", "opcije": ["2 ⋅ (a + b)", "a ⋅ b", "a + b", "a²"], "tocan_odgovor": 0, "obasnjenje": "Formula: O = 2a + 2b." },
    { "id": 44, "semester": 1, "pitanje": "Površina pravokutnika s stranicama a i b računa se:", "opcije": ["a ⋅ b", "a + b", "2 ⋅ (a + b)", "a²"], "tocan_odgovor": 0, "obasnjenje": "Formula: P = a ⋅ b." },
    { "id": 45, "semester": 1, "pitanje": "Opseg kvadrata stranice a je:", "opcije": ["4 ⋅ a", "a²", "a ⋅ a", "a + a"], "tocan_odgovor": 0, "obasnjenje": "Formula: O = 4a." },
    { "id": 46, "semester": 1, "pitanje": "Površina kvadrata stranice a je:", "opcije": ["a ⋅ a (a²)", "2 ⋅ a", "4 ⋅ a", "a + 4"], "tocan_odgovor": 0, "obasnjenje": "Formula: P = a ⋅ a." },
    { "id": 47, "semester": 1, "pitanje": "Koliko mm ima jedan centimetar (1 cm)?", "opcije": ["100", "1000", "10", "5"], "tocan_odgovor": 2, "obasnjenje": "1 cm = 10 mm." },
    { "id": 48, "semester": 1, "pitanje": "Koliko cm ima jedan metar (1 m)?", "opcije": ["100", "1000", "60", "10"], "tocan_odgovor": 0, "obasnjenje": "1 m = 100 cm." },
    { "id": 49, "semester": 1, "pitanje": "Koliko metara ima jedan kilometar (1 km)?", "opcije": ["1000", "10000", "100", "500"], "tocan_odgovor": 0, "obasnjenje": "1 km = 1000 m." },
    { "id": 50, "semester": 1, "pitanje": "Jedinica za površinu je:", "opcije": ["m²", "kg", "m", "m³"], "tocan_odgovor": 0, "obasnjenje": "Površina se mjeri u kvadratnim jedinicama." },
    { "id": 51, "semester": 2, "pitanje": "Što predstavlja gornji broj u razlomku?", "opcije": ["Razlomačka crta", "Nazivnik", "Brojnik", "Cijeli dio"], "tocan_odgovor": 2, "obasnjenje": "On broji dijelove." },
    { "id": 52, "semester": 2, "pitanje": "Što predstavlja donji broj u razlomku?", "opcije": ["Brojnik", "Nazivnik", "Razlomačka crta", "Količnik"], "tocan_odgovor": 1, "obasnjenje": "On naziva od koliko se dijelova sastoji cijelo." },
    { "id": 53, "semester": 2, "pitanje": "Što označava razlomačka crta?", "opcije": ["Zbrajanje", "Dijeljenje", "Množenje", "Oduzimanje"], "tocan_odgovor": 1, "obasnjenje": "Razlomak je zapravo operacija dijeljenja." },
    { "id": 54, "semester": 2, "pitanje": "Koji je razlomak veći: 1/4 ili 3/4?", "opcije": ["Nijedan", "Jednaki su", "3/4", "1/4"], "tocan_odgovor": 2, "obasnjenje": "Ako su nazivnici isti, veći je onaj s većim brojnikom." },
    { "id": 55, "semester": 2, "pitanje": "Koliko je 1/5 + 2/5?", "opcije": ["1/5", "3/5", "1", "3/10"], "tocan_odgovor": 1, "obasnjenje": "Zbrajamo samo brojnike." },
    { "id": 56, "semester": 2, "pitanje": "Koliko je 7/10 - 3/10?", "opcije": ["4/20", "10/10", "4/10", "1"], "tocan_odgovor": 2, "obasnjenje": "Oduzimamo brojnike, nazivnik ostaje isti." },
    { "id": 57, "semester": 2, "pitanje": "Razlomak 1/2 u decimalnom zapisu je:", "opcije": ["0.5", "0.12", "0.2", "1.2"], "tocan_odgovor": 0, "obasnjenje": "Polovina je 0.5." },
    { "id": 58, "semester": 2, "pitanje": "Razlomak 1/4 u decimalnom zapisu je:", "opcije": ["0.4", "4.0", "0.14", "0.25"], "tocan_odgovor": 3, "obasnjenje": "Četvrtina je 0.25." },
    { "id": 59, "semester": 2, "pitanje": "Kako zapisujemo pet desetinki decimalno?", "opcije": ["5.10", "0.05", "0.5", "5.0"], "tocan_odgovor": 2, "obasnjenje": "Prvo mjesto desno od zareza su desetinke." },
    { "id": 60, "semester": 2, "pitanje": "Koji je broj veći: 0.5 ili 0.05?", "opcije": ["Ništa", "0.5", "Jednaki su", "0.05"], "tocan_odgovor": 1, "obasnjenje": "0.5 je isto što i 0.50." },
    { "id": 61, "semester": 2, "pitanje": "Zbroji: 0.2 + 0.3", "opcije": ["5.0", "0.05", "0.5", "1.0"], "tocan_odgovor": 2, "obasnjenje": "2 desetinke + 3 desetinke = 5 desetinki." },
    { "id": 62, "semester": 2, "pitanje": "Zbroji: 1.5 + 2.5", "opcije": ["4.5", "5", "3", "4"], "tocan_odgovor": 3, "obasnjenje": "1+2=3, 0.5+0.5=1, ukupno 4." },
    { "id": 63, "semester": 2, "pitanje": "Oduzmi: 1 - 0.3", "opcije": ["1.3", "0.6", "0.7", "0.3"], "tocan_odgovor": 2, "obasnjenje": "Jedno cijelo minus tri desetinke je sedam desetinki." },
    { "id": 64, "semester": 2, "pitanje": "Koliko je 0.1 ⋅ 10?", "opcije": ["0.01", "10", "0.1", "1"], "tocan_odgovor": 3, "obasnjenje": "Zarez se pomiče udesno za jedno mjesto." },
    { "id": 65, "semester": 2, "pitanje": "Koliko je 5.5 : 10?", "opcije": ["5.50", "55", "5", "0.55"], "tocan_odgovor": 3, "obasnjenje": "Zarez se pomiče ulijevo za jedno mjesto." },
    { "id": 66, "semester": 2, "pitanje": "U broju 12.34, koja je znamenka na mjestu desetinki?", "opcije": ["2", "3", "1", "4"], "tocan_odgovor": 1, "obasnjenje": "Prva znamenka nakon zareza." },
    { "id": 67, "semester": 2, "pitanje": "U broju 7.89, koja je znamenka na mjestu stotinki?", "opcije": ["9", "0", "7", "8"], "tocan_odgovor": 0, "obasnjenje": "Druga znamenka nakon zareza." },
    { "id": 68, "semester": 2, "pitanje": "Zaokruži 4.56 na jednu decimalu:", "opcije": ["4.0", "4.5", "4.6", "5"], "tocan_odgovor": 2, "obasnjenje": "Jer je stotinka 6 (što je 5 ili više), desetinka se povećava." },
    { "id": 69, "semester": 2, "pitanje": "Što je osna simetrija?", "opcije": ["Preslikavanje preko pravca (osi)", "Smanjivanje lika", "Preslikavanje preko točke", "Rotacija"], "tocan_odgovor": 0, "obasnjenje": "Likovi se zrcale preko pravca." },
    { "id": 70, "semester": 2, "pitanje": "Koliko simetrala ima kvadrat?", "opcije": ["2", "Beskonačno", "4", "1"], "tocan_odgovor": 2, "obasnjenje": "Dvije preko vrhova i dvije preko polovišta stranica." },
    { "id": 71, "semester": 2, "pitanje": "Koliko simetrala ima kružnica?", "opcije": ["1", "4", "Beskonačno", "2"], "tocan_odgovor": 2, "obasnjenje": "Svaki pravac kroz središte je os simetrije." },
    { "id": 72, "semester": 1, "pitanje": "Pravokutnik s svim jednakim stranicama zove se:", "opcije": ["Krug", "Romb", "Kvadrat", "Trokut"], "tocan_odgovor": 2, "obasnjenje": "Definicija kvadrata." },
    { "id": 73, "semester": 2, "pitanje": "Ako je opseg kvadrata 20 cm, kolika mu je stranica?", "opcije": ["4 cm", "10 cm", "5 cm", "20 cm"], "tocan_odgovor": 2, "obasnjenje": "20 podijeljeno s 4 je 5." },
    { "id": 74, "semester": 2, "pitanje": "Ako su stranice pravokutnika 3 cm i 4 cm, kolika mu je površina?", "opcije": ["14 cm²", "12 cm²", "7 cm²", "10 cm²"], "tocan_odgovor": 1, "obasnjenje": "3 puta 4 je 12." },
    { "id": 75, "semester": 2, "pitanje": "Koji kut je veći od pravog kuta?", "opcije": ["Svi su isti", "Nijedan", "Tupi", "Oštri"], "tocan_odgovor": 2, "obasnjenje": "Tupi kut ima više od 90 stupnjeva." },
    { "id": 76, "semester": 1, "pitanje": "Kružnica je:", "opcije": ["Bilo kakva crta", "Skup svih točaka ravnine jednako udaljenih od točke S", "Ploha omeđena krugom", "Točka"], "tocan_odgovor": 1, "obasnjenje": "Definicija kružnice." },
    { "id": 77, "semester": 2, "pitanje": "Udaljenost točke na kružnici od središta zove se:", "opcije": ["Radijus (polumjer)", "Tetiva", "Luk", "Promjer"], "tocan_odgovor": 0, "obasnjenje": "Označava se s r." },
    { "id": 78, "semester": 2, "pitanje": "Dvaput veći od radijusa je:", "opcije": ["Promjer", "Kut", "Opseg", "Površina"], "tocan_odgovor": 0, "obasnjenje": "Promjer spaja dvije točke kružnice kroz središte." },
    { "id": 79, "semester": 2, "pitanje": "Koji je rezultat 10²?", "opcije": ["10", "1000", "20", "100"], "tocan_odgovor": 3, "obasnjenje": "10 puta 10 je 100." },
    { "id": 80, "semester": 2, "pitanje": "Koji je rezultat 2³?", "opcije": ["6", "8", "4", "16"], "tocan_odgovor": 1, "obasnjenje": "2 puta 2 puta 2 je 8." },
    { "id": 81, "semester": 1, "pitanje": "Marko ima 5 jabuka, a Ana 3 puta više. Koliko ima Ana?", "opcije": ["8", "12", "10", "15"], "tocan_odgovor": 3, "obasnjenje": "5 puta 3." },
    { "id": 82, "semester": 1, "pitanje": "U razredu je 24 učenika, polovica su dječaci. Koliko je djevojčica?", "opcije": ["12", "6", "14", "10"], "tocan_odgovor": 0, "obasnjenje": "Pola od 24 je 12." },
    { "id": 83, "semester": 1, "pitanje": "Pravokutnik ima stranice 2 cm i 5 cm. Koliki mu je opseg?", "opcije": ["20 cm", "7 cm", "10 cm", "14 cm"], "tocan_odgovor": 3, "obasnjenje": "2+2+5+5 = 14." },
    { "id": 84, "semester": 1, "pitanje": "Izračunaj unutar zagrade prvo: 2 + 3 ⋅ 4", "opcije": ["14", "20", "24", "10"], "tocan_odgovor": 0, "obasnjenje": "Množenje ima prednost ako nema zagrada." },
    { "id": 85, "semester": 1, "pitanje": "Koji broj nedostaje: 15 + _ = 40?", "opcije": ["35", "25", "15", "20"], "tocan_odgovor": 1, "obasnjenje": "40 - 15 = 25." },
    { "id": 86, "semester": 1, "pitanje": "Auto vozi 60 km/h. Koliko će prijeći za 2 sata?", "opcije": ["120 km", "180 km", "100 km", "60 km"], "tocan_odgovor": 0, "obasnjenje": "60 puta 2." },
    { "id": 87, "semester": 1, "pitanje": "Koliko je 1000 - 1?", "opcije": ["900", "990", "999", "1001"], "tocan_odgovor": 2, "obasnjenje": "Prethodnik od 1000." },
    { "id": 88, "semester": 1, "pitanje": "Koji je broj djeljiv s 3 i s 5?", "opcije": ["10", "12", "15", "20"], "tocan_odgovor": 2, "obasnjenje": "Broj 15 je višekratnik oba broja." },
    { "id": 89, "semester": 2, "pitanje": "Zbroj kutova u trokutu je:", "opcije": ["90°", "0°", "180°", "360°"], "tocan_odgovor": 2, "obasnjenje": "Uvijek 180 stupnjeva." },
    { "id": 90, "semester": 2, "pitanje": "Kut alpha=40° i beta=50°. Njihov zbroj je:", "opcije": ["90°", "80°", "100°", "70°"], "tocan_odgovor": 0, "obasnjenje": "40 + 50." },
    { "id": 91, "semester": 2, "pitanje": "Zapiši 0.75 kao razlomak:", "opcije": ["1/4", "7/5", "1/2", "3/4"], "tocan_odgovor": 3, "obasnjenje": "Tri četvrtine je 0.75." },
    { "id": 92, "semester": 2, "pitanje": "Zbroji 1/2 + 1/2", "opcije": ["1", "2/2", "1/4", "1/2"], "tocan_odgovor": 0, "obasnjenje": "Dvije polovine čine jedno cijelo." },
    { "id": 93, "semester": 2, "pitanje": "Što je veće: 0.1 ili 0.11?", "opcije": ["Možda", "0.1", "Jednaki su", "0.11"], "tocan_odgovor": 3, "obasnjenje": "0.11 ima više stotinki." },
    { "id": 94, "semester": 2, "pitanje": "Koliko je 0.5 + 0.5?", "opcije": ["0.10", "0.55", "1.0", "1.5"], "tocan_odgovor": 2, "obasnjenje": "5 desetinki plus 5 desetinki je 10 desetinki ili jedno cijelo." },
    { "id": 95, "semester": 2, "pitanje": "Koliko je 10 : 0.1?", "opcije": ["10", "1", "0.1", "100"], "tocan_odgovor": 3, "obasnjenje": "Dijeljenje s 0.1 je kao množenje s 10." },
    { "id": 96, "semester": 2, "pitanje": "Opseg trokuta s stranicama 3, 4 i 5 je:", "opcije": ["7", "15", "60", "12"], "tocan_odgovor": 3, "obasnjenje": "3+4+5." },
    { "id": 97, "semester": 2, "pitanje": "Ako je površina kvadrata 16, kolika mu je stranica?", "opcije": ["8", "16", "4", "2"], "tocan_odgovor": 2, "obasnjenje": "4 puta 4 je 16." },
    { "id": 98, "semester": 2, "pitanje": "Koji je od ovih brojeva decimalni broj?", "opcije": ["1/2", "2.5", "100", "5"], "tocan_odgovor": 1, "obasnjenje": "Brojevi s decimalnom točkom (zarezom)." },
    { "id": 99, "semester": 2, "pitanje": "Zbroj 0.12 + 0.08 je:", "opcije": ["0.2", "0.1208", "0.20", "0.02"], "tocan_odgovor": 0, "obasnjenje": "12 stotinki + 8 stotinki = 20 stotinki = 0.2." },
    { "id": 100, "semester": 2, "pitanje": "Matematika je:", "opcije": ["Sve navedeno", "Teška", "Znanost o brojevima i oblicima", "Zabavna"], "tocan_odgovor": 2, "obasnjenje": "Osnovna definicija matematike." }
];
