const MAT_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Kako se zove rezultat zbrajanja?", "opcije": ["Razlika", "Suma", "Količnik", "Umnožak"], "tocan_odgovor": 1, "obasnjenje": "Rezultat zbroja zove se suma." },
    { "id": 2, "semester": 1, "pitanje": "Kako se zove rezultat oduzimanja?", "opcije": ["Suma", "Količnik", "Razlika", "Umnožak"], "tocan_odgovor": 2, "obasnjenje": "Rezultat oduzimanja zove se razlika." },
    { "id": 3, "semester": 1, "pitanje": "Kako se zove rezultat množenja?", "opcije": ["Razlika", "Količnik", "Umnožak", "Suma"], "tocan_odgovor": 2, "obasnjenje": "Rezultat množenja zove se umnožak." },
    { "id": 4, "semester": 1, "pitanje": "Kako se zove rezultat dijeljenja?", "opcije": ["Količnik", "Umnožak", "Razlika", "Suma"], "tocan_odgovor": 0, "obasnjenje": "Rezultat dijeljenja zove se količnik." },
    { "id": 5, "semester": 1, "pitanje": "Koji je najmanji prirodni broj?", "opcije": ["1", "10", "Ne postoji", "0"], "tocan_odgovor": 0, "obasnjenje": "Najmanji prirodni broj je 1." },
    { "id": 6, "semester": 1, "pitanje": "Je li broj 0 prirodni broj?", "opcije": ["Da", "Ovisi o državi", "Samo ponekad", "Ne"], "tocan_odgovor": 3, "obasnjenje": "Prirodni brojevi počinju od 1." },
    { "id": 7, "semester": 1, "pitanje": "Koji je broj neposredni sljedbenik broja 999?", "opcije": ["1001", "1000", "998", "990"], "tocan_odgovor": 1, "obasnjenje": "999 + 1 = 1000." },
    { "id": 8, "semester": 1, "pitanje": "Koji je broj neposredni prethodnik broja 100?", "opcije": ["101", "99", "90", "0"], "tocan_odgovor": 1, "obasnjenje": "100 - 1 = 99." },
    { "id": 9, "semester": 1, "pitanje": "Izračunaj: 125 + 75", "opcije": ["190", "225", "200", "210"], "tocan_odgovor": 2, "obasnjenje": "125 + 75 = 200." },
    { "id": 10, "semester": 1, "pitanje": "Izračunaj: 300 - 125", "opcije": ["185", "275", "175", "150"], "tocan_odgovor": 2, "obasnjenje": "300 - 125 = 175." },
    { "id": 11, "semester": 1, "pitanje": "Koliko je 15 ⋅ 4?", "opcije": ["60", "70", "45", "50"], "tocan_odgovor": 0, "obasnjenje": "15 puta 4 je 60." },
    { "id": 12, "semester": 1, "pitanje": "Koliko je 100 : 4?", "opcije": ["20", "50", "25", "10"], "tocan_odgovor": 2, "obasnjenje": "100 podijeljeno s 4 je 25." },
    { "id": 13, "semester": 1, "pitanje": "Koji je rezultat operacije 0 ⋅ 55?", "opcije": ["1", "Beskonačno", "55", "0"], "tocan_odgovor": 3, "obasnjenje": "Sve pomnoženo s nulom je nula." },
    { "id": 14, "semester": 1, "pitanje": "Je li dijeljenje s nulom moguće?", "opcije": ["Ponekad", "Ne", "Da", "Samo u geometriji"], "tocan_odgovor": 1, "obasnjenje": "Dijeljenje s nulom nije definirano u matematici." },
    { "id": 15, "semester": 1, "pitanje": "Koji broj dobijemo ako 45 zbrojimo s 0?", "opcije": ["450", "90", "45", "0"], "tocan_odgovor": 2, "obasnjenje": "Nula je neutralni element za zbrajanje." },
    { "id": 16, "semester": 1, "pitanje": "Koliko je 72 : 8?", "opcije": ["7", "8", "10", "9"], "tocan_odgovor": 3, "obasnjenje": "9 puta 8 je 72." },
    { "id": 17, "semester": 1, "pitanje": "Broj je djeljiv s 2 ako mu je zadnja znamenka:", "opcije": ["Bilo koja", "Uvijek 0", "Parna", "Neparna"], "tocan_odgovor": 2, "obasnjenje": "Parna znamenka (0,2,4,6,8) znači djeljivost s 2." },
    { "id": 18, "semester": 1, "pitanje": "Koji je od ovih brojeva djeljiv s 5?", "opcije": ["101", "45", "34", "26"], "tocan_odgovor": 1, "obasnjenje": "Brojevi djeljivi s 5 završavaju na 0 ili 5." },
    { "id": 19, "semester": 1, "pitanje": "Broj je djeljiv s 10 ako mu je zadnja znamenka:", "opcije": ["0", "1", "5", "Parna"], "tocan_odgovor": 0, "obasnjenje": "Broj je djeljiv s 10 ako završava s 0." },
    { "id": 20, "semester": 1, "pitanje": "Broj je djeljiv s 5 ako mu je zadnja znamenka:", "opcije": ["0 ili 5", "Parna", "Samo 0", "Samo 5"], "tocan_odgovor": 0, "obasnjenje": "Pravilo djeljivosti s 5." },
    { "id": 21, "semester": 1, "pitanje": "Koji je od ovih brojeva prost broj?", "opcije": ["9", "7", "4", "6"], "tocan_odgovor": 1, "obasnjenje": "7 je djeljiv samo s 1 i sa samim sobom." },
    { "id": 22, "semester": 1, "pitanje": "Što su prosti brojevi?", "opcije": ["Brojevi djeljivi s 2", "Brojevi veći od 100", "Brojevi koji imaju samo 2 djelitelja (1 i samog sebe)", "Neparni brojevi"], "tocan_odgovor": 2, "obasnjenje": "Definicija prostih brojeva." },
    { "id": 23, "semester": 1, "pitanje": "Je li broj 1 prost broj?", "opcije": ["Ne", "Da", "Samo u matematici", "Ponekad"], "tocan_odgovor": 0, "obasnjenje": "1 nije ni prost ni složen broj." },
    { "id": 24, "semester": 1, "pitanje": "Koji je jedini parni prost broj?", "opcije": ["2", "4", "1", "10"], "tocan_odgovor": 0, "obasnjenje": "2 je jedinstven po tome što je paran i prost." },
    { "id": 25, "semester": 1, "pitanje": "Zbroj znamenaka broja 123 je:", "opcije": ["7", "6", "5", "3"], "tocan_odgovor": 1, "obasnjenje": "1+2+3=6." },
    { "id": 26, "semester": 1, "pitanje": "Broj je djeljiv s 3 ako mu je zbroj znamenaka djeljiv s:", "opcije": ["3", "9", "5", "2"], "tocan_odgovor": 0, "obasnjenje": "Pravilo djeljivosti s 3." },
    { "id": 27, "semester": 1, "pitanje": "Je li broj 123 djeljiv s 3?", "opcije": ["Ne", "Možda", "Da", "Samo petkom"], "tocan_odgovor": 2, "obasnjenje": "Jer mu je zbroj znamenaka 6, a 6 je djeljivo s 3." },
    { "id": 28, "semester": 1, "pitanje": "Je li broj 450 djeljiv s 9?", "opcije": ["Da", "Ovisi o kutu", "Ne", "Samo ako je paran"], "tocan_odgovor": 0, "obasnjenje": "Zbroj znamenaka je 9, što je djeljivo s 9." },
    { "id": 29, "semester": 1, "pitanje": "Koji je najmanji zajednički višekratnik brojeva 4 i 6?", "opcije": ["24", "6", "12", "10"], "tocan_odgovor": 2, "obasnjenje": "Najmanji broj djeljiv s oba je 12." },
    { "id": 30, "semester": 1, "pitanje": "Koji je najveći zajednički djelitelj brojeva 12 i 18?", "opcije": ["2", "6", "12", "3"], "tocan_odgovor": 1, "obasnjenje": "6 je najveći broj koji dijeli oba." },
    { "id": 31, "semester": 1, "pitanje": "Dvije točke određuju točno jedan:", "opcije": ["Pravac", "Kut", "Kvadrat", "Trokut"], "tocan_odgovor": 0, "obasnjenje": "Kroz bilo koje dvije točke prolazi točno jedan pravac." },
    { "id": 32, "semester": 1, "pitanje": "Dio pravca omeđen dvjema točkama zove se:", "opcije": ["Zraka", "Dužina", "Točka", "Kružnica"], "tocan_odgovor": 1, "obasnjenje": "Dužina ima početnu i završnu točku." },
    { "id": 33, "semester": 1, "pitanje": "Koliko točaka ima pravac?", "opcije": ["Nijednu", "Jednu", "Dvije", "Beskonačno"], "tocan_odgovor": 3, "obasnjenje": "Pravac je skup beskonačno mnogo točaka." },
    { "id": 34, "semester": 1, "pitanje": "Pravci koji se nikada ne sijeku zovu se:", "opcije": ["Kosi", "Sječice", "Okomiti", "Usporedni (paralelni)"], "tocan_odgovor": 3, "obasnjenje": "Usporedni pravci leže u istoj ravnini i nemaju zajedničkih točaka." },
    { "id": 35, "semester": 1, "pitanje": "Pravci koji se sijeku pod pravim kutom zovu se:", "opcije": ["Tangente", "Okomiti", "Kosi", "Usporedni"], "tocan_odgovor": 1, "obasnjenje": "Okomiti pravci sijeku se pod 90 stupnjeva." },
    { "id": 36, "semester": 1, "pitanje": "Koji je simbol za okomitost?", "opcije": ["∥", "=", "Angle", "⊥"], "tocan_odgovor": 3, "obasnjenje": "⊥ je simbol za okomitost." },
    { "id": 37, "semester": 1, "pitanje": "Koji je simbol za usporednost?", "opcije": ["∥", "<", "≈", "⊥"], "tocan_odgovor": 0, "obasnjenje": "∥ je simbol za usporednost." },
    { "id": 38, "semester": 1, "pitanje": "Kako se zove kut od 90 stupnjeva?", "opcije": ["Pravi", "Oštri", "Tupi", "Ispruženi"], "tocan_odgovor": 0, "obasnjenje": "Pravi kut iznosi točno 90 stupnjeva." },
    { "id": 39, "semester": 1, "pitanje": "Kut manji od 90 stupnjeva je:", "opcije": ["Oštri", "Tupi", "Ispruženi", "Pravi"], "tocan_odgovor": 0, "obasnjenje": "Takav kut zovemo oštrim kutom." },
    { "id": 40, "semester": 1, "pitanje": "Kut veći od 90 stupnjeva, a manji od 180 stupnjeva je:", "opcije": ["Oštri", "Tupi", "Puni", "Pravi"], "tocan_odgovor": 1, "obasnjenje": "Takav kut zovemo tupim kutom." },
    { "id": 41, "semester": 1, "pitanje": "Kako se zove kut od 180 stupnjeva?", "opcije": ["Puni", "Tupi", "Pravi", "Ispruženi"], "tocan_odgovor": 3, "obasnjenje": "Ispruženi kut iznosi 180 stupnjeva." },
    { "id": 42, "semester": 1, "pitanje": "Koliko stupnjeva ima puni kut?", "opcije": ["90", "0", "360", "180"], "tocan_odgovor": 2, "obasnjenje": "Puni krug ima 360 stupnjeva." },
    { "id": 43, "semester": 1, "pitanje": "Opseg pravokutnika s stranicama a i b računa se:", "opcije": ["2 ⋅ (a + b)", "a ⋅ b", "a + b", "a²"], "tocan_odgovor": 0, "obasnjenje": "Formula: O = 2a + 2b." },
    { "id": 44, "semester": 1, "pitanje": "Površina pravokutnika s stranicama a i b računa se:", "opcije": ["a²", "2 ⋅ (a + b)", "a ⋅ b", "a + b"], "tocan_odgovor": 2, "obasnjenje": "Formula: P = a ⋅ b." },
    { "id": 45, "semester": 1, "pitanje": "Opseg kvadrata stranice a je:", "opcije": ["a + a", "4 ⋅ a", "a ⋅ a", "a²"], "tocan_odgovor": 1, "obasnjenje": "Formula: O = 4a." },
    { "id": 46, "semester": 1, "pitanje": "Površina kvadrata stranice a je:", "opcije": ["a ⋅ a (a²)", "4 ⋅ a", "2 ⋅ a", "a + 4"], "tocan_odgovor": 0, "obasnjenje": "Formula: P = a ⋅ a." },
    { "id": 47, "semester": 1, "pitanje": "Koliko mm ima jedan centimetar (1 cm)?", "opcije": ["5", "10", "100", "1000"], "tocan_odgovor": 1, "obasnjenje": "1 cm = 10 mm." },
    { "id": 48, "semester": 1, "pitanje": "Koliko cm ima jedan metar (1 m)?", "opcije": ["1000", "100", "60", "10"], "tocan_odgovor": 1, "obasnjenje": "1 m = 100 cm." },
    { "id": 49, "semester": 1, "pitanje": "Koliko metara ima jedan kilometar (1 km)?", "opcije": ["100", "1000", "500", "10000"], "tocan_odgovor": 1, "obasnjenje": "1 km = 1000 m." },
    { "id": 50, "semester": 1, "pitanje": "Jedinica za površinu je:", "opcije": ["m", "m³", "kg", "m²"], "tocan_odgovor": 3, "obasnjenje": "Površina se mjeri u kvadratnim jedinicama." },
    { "id": 51, "semester": 2, "pitanje": "Što predstavlja gornji broj u razlomku?", "opcije": ["Brojnik", "Razlomačka crta", "Nazivnik", "Cijeli dio"], "tocan_odgovor": 0, "obasnjenje": "On broji dijelove." },
    { "id": 52, "semester": 2, "pitanje": "Što predstavlja donji broj u razlomku?", "opcije": ["Brojnik", "Razlomačka crta", "Nazivnik", "Količnik"], "tocan_odgovor": 2, "obasnjenje": "On naziva od koliko se dijelova sastoji cijelo." },
    { "id": 53, "semester": 2, "pitanje": "Što označava razlomačka crta?", "opcije": ["Množenje", "Dijeljenje", "Oduzimanje", "Zbrajanje"], "tocan_odgovor": 1, "obasnjenje": "Razlomak je zapravo operacija dijeljenja." },
    { "id": 54, "semester": 2, "pitanje": "Koji je razlomak veći: 1 / 4 ili 3 / 4?", "opcije": ["3 / 4", "1 / 4", "Nijedan", "Jednaki su"], "tocan_odgovor": 0, "obasnjenje": "Ako su nazivnici isti, veći je onaj s većim brojnikom." },
    { "id": 55, "semester": 2, "pitanje": "Koliko je 1 / 5 + 2 / 5?", "opcije": ["3 / 10", "3 / 5", "1", "1 / 5"], "tocan_odgovor": 1, "obasnjenje": "Zbrajamo samo brojnike." },
    { "id": 56, "semester": 2, "pitanje": "Koliko je 7 / 10 - 3 / 10?", "opcije": ["1", "10 / 10", "4 / 20", "4 / 10"], "tocan_odgovor": 3, "obasnjenje": "Oduzimamo brojnike, nazivnik ostaje isti." },
    { "id": 57, "semester": 2, "pitanje": "Razlomak 1 / 2 u decimalnom zapisu je:", "opcije": ["0,2", "0,12", "0,5", "1,2"], "tocan_odgovor": 2, "obasnjenje": "Polovina je 0,5." },
    { "id": 58, "semester": 2, "pitanje": "Razlomak 1 / 4 u decimalnom zapisu je:", "opcije": ["4,0", "0,25", "0,4", "0,14"], "tocan_odgovor": 1, "obasnjenje": "Četvrtina je 0,25." },
    { "id": 59, "semester": 2, "pitanje": "Kako zapisujemo pet desetinki decimalno?", "opcije": ["5,10", "0,05", "5,0", "0,5"], "tocan_odgovor": 3, "obasnjenje": "Prvo mjesto desno od zareza su desetinke." },
    { "id": 60, "semester": 2, "pitanje": "Koji je broj veći: 0,5 ili 0,05?", "opcije": ["Jednaki su", "Ništa", "0,5", "0,05"], "tocan_odgovor": 2, "obasnjenje": "0,5 je isto što i 0,50." },
    { "id": 61, "semester": 2, "pitanje": "Zbroji: 0,2 + 0,3", "opcije": ["0,05", "5,0", "0,5", "1,0"], "tocan_odgovor": 2, "obasnjenje": "2 desetinke + 3 desetinke = 5 desetinki." },
    { "id": 62, "semester": 2, "pitanje": "Zbroji: 1,5 + 2,5", "opcije": ["4,5", "3", "5", "4"], "tocan_odgovor": 3, "obasnjenje": "1+2=3, 0,5+0,5=1, ukupno 4." },
    { "id": 63, "semester": 2, "pitanje": "Oduzmi: 1 - 0,3", "opcije": ["0,3", "1,3", "0,7", "0,6"], "tocan_odgovor": 2, "obasnjenje": "Jedno cijelo minus tri desetinke je sedam desetinki." },
    { "id": 64, "semester": 2, "pitanje": "Koliko je 0,1 ⋅ 10?", "opcije": ["0,01", "0,1", "1", "10"], "tocan_odgovor": 2, "obasnjenje": "Zarez se pomiče udesno za jedno mjesto." },
    { "id": 65, "semester": 2, "pitanje": "Koliko je 5,5 : 10?", "opcije": ["5", "0,55", "55", "5,50"], "tocan_odgovor": 1, "obasnjenje": "Zarez se pomiče ulijevo za jedno mjesto." },
    { "id": 66, "semester": 2, "pitanje": "U broju 12,34, koja je znamenka na mjestu desetinki?", "opcije": ["3", "1", "2", "4"], "tocan_odgovor": 0, "obasnjenje": "Prva znamenka nakon zareza." },
    { "id": 67, "semester": 2, "pitanje": "U broju 7,89, koja je znamenka na mjestu stotinki?", "opcije": ["8", "0", "9", "7"], "tocan_odgovor": 2, "obasnjenje": "Druga znamenka nakon zareza." },
    { "id": 68, "semester": 2, "pitanje": "Zaokruži 4,56 na jednu decimalu:", "opcije": ["5", "4,5", "4,0", "4,6"], "tocan_odgovor": 3, "obasnjenje": "Jer je stotinka 6 (što je 5 ili više), desetinka se povećava." },
    { "id": 69, "semester": 2, "pitanje": "Što je osna simetrija?", "opcije": ["Preslikavanje preko točke", "Preslikavanje preko pravca (osi)", "Rotacija", "Smanjivanje lika"], "tocan_odgovor": 1, "obasnjenje": "Likovi se zrcale preko pravca." },
    { "id": 70, "semester": 2, "pitanje": "Koliko simetrala ima kvadrat?", "opcije": ["2", "1", "Beskonačno", "4"], "tocan_odgovor": 3, "obasnjenje": "Dvije preko vrhova i dvije preko polovišta stranica." },
    { "id": 71, "semester": 2, "pitanje": "Koliko simetrala ima kružnica?", "opcije": ["4", "2", "Beskonačno", "1"], "tocan_odgovor": 2, "obasnjenje": "Svaki pravac kroz središte je os simetrije." },
    { "id": 72, "semester": 1, "pitanje": "Pravokutnik s svim jednakim stranicama zove se:", "opcije": ["Romb", "Trokut", "Krug", "Kvadrat"], "tocan_odgovor": 3, "obasnjenje": "Definicija kvadrata." },
    { "id": 73, "semester": 2, "pitanje": "Ako je opseg kvadrata 20 cm, kolika mu je stranica?", "opcije": ["5 cm", "20 cm", "4 cm", "10 cm"], "tocan_odgovor": 0, "obasnjenje": "20 podijeljeno s 4 je 5." },
    { "id": 74, "semester": 2, "pitanje": "Ako su stranice pravokutnika 3 cm i 4 cm, kolika mu je površina?", "opcije": ["10 cm²", "12 cm²", "14 cm²", "7 cm²"], "tocan_odgovor": 1, "obasnjenje": "3 puta 4 je 12." },
    { "id": 75, "semester": 2, "pitanje": "Koji kut je veći od pravog kuta?", "opcije": ["Svi su isti", "Tupi", "Oštri", "Nijedan"], "tocan_odgovor": 1, "obasnjenje": "Tupi kut ima više od 90 stupnjeva." },
    { "id": 76, "semester": 1, "pitanje": "Kružnica je:", "opcije": ["Točka", "Bilo kakva crta", "Skup svih točaka ravnine jednako udaljenih od točke S", "Ploha omeđena krugom"], "tocan_odgovor": 2, "obasnjenje": "Definicija kružnice." },
    { "id": 77, "semester": 2, "pitanje": "Udaljenost točke na kružnici od središta zove se:", "opcije": ["Tetiva", "Luk", "Radijus (polumjer)", "Promjer"], "tocan_odgovor": 2, "obasnjenje": "Označava se s r." },
    { "id": 78, "semester": 2, "pitanje": "Dvaput veći od radijusa je:", "opcije": ["Površina", "Promjer", "Kut", "Opseg"], "tocan_odgovor": 1, "obasnjenje": "Promjer spaja dvije točke kružnice kroz središte." },
    { "id": 79, "semester": 2, "pitanje": "Koji je rezultat 10²?", "opcije": ["20", "1000", "100", "10"], "tocan_odgovor": 2, "obasnjenje": "10 puta 10 je 100." },
    { "id": 80, "semester": 2, "pitanje": "Koji je rezultat 2³?", "opcije": ["16", "6", "4", "8"], "tocan_odgovor": 3, "obasnjenje": "2 puta 2 puta 2 je 8." },
    { "id": 81, "semester": 1, "pitanje": "Marko ima 5 jabuka, a Ana 3 puta više. Koliko ima Ana?", "opcije": ["12", "10", "8", "15"], "tocan_odgovor": 3, "obasnjenje": "5 puta 3." },
    { "id": 82, "semester": 1, "pitanje": "U razredu je 24 učenika, polovica su dječaci. Koliko je djevojčica?", "opcije": ["14", "12", "6", "10"], "tocan_odgovor": 1, "obasnjenje": "Pola od 24 je 12." },
    { "id": 83, "semester": 1, "pitanje": "Pravokutnik ima stranice 2 cm i 5 cm. Koliki mu je opseg?", "opcije": ["7 cm", "14 cm", "20 cm", "10 cm"], "tocan_odgovor": 1, "obasnjenje": "2+2+5+5 = 14." },
    { "id": 84, "semester": 1, "pitanje": "Izračunaj unutar zagrade prvo: 2 + 3 ⋅ 4", "opcije": ["14", "24", "10", "20"], "tocan_odgovor": 0, "obasnjenje": "Množenje ima prednost ako nema zagrada." },
    { "id": 85, "semester": 1, "pitanje": "Koji broj nedostaje: 15 + _ = 40?", "opcije": ["15", "35", "20", "25"], "tocan_odgovor": 3, "obasnjenje": "40 - 15 = 25." },
    { "id": 86, "semester": 1, "pitanje": "Auto vozi 60 km/h. Koliko će prijeći za 2 sata?", "opcije": ["100 km", "120 km", "180 km", "60 km"], "tocan_odgovor": 1, "obasnjenje": "60 puta 2." },
    { "id": 87, "semester": 1, "pitanje": "Koliko je 1000 - 1?", "opcije": ["900", "1001", "999", "990"], "tocan_odgovor": 2, "obasnjenje": "Prethodnik od 1000." },
    { "id": 88, "semester": 1, "pitanje": "Koji je broj djeljiv s 3 i s 5?", "opcije": ["12", "15", "20", "10"], "tocan_odgovor": 1, "obasnjenje": "Broj 15 je višekratnik oba broja." },
    { "id": 89, "semester": 2, "pitanje": "Zbroj kutova u trokutu je:", "opcije": ["0°", "360°", "90°", "180°"], "tocan_odgovor": 3, "obasnjenje": "Uvijek 180 stupnjeva." },
    { "id": 90, "semester": 2, "pitanje": "Kut alpha=40° i beta=50°. Njihov zbroj je:", "opcije": ["100°", "80°", "90°", "70°"], "tocan_odgovor": 2, "obasnjenje": "40 + 50." },
    { "id": 91, "semester": 2, "pitanje": "Zapiši 0,75 kao razlomak:", "opcije": ["7 / 5", "1 / 2", "3 / 4", "1 / 4"], "tocan_odgovor": 2, "obasnjenje": "Tri četvrtine je 0,75." },
    { "id": 92, "semester": 2, "pitanje": "Zbroji 1 / 2 + 1 / 2", "opcije": ["1", "1 / 4", "1 / 2", "2 / 2"], "tocan_odgovor": 0, "obasnjenje": "Dvije polovine čine jedno cijelo." },
    { "id": 93, "semester": 2, "pitanje": "Što je veće: 0,1 ili 0,11?", "opcije": ["Jednaki su", "0,1", "Možda", "0,11"], "tocan_odgovor": 3, "obasnjenje": "0,11 ima više stotinki." },
    { "id": 94, "semester": 2, "pitanje": "Koliko je 0,5 + 0,5?", "opcije": ["0,55", "1,0", "0,10", "1,5"], "tocan_odgovor": 1, "obasnjenje": "5 desetinki plus 5 desetinki je 10 desetinki ili jedno cijelo." },
    { "id": 95, "semester": 2, "pitanje": "Koliko je 10 : 0,1?", "opcije": ["100", "10", "0,1", "1"], "tocan_odgovor": 0, "obasnjenje": "Dijeljenje s 0,1 je kao množenje s 10." },
    { "id": 96, "semester": 2, "pitanje": "Opseg trokuta s stranicama 3, 4 i 5 je:", "opcije": ["12", "7", "60", "15"], "tocan_odgovor": 0, "obasnjenje": "3+4+5." },
    { "id": 97, "semester": 2, "pitanje": "Ako je površina kvadrata 16, kolika mu je stranica?", "opcije": ["4", "8", "16", "2"], "tocan_odgovor": 0, "obasnjenje": "4 puta 4 je 16." },
    { "id": 98, "semester": 2, "pitanje": "Koji je od ovih brojeva decimalni broj?", "opcije": ["100", "2,5", "5", "1 / 2"], "tocan_odgovor": 1, "obasnjenje": "Brojevi s decimalnom točkom (zarezom)." },
    { "id": 99, "semester": 2, "pitanje": "Zbroj 0,12 + 0,08 je:", "opcije": ["0,2", "0,02", "0,20", "0,1208"], "tocan_odgovor": 0, "obasnjenje": "12 stotinki + 8 stotinki = 20 stotinki = 0,2." },
    { "id": 100, "semester": 2, "pitanje": "Matematika je:", "opcije": ["Zabavna", "Znanost o brojevima i oblicima", "Sve navedeno", "Teška"], "tocan_odgovor": 1, "obasnjenje": "Osnovna definicija matematike." }
];
