const PRI_5_DATA = [
    { "id": 1, "semester": 1, "pitanje": "Što je priroda?", "opcije": ["Gradovi i prometnice", "Samo biljke i životinje", "Samo planine i mora", "Sve što nas okružuje bez utjecaja čovjeka"], "tocan_odgovor": 3, "obasnjenje": "Priroda obuhvaća živu i neživu prirodu." },
    { "id": 2, "semester": 1, "pitanje": "Koja znanost proučava prirodu u cjelini?", "opcije": ["Prirodoslovlje", "Povijest", "Matematika", "Geografija"], "tocan_odgovor": 0, "obasnjenje": "Skupna znanost o prirodi." },
    { "id": 3, "semester": 1, "pitanje": "Što od navedenog pripada živoj prirodi?", "opcije": ["Gljiva", "Kamen", "Voda", "Zrak"], "tocan_odgovor": 0, "obasnjenje": "Biljke, životinje, gljive i ljudi." },
    { "id": 4, "semester": 1, "pitanje": "Što od navedenog pripada neživoj prirodi?", "opcije": ["Hrast", "Sunčeva svjetlost", "Maslačak", "Vuk"], "tocan_odgovor": 1, "obasnjenje": "Sunce, voda, zrak i tlo." },
    { "id": 5, "semester": 1, "pitanje": "Kojim osjetilom prepoznajemo miris cvijeta?", "opcije": ["Kožom", "Očima", "Nosom", "Ušima"], "tocan_odgovor": 2, "obasnjenje": "Njuh (nos)." },
    { "id": 6, "semester": 1, "pitanje": "Kako nazivamo predviđanje rezultata nekog pokusa?", "opcije": ["Promatranje", "Zaključak", "Mjerenje", "Pretpostavka (hipoteza)"], "tocan_odgovor": 3, "obasnjenje": "Hipoteza se testira pokusom." },
    { "id": 7, "semester": 1, "pitanje": "Što je osnovna jedinica svih živih bića?", "opcije": ["Atom", "Molekula", "Stanica", "Organ"], "tocan_odgovor": 2, "obasnjenje": "Stanica je osnova života." },
    { "id": 8, "semester": 1, "pitanje": "Pomoću čega vidimo stanice?", "opcije": ["Lupe", "Teleskopa", "Mikroskopa", "Naočala"], "tocan_odgovor": 2, "obasnjenje": "Mikroskop za premalene objekte." },
    { "id": 9, "semester": 1, "pitanje": "Od čega su građene sve tvari?", "opcije": ["Od čestica", "Od vode", "Od stanica", "Od zraka"], "tocan_odgovor": 0, "obasnjenje": "Sve je građeno od sitnih čestica." },
    { "id": 10, "semester": 1, "pitanje": "Koja tvar se nalazi u sva tri stanja u prirodi?", "opcije": ["Voda", "Željezo", "Zlato", "Drvo"], "tocan_odgovor": 0, "obasnjenje": "Led, voda i para." },
    { "id": 11, "semester": 1, "pitanje": "Kako nazivamo prijelaz iz tekućeg u plinovito stanje?", "opcije": ["Zaleđivanje", "Isparavanje", "Topljenje", "Taloženje"], "tocan_odgovor": 1, "obasnjenje": "Isparavanje grijanjem tekućine." },
    { "id": 12, "semester": 1, "pitanje": "Što je energija?", "opcije": ["Sposobnost tijela da obavlja rad", "Samo struja", "Nešto što samo grije", "Vrsta hrane"], "tocan_odgovor": 0, "obasnjenje": "Energija pokreće procese." },
    { "id": 13, "semester": 1, "pitanje": "Koji je glavni izvor energije na Zemlji?", "opcije": ["Nafta", "Sunce", "Vjetar", "Baterije"], "tocan_odgovor": 1, "obasnjenje": "Sunce daje toplinu i svjetlost." },
    { "id": 14, "semester": 1, "pitanje": "Što rade biljke tijekom fotosinteze?", "opcije": ["Samo troše vodu", "Samo piju vodu", "Samo rastu", "Stvaraju hranu i kisik"], "tocan_odgovor": 3, "obasnjenje": "Fotosinteza stvara hranu." },
    { "id": 15, "semester": 1, "pitanje": "Gdje se u prirodi nalazi najviše vode?", "opcije": ["U oblacima", "U rijekama", "U jezerima", "U oceanima i morima"], "tocan_odgovor": 3, "obasnjenje": "97% je slana voda mora." },
    { "id": 16, "semester": 1, "pitanje": "Kakvog je okusa morska voda?", "opcije": ["Bez okusa", "Slana", "Slatka", "Gorka"], "tocan_odgovor": 1, "obasnjenje": "Zbog otopljenih soli." },
    { "id": 17, "semester": 1, "pitanje": "Što je zrak?", "opcije": ["Vodena para", "Čisti kisik", "Smjesa plinova", "Čisti dušik"], "tocan_odgovor": 2, "obasnjenje": "Najviše dušika i kisika." },
    { "id": 18, "semester": 1, "pitanje": "Koji plin iz zraka udišemo?", "opcije": ["Kisik", "Dušik", "Helij", "Ugljikov dioksid"], "tocan_odgovor": 0, "obasnjenje": "Neophodan za disanje stanica." },
    { "id": 19, "semester": 1, "pitanje": "Što je tlo?", "opcije": ["Površinski sloj Zemljine kore", "Samo pijesak", "Dno oceana", "Samo kamenje"], "tocan_odgovor": 0, "obasnjenje": "Nastaje trošenjem stijena." },
    { "id": 20, "semester": 1, "pitanje": "Koji organizmi razgrađuju ostatke bića u tlu?", "opcije": ["Biljke", "Razlagači", "Ptice", "Ljudi"], "tocan_odgovor": 1, "obasnjenje": "Bakterije i gljive vraćaju minerale." },
    { "id": 21, "semester": 1, "pitanje": "Što je ekosustav?", "opcije": ["Povezana živa bića i njihovo stanište", "Samo more", "Samo akvarij", "Samo šuma"], "tocan_odgovor": 0, "obasnjenje": "Živi i neživi dio zajedno." },
    { "id": 22, "semester": 1, "pitanje": "Primjer kojeg ekosustava je Bara?", "opcije": ["Kopnene vode stajaćice", "Kopnene vode tekućice", "More", "Pustinja"], "tocan_odgovor": 0, "obasnjenje": "Bare i jezera su stajaćice." },
    { "id": 23, "semester": 1, "pitanje": "Koja riba živi u rijekama?", "opcije": ["Morski pas", "Šaran", "Tuna", "Srdele"], "tocan_odgovor": 1, "obasnjenje": "Šaran je slatkovodna riba." },
    { "id": 24, "semester": 1, "pitanje": "Što je hranidbeni lanac?", "opcije": ["Prikaz tko koga jede u prirodi", "Popis kupovina", "Lanac od metala", "Vrsta igre"], "tocan_odgovor": 0, "obasnjenje": "Prenosi energiju kroz prirodu." },
    { "id": 25, "semester": 1, "pitanje": "Tko je na početku svakog hranidbenog lanca?", "opcije": ["Vuk", "Gljiva", "Zec", "Biljke (proizvođači)"], "tocan_odgovor": 3, "obasnjenje": "Biljke stvaraju hranu od Sunca." },
    { "id": 26, "semester": 1, "pitanje": "Koji instrument mjeri temperaturu?", "opcije": ["Vaga", "Termometar", "Metar", "Sat"], "tocan_odgovor": 1, "obasnjenje": "Mjerimo u Celzijevim stupnjevima." },
    { "id": 27, "semester": 1, "pitanje": "Što je pretvorba energije?", "opcije": ["Nestanak energije", "Samo struja", "Grijanje", "Promjena jednog oblika u drugi"], "tocan_odgovor": 3, "obasnjenje": "Energija ne nestaje." },
    { "id": 28, "semester": 1, "pitanje": "Što je otpad?", "opcije": ["Stvari koje nam više ne trebaju", "HRana", "Zlato", "Plastika"], "tocan_odgovor": 0, "obasnjenje": "Otpad moramo razvrstavati." },
    { "id": 29, "semester": 1, "pitanje": "Što je recikliranje?", "opcije": ["Bacanje u šumu", "Spremanje", "Spaljivanje", "Prerada starog otpada"], "tocan_odgovor": 3, "obasnjenje": "Čuvamo prirodu recikliranjem." },
    { "id": 30, "semester": 1, "pitanje": "Koje je boje spremnik za papir?", "opcije": ["Plave", "Zelene", "Smeđe", "Žute"], "tocan_odgovor": 0, "obasnjenje": "Plavi spremnik = papir." },
    { "id": 31, "semester": 1, "pitanje": "Što mjerimo menzurom?", "opcije": ["Duljinu", "Vrijeme", "Masu", "Obujam tekućine"], "tocan_odgovor": 3, "obasnjenje": "Menzura ima mjernu skalu." },
    { "id": 32, "semester": 1, "pitanje": "Što je masa tijela?", "opcije": ["Količina tvari u tijelu", "Veličina", "Duljina", "Boja"], "tocan_odgovor": 0, "obasnjenje": "Mjerimo vagom u kg/g." },
    { "id": 33, "semester": 1, "pitanje": "Koliko dugo Zemlja putuje oko Sunca?", "opcije": ["Godinu dana", "Mjesec", "Dan", "Tjedan"], "tocan_odgovor": 0, "obasnjenje": "Put duži od 365 dana." },
    { "id": 34, "semester": 1, "pitanje": "Što uzrokuje rotacija Zemlje oko svoje osi?", "opcije": ["Izmjenu dana i noći", "Izmjenu sezona", "Mrak", "Kišu"], "tocan_odgovor": 0, "obasnjenje": "Traje 24 sata." },
    { "id": 35, "semester": 1, "pitanje": "Što je horizont (obzor)?", "opcije": ["Kraj svijeta", "Linija spajanja neba i Zemlje", "Planina", "More"], "tocan_odgovor": 1, "obasnjenje": "Što smo više, obzor je širi." },
    { "id": 36, "semester": 1, "pitanje": "Strana svijeta nasuprot sjeveru?", "opcije": ["Jugoistok", "Zapad", "Istok", "Jug"], "tocan_odgovor": 3, "obasnjenje": "Glavne strane S-J i I-Z." },
    { "id": 37, "semester": 1, "pitanje": "Gdje Sunce izlazi?", "opcije": ["Na istoku", "Na sjeveru", "Na jugu", "Na zapadu"], "tocan_odgovor": 0, "obasnjenje": "Istok je strana izlaska Sunca." },
    { "id": 38, "semester": 1, "pitanje": "Što je kompas?", "opcije": ["Igračka", "Sat", "Hrana", "Uređaj za orijentaciju"], "tocan_odgovor": 3, "obasnjenje": "Magnetna igla pokazuje sjever." },
    { "id": 39, "semester": 1, "pitanje": "Mahovina na stablu raste na...", "opcije": ["Grani", "Sjevernoj strani", "Sunčanoj strani", "Južnoj strani"], "tocan_odgovor": 1, "obasnjenje": "Mahovina voli sjenu i vlagu." },
    { "id": 40, "semester": 1, "pitanje": "Što je geografska karta?", "opcije": ["Crtež", "Umanjeni prikaz površine", "Slika", "Stvarna veličina"], "tocan_odgovor": 1, "obasnjenje": "Pomaže snalaženju u prostoru." },
    { "id": 41, "semester": 1, "pitanje": "Što prikazuje mjerilo?", "opcije": ["Boje", "Koliko je stvarnost umanjena", "Visinu", "Dubinu"], "tocan_odgovor": 1, "obasnjenje": "Omjer na karti i u prirodi." },
    { "id": 42, "semester": 1, "pitanje": "Planine su na karti...", "opcije": ["Plave", "Smeđe", "Žute", "Zelene"], "tocan_odgovor": 1, "obasnjenje": "Smeđa označava visine." },
    { "id": 43, "semester": 1, "pitanje": "Nizine su visine do...", "opcije": ["5 km", "0 metara", "1000 metara", "200 metara"], "tocan_odgovor": 3, "obasnjenje": "Zelena boja na karti." },
    { "id": 44, "semester": 1, "pitanje": "Sva uzvišenja i udubljenja na tlu su...", "opcije": ["Reljef", "Karta", "Slika", "Ravnica"], "tocan_odgovor": 0, "obasnjenje": "Obuhvaća planine, doline itd." },
    { "id": 45, "semester": 1, "pitanje": "Glavni grad Hrvatske?", "opcije": ["Osijek", "Rijeka", "Zagreb", "Split"], "tocan_odgovor": 2, "obasnjenje": "Središte države." },
    { "id": 46, "semester": 1, "pitanje": "Kopno, more i zrak države je...", "opcije": ["Samo Zagreb", "Obala", "Samo more", "Državni prostor"], "tocan_odgovor": 3, "obasnjenje": "ČINI cjelinu RH." },
    { "id": 47, "semester": 1, "pitanje": "Broj županija u Hrvatskoj?", "opcije": ["5", "10", "50", "20 i Grad Zagreb"], "tocan_odgovor": 3, "obasnjenje": "Administrativna podjela RH." },
    { "id": 48, "semester": 1, "pitanje": "Boje hrvatske zastave?", "opcije": ["Plava i žuta", "Samo bijela", "Crven, bijeli, plavi", "Zelena"], "tocan_odgovor": 2, "obasnjenje": "Boje hrvatske trobojnice." },
    { "id": 49, "semester": 1, "pitanje": "Klima u nizinskoj Hrvatskoj?", "opcije": ["Umjereno topla vlažna", "Tropska", "Polarna", "Pustinjska"], "tocan_odgovor": 0, "obasnjenje": "Klima s 4 godišnja doba." },
    { "id": 50, "semester": 1, "pitanje": "Glavna djelatnost u nizinama?", "opcije": ["Rudarstvo", "Poljoprivreda", "Skijanje", "Pomorstvo"], "tocan_odgovor": 1, "obasnjenje": "Zbog plodnog tla i reljefa." },
    { "id": 51, "semester": 2, "pitanje": "Obilježja živih bića?", "opcije": ["Letenje", "Hrana, disanje, rast", "Samo san", "Samo igra"], "tocan_odgovor": 1, "obasnjenje": "Životni procesi svih bića." },
    { "id": 52, "semester": 2, "pitanje": "Prenošenje osobina na potomke?", "opcije": ["Poklon", "Nasljeđivanje", "Kupnja", "Učenje"], "tocan_odgovor": 1, "obasnjenje": "Razlog zašto sličimo roditeljima." },
    { "id": 53, "semester": 2, "pitanje": "Jednostanično biće je...", "opcije": ["Papučica", "Pas", "Čovjek", "Hrast"], "tocan_odgovor": 0, "obasnjenje": "Građeno od samo jedne stanice." },
    { "id": 54, "semester": 2, "pitanje": "Skupina sličnih stanica je...", "opcije": ["Organizam", "Tkivo", "Organ", "Sustav"], "tocan_odgovor": 1, "obasnjenje": "Tkiva obavljaju istu zadaću." },
    { "id": 55, "semester": 2, "pitanje": "Više tkiva skupa čine...", "opcije": ["Organ", "Tvar", "Sustav", "Stanicu"], "tocan_odgovor": 0, "obasnjenje": "Srce, jetra ili list su organi." },
    { "id": 56, "semester": 2, "pitanje": "Uloga kostura?", "opcije": ["Potpora i zaštita", "Razmišljanje", "Probava", "Disanje"], "tocan_odgovor": 0, "obasnjenje": "Kosti daju oblik tijelu." },
    { "id": 57, "semester": 2, "pitanje": "Kosti se spajaju u...", "opcije": ["Koži", "Zglobovima", "Mozgu", "Mišićima"], "tocan_odgovor": 1, "obasnjenje": "Omogućuju kretanje." },
    { "id": 58, "semester": 2, "pitanje": "Mišići nam služe za...", "opcije": ["Razmišljanje", "Pokretanje kostiju", "Probavu", "Ništa"], "tocan_odgovor": 1, "obasnjenje": "Stežu se i rastežu." },
    { "id": 59, "semester": 2, "pitanje": "Krvožilni sustav prenosi...", "opcije": ["Samo vodu", "Kisik i hranu", "Samo zrak", "Samo otpad"], "tocan_odgovor": 1, "obasnjenje": "Srce pumpa krv svuda." },
    { "id": 60, "semester": 2, "pitanje": "Ritam rada srca je...", "opcije": ["Šum", "Dah", "Puls (bilo)", "San"], "tocan_odgovor": 2, "obasnjenje": "Mjerimo na zapešću." },
    { "id": 61, "semester": 2, "pitanje": "Pluća služe za...", "opcije": ["Probavu", "Razmišljanje", "Kretanje", "Disanje"], "tocan_odgovor": 3, "obasnjenje": "Izmjena plinova." },
    { "id": 62, "semester": 2, "pitanje": "Probava služi za...", "opcije": ["Razgradnju hrane", "Hlađenje", "Spavanje", "Grijanje"], "tocan_odgovor": 0, "obasnjenje": "Pretvara hranu u energiju." },
    { "id": 63, "semester": 2, "pitanje": "Probava počinje u...", "opcije": ["Crijevu", "Želucu", "Ustima", "Grlu"], "tocan_odgovor": 2, "obasnjenje": "Zubi usitnjavaju hranu." },
    { "id": 64, "semester": 2, "pitanje": "Najveći organ tijela?", "opcije": ["Pluća", "Srce", "Jetra", "Koža"], "tocan_odgovor": 3, "obasnjenje": "Štiti nas od vanjskog svijeta." },
    { "id": 65, "semester": 2, "pitanje": "Živčani sustav...", "opcije": ["Samo diše", "Ništa", "Samo kuca", "Upravlja tijelom"], "tocan_odgovor": 3, "obasnjenje": "Mozak je glavni centar." },
    { "id": 66, "semester": 2, "pitanje": "Vid, sluh i njuh su...", "opcije": ["Kosti", "Mišići", "Osjetila", "Stanice"], "tocan_odgovor": 2, "obasnjenje": "Informiraju mozak." },
    { "id": 67, "semester": 2, "pitanje": "San djeteta treba trajati...", "opcije": ["1 sat", "20 sati", "2 sata", "9 do 10 sati"], "tocan_odgovor": 3, "obasnjenje": "Odmor i rast." },
    { "id": 68, "semester": 2, "pitanje": "Pranje ruku i zuba je...", "opcije": ["Geografija", "Šport", "Igra", "Osobna higijena"], "tocan_odgovor": 3, "obasnjenje": "Čuva nas od bolesti." },
    { "id": 69, "semester": 2, "pitanje": "Vitamine najviše dobivamo iz...", "opcije": ["Slatkiša", "Kruha", "Voća i povrća", "Mesa"], "tocan_odgovor": 2, "obasnjenje": "Jačaju imunitet." },
    { "id": 70, "semester": 2, "pitanje": "Zarazne bolesti uzrokuju...", "opcije": ["San", "Padovi", "Mikroorganizmi", "Smijeh"], "tocan_odgovor": 2, "obasnjenje": "Bakterije i virusi." },
    { "id": 71, "semester": 2, "pitanje": "Cijepljenje nas štiti od...", "opcije": ["Lomova", "Zaraza", "Gladi", "Žeđi"], "tocan_odgovor": 1, "obasnjenje": "Preventivna zaštita." },
    { "id": 72, "semester": 2, "pitanje": "Pušenje i alkohol su...", "opcije": ["Športovi", "Hrana", "Hobiji", "Štetne ovisnosti"], "tocan_odgovor": 3, "obasnjenje": "Uništavaju zdravlje." },
    { "id": 73, "semester": 2, "pitanje": "Razdoblje odrastanja je...", "opcije": ["Škola", "Rođendan", "Pubertet", "San"], "tocan_odgovor": 2, "obasnjenje": "Tjelesno dozrijevanje." },
    { "id": 74, "semester": 2, "pitanje": "Biljke se razmnožavaju...", "opcije": ["Disanjem", "Trčanjem", "Ništa", "Sjemenkama"], "tocan_odgovor": 3, "obasnjenje": "Nova biljka iz sjemena." },
    { "id": 75, "semester": 2, "pitanje": "Pelud na tučak prenosi...", "opcije": ["Sadnja", "Zalijevanje", "Rezanje", "Oprašivanje"], "tocan_odgovor": 3, "obasnjenje": "Pomažu pčele i vjetar." },
    { "id": 76, "semester": 1, "pitanje": "Pri naporu srce radi...", "opcije": ["Isto", "Stane", "Sporije", "Brže"], "tocan_odgovor": 3, "obasnjenje": "Treba nam više kisika." },
    { "id": 77, "semester": 2, "pitanje": "Životinja s kovanice?", "opcije": ["Kuna", "Vuk", "Lav", "Zec"], "tocan_odgovor": 0, "obasnjenje": "Prijašnja valuta RH." },
    { "id": 78, "semester": 2, "pitanje": "Nacionalni parkovi su...", "opcije": ["Gradovi", "Škole", "Prirodna baština", "Trgovine"], "tocan_odgovor": 2, "obasnjenje": "Zaštićeni dijelovi prirode." },
    { "id": 79, "semester": 2, "pitanje": "Plitvička jezera imaju...", "opcije": ["Nema jezera", "16 jezera", "100 jezera", "1 jezero"], "tocan_odgovor": 1, "obasnjenje": "Najpoznatiji park RH." },
    { "id": 80, "semester": 2, "pitanje": "Zimski san je...", "opcije": ["San ljeti", "Bolest", "Igra", "Prilagodba na hladnoću"], "tocan_odgovor": 3, "obasnjenje": "Štednja energije zimi." },
    { "id": 81, "semester": 1, "pitanje": "Štoperica mjeri...", "opcije": ["Temperaturu", "Duljinu", "Točno vrijeme", "Masu"], "tocan_odgovor": 2, "obasnjenje": "Trajanje aktivnosti." },
    { "id": 82, "semester": 2, "pitanje": "Stanovnik Jadrana je...", "opcije": ["Devva", "Slon", "Dobri dupin", "Tigar"], "tocan_odgovor": 2, "obasnjenje": "Zaštićeni morski sisavac." },
    { "id": 83, "semester": 2, "pitanje": "Provjetravanje daje...", "opcije": ["Muhe", "Svježi kisik", "Prašinu", "Hladnoću"], "tocan_odgovor": 1, "obasnjenje": "Izbacuje štetni CO2." },
    { "id": 84, "semester": 2, "pitanje": "Sve vrste na Zemlji čine...", "opcije": ["Bioraznolikost", "Samo šumu", "Samo vukove", "Samo ljude"], "tocan_odgovor": 0, "obasnjenje": "Bogatstvo života." },
    { "id": 85, "semester": 2, "pitanje": "Zube peremo radi...", "opcije": ["Jer moramo", "Zdravlja i higijene", "Zabave", "Strahova"], "tocan_odgovor": 1, "obasnjenje": "Sprječava karijes." },
    { "id": 86, "semester": 2, "pitanje": "Bjelančevine su važne za...", "opcije": ["Vodu", "Izgradnju mišića", "Šećer", "Mast"], "tocan_odgovor": 1, "obasnjenje": "Gradivne tvari." },
    { "id": 87, "semester": 2, "pitanje": "Pri izdisaju izlazi...", "opcije": ["Ugljikov dioksid", "Para", "Kisik", "Miris"], "tocan_odgovor": 0, "obasnjenje": "Otpadni plin stanica." },
    { "id": 88, "semester": 2, "pitanje": "Ugrožene vrste su one...", "opcije": ["Koje su jake", "Pred izumiranjem", "Koje lete", "Koje su brze"], "tocan_odgovor": 1, "obasnjenje": "Štitimo ih zakonom." },
    { "id": 89, "semester": 2, "pitanje": "Simbioza je...", "opcije": ["Samoća", "Kupnja", "Suživot s koristi", "Rat"], "tocan_odgovor": 2, "obasnjenje": "Oba bića imaju korist." },
    { "id": 90, "semester": 2, "pitanje": "Voda je...", "opcije": ["Samo slana", "Dragocjen resurs", "Beskonačna", "Nepotrebna"], "tocan_odgovor": 1, "obasnjenje": "Moramo štedjeti pitku vodu." },
    { "id": 91, "semester": 2, "pitanje": "Porast temperature Zemlje?", "opcije": ["Zima", "Mrak", "Sunce", "Globalno zatopljenje"], "tocan_odgovor": 3, "obasnjenje": "Uzrokovano stakleničkim plinovima." },
    { "id": 92, "semester": 2, "pitanje": "Ozonski omotač...", "opcije": ["Donosi kišu", "Štiti od UV zračenja", "Grije nas", "Ništa"], "tocan_odgovor": 1, "obasnjenje": "Štit od Sunca." },
    { "id": 93, "semester": 1, "pitanje": "Najveći planet?", "opcije": ["Mars", "Zemlja", "Jupiter", "Mjesec"], "tocan_odgovor": 2, "obasnjenje": "Najveći u Sunčevom sustavu." },
    { "id": 94, "semester": 1, "pitanje": "Mjesec je Zemljin...", "opcije": ["Sunce", "Susjed", "Zvijezda", "Prirodni satelit"], "tocan_odgovor": 3, "obasnjenje": "Kruži oko Zemlje." },
    { "id": 95, "semester": 1, "pitanje": "Kompas pokazuje...", "opcije": ["Zapad samo", "Sjever", "Istok samo", "Sat"], "tocan_odgovor": 1, "obasnjenje": "Glavna orijentacija." },
    { "id": 96, "semester": 1, "pitanje": "Reljefna maketa je...", "opcije": ["3D prikaz", "Video", "Papir", "Slika"], "tocan_odgovor": 0, "obasnjenje": "Prikazuje visinu reljefa." },
    { "id": 97, "semester": 1, "pitanje": "Velebit je...", "opcije": ["Otok", "Naša najduža planina", "Rijeka", "Grad"], "tocan_odgovor": 1, "obasnjenje": "Park prirode i planina." },
    { "id": 98, "semester": 1, "pitanje": "Prolaz između kopna je...", "opcije": ["Brdo", "Nizina", "Tjesnac (moreuz)", "Ocean"], "tocan_odgovor": 2, "obasnjenje": "Povezuje mora." },
    { "id": 99, "semester": 2, "pitanje": "Pranje ruku prije jela...", "opcije": ["Ništa", "Grije nas", "Ubija bakterije", "Čisti pod"], "tocan_odgovor": 2, "obasnjenje": "Prevencija bolesti." },
    { "id": 100, "semester": 2, "pitanje": "SharkLearn je...", "opcije": ["Težak rad", "Igra samo", "Avantura učenja", "Dosada"], "tocan_odgovor": 2, "obasnjenje": "Aplikacija za uspjeh!" }
];
